### ISSUE TITLE
Code duplication in .subscribe()

### ISSUE THREAD

**Issue by Yagger** [Reactive-Extensions/RxJS#1011]
How could we avoid code duplication if the same code needs to run disregarding what function is called (onNext, onError or onComplete).

In the following example, `this.loading.next(false)` is called in all scenarios - on success, on error and on complete.
Should be a way to add something like `finally()` function as optional fourth parameter, that will contain the code to be executed whatever happens.
```
.subscribe(
    (results: SearchResult[]) => {
        this.loading.next(false); // <== duplicated line of code
        this.results.next(results);
    },
    (error: any) => {
        console.log(error);
        this.loading.next(false); // <== duplicated line of code
    },
    () => {
        this.loading.next(false); // <== duplicated line of code
    }
);
```

**Comment by mattpodwysocki** [comment]
@Yagger yes, that's the point of `finally` where you can do something right as `onCompleted` or `onError` has been hit. I'm not sure why you are also calling this in `onNext`.

**Comment by samarpanda** [comment]
RxJS has already a `finally` function. But it will be triggered for `onComplete` & `OnError`, except `OnNext`. 
```js

var fn = function(){
  // Add your duplicate code here
}

//Assuming source to be one Observable
var source = source.finally(() => {
  console.log('Finally called for OnError or OnComplete');
  fn();
});

source.subscribe(
  () => {
    console.log('On Next handler');
    fn();
  }
);
```
This can avoid repetitive code in case of `onError` & `OnComplete`. Couldn't find any option as of now for `OnNext` as per your requirement.

For more details you can refer [RxJS operator finally](http://reactivex.io/documentation/operators/do.html)
![Rxjs operator Finally](http://reactivex.io/documentation/operators/images/finally.png)

**Comment by paulpdaniels** [comment]
You can use `materialize` for this purpose.

```javascript

var observer = Rx.Observer.create(
 (results: SearchResult[]) => this.results.next(results)
 (error: any) => console.log(error));

source
.materialize()
.subscribe(
    (notification: Notification) => {
        this.loading.next(false);
        notification.accept(observer);
    });


```
