### ISSUE TITLE
[Doc] – Observable has link to throttleFirst, but there is no one

### ISSUE THREAD

**Issue by kibin** [Reactive-Extensions/RxJS#1025]
[Observable docs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md) has link to `throttleFirst` [operators/throttlefirst.md](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/throttlefirst.md) (which results in 404), but there I see only [throttle.md](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/throttle.md). Are they the same?

**Comment by paulpdaniels** [comment]
Yes, the Observable docs link is wrong. It should be `throttle`
