### ISSUE TITLE
Optimised "resolver"

### ISSUE THREAD

**Issue by ronag** [Reactive-Extensions/RxJS#1032]
Based on the following issue https://github.com/Reactive-Extensions/RxJS/issues/943 I've implemented a "resolve" query which transforms an observable of array to another observable array based on a transformer/resolver.

Now this does what it needs to do. However, I'm encountering some performance issue. In particular I'm forced to put a `debounce` at the end in order to avoid each element causing a partial transformed array. I would like to avoid the `debounce` while still not getting immediate partial transformations.

Is that possible?

```javascript
import { Observable, Scheduler } from 'rx'
import R from 'ramda'

const _eof = {}

export default function resolve(xs$, resolver) {
  const keys$ = xs$
    .filter(x => x)
    .distinctUntilChanged()
    .shareValue([])

  const pairs$ = keys$
    .startWith([])
    .pairwise()
    .share()

  const add$ = pairs$
    .flatMap(([prev, curr]) => R.difference(curr, prev))
  const remove$ = pairs$
    .flatMap(([prev, curr]) => R.difference(prev, curr))

  return add$
    .flatMap(key => resolver(key)
      .takeUntil(remove$.filter(removeId => removeId === key))
      .concat(Observable.return(_eof))
      .map((x) => [key, x]))
    .scan((xs, [key, x]) => x === _eof
      ? R.dissoc(key, xs)
      : R.assoc(key, x, xs), {})
    .startWith({})
    .debounce(0)
    .combineLatest(keys$, (xs, keys) => keys.map(key => R.prop(key, xs)))
}

```

Example:

```
const props$ = Observable.return([1, 2, 3, 4])
resolve(props$, (x) => Observable.return(x * 2)).subscribe(::console.log)
// [2, 4, 6, 8]
```

**Comment by xgrommx** [comment]
Why not: 
```js
const props$ = Rx.Observable.return([1, 2, 3, 4]);
props$.map(x => x.map(_ => _ * 2)).subscribe(::console.log);
```

**Comment by ronag** [comment]
The example is not very good.

```javascript
const ids$ = ....
const values$ = resolve($ids, onValue)
```

Where onValue is a complicated stream (including server communication) transforming an id to an actual value.

**Comment by xgrommx** [comment]
@ronag I don't understand your case. =(

**Comment by ronag** [comment]
@xgrommx: Another try then.

This is how you would do the same thing using regular rxjs operators:

```javascript
const urls$ = ...
const images$ = urls$.flatMapLatest((urls) => Observable.combineLatest(...urls.map(loadImage), (...args) => [].concat(...args)))
```
However, this is rather inefficient since as soon urls$ change it will re load all the images. Thus, I use the "resolve" function to avoid this.

```javascript
const urls$ = ...
const images$ = resolve(urls$, loadImage)
```
The problem is. Though this is much more efficient in terms that `loadImage` is not called necessarily to fetch already fetched data. However, the resolve implementation in itself is rather inefficient.

**Comment by ronag** [comment]
Solved in https://github.com/Reactive-Extensions/RxJS/issues/1145
