### ISSUE TITLE
DistinctObservable is emitting duplicate values

### ISSUE THREAD

**Issue by jisaacks** [Reactive-Extensions/RxJS#1034]
I am using Rx with Cycle.js

I am mapping a list of click event observables into distinct keys like so:

 ```javascript
let distinctSelectedKeys$ = DOM
   .select('.keyboard-button')
   .events('click')
   .map(e => e.target.textContent)
   .distinct();
 
console.log(distinctSelectedKeys$); // <-- Confirmed this is a `DistinctObservable`
 
let selectedKeys$ = distinctSelectedKeys$
   .map(key => {
      console.log('got:', key); // <----- Getting duplicated values logged here
      return key;
    });
```

I am expecting to only ever log a single key, yet I am getting multiple logs of the same key. I was under the impression that the distinct observable would prevent this.

Am I misunderstanding  `DistinctObservable`?

**Comment by ronag** [comment]
Try adding the following to debug:

```javascript
 distinctSelectedKeys$
  .pairwise()
  .subscribe(([prev, current]) => console.log(prev === current))
```

It should only print false.

Remember `distinct` only performance reference based equality by default. So even though you think they have the same value it could be different references with the same value.

**Comment by jisaacks** [comment]
You are right I was getting all false. I think my problem was with using a scan, to always get a cumulative list of all the previous values, which was inadvertently duplicating each value at each scan. So I just switched to using a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) with my scan instead of an array and that fixed it.
