### ISSUE TITLE
Observable.timer(Infinity) completes immediately

### ISSUE THREAD

**Issue by eschwartz** [Reactive-Extensions/RxJS#1046]
I noticed that if you pass `Infinity` as the first argument to `Rx.Observable.timer()`, the observable completes immediately:

```js
Rx.Observable.timer(Infinity).
  subscribeOnCompleted(() => console.log('infinite timer complete'));
```

I would expect this observable to never complete.

My use case is that I have an operation which creates a new file, followed by an operation that deletes the file after a configured `ttl`. I would like to be able to pass in a config of `ttl = Infinity`, to indicate that I never want the file to be deleted. So my code looks like:

```js
createSomeFiles().
  flatMap(generatedFilePaths => Rx.Observable.
    timer(config.ttl).
    flatMap(() => deleteFiles(generatedFilePaths))
  );
```

**Comment by corps** [comment]
This has to do with javascript itself and is non trivial to fix.  Check this out:

```javascript
setTimeout(function() { console.log("hi"); }, Infinity);
```

This immediately fires.  All schedulers would have to be written to recognize Infinity as a special case number.  Is it possible you could pull the Rx.Observable.timer into a conditional variable, and on Infinity make a replacement for rx.Observable.never?

**Comment by eschwartz** [comment]
Oh that's silly -- I didn't know JS did that. As a side note, I also just learned that node has a max timeout of around 24 days, so I might need to rethink how I'm doing some of this.

Yes, I can certainly write some logic to get around this. I just thought this might be a bug in RxJS.
