### ISSUE TITLE
shareReplay triggers subscription when not expected

### ISSUE THREAD

**Issue by jhoguet** [Reactive-Extensions/RxJS#1052]
I am trying to wrap my head around hot observables, publish, and connect. 

I came across shareReplay which I thought was going to brings things together, but the results are not what I would expect. 

Given

```js
var interval = Rx.Observable.range(1, 2);

var source = interval
    .doAction(function (x) {
        console.log(`Side effect ${x}`);
    });

var published = source
    .shareReplay(1);

published.subscribe(x => console.log(`a ${x}`));
published.subscribe(x => console.log(`b ${x}`));
```

I expect the following
```
"Side effect 1"
"a 1"
"Side effect 2"
"a 2"
"b 2"
```
But I actually get
```
"Side effect 1"
"a 1"
"Side effect 2"
"a 2"
"b 2"
"Side effect 1"
```
Why is side effect 1 being called again, especially when it doesn't output 1 to any other subscribers?

I am sorry if this is something obvious - I am still ramping up on rx. 

http://jsbin.com/basufi/edit?js,console,output

**Comment by bouzuya** [comment]
Is this same problem? I use `v4.0.7`.

```js
import { Observable } from 'rx';

const observable = Observable
  .from([1, 2, 3])
  .do(value => console.log(`do: ${value}`))
  .replay(null, 2)
  .refCount();

observable
  .subscribe(
    value => console.log(`observer1 onNext: ${value}`),
    error => console.log(`observer1 onError: ${error}`),
    () => console.log('observer1 onCompleted')
  );
console.log('observer1 subscribed');

observable
  .subscribe(
    value => console.log(`observer2 onNext: ${value}`),
    error => console.log(`observer2 onError: ${error}`),
    () => console.log('observer2 onCompleted')
  );
console.log('observer2 subscribed');

// do: 1
// observer1 onNext: 1
// do: 2
// observer1 onNext: 2
// do: 3
// observer1 onNext: 3
// observer1 onCompleted
// observer1 subscribed
// observer2 onNext: 2
// do: 1
// observer2 onNext: 3
// do: 2
// observer2 onCompleted
// observer2 subscribed
```

I think here is suspicious:
https://github.com/Reactive-Extensions/RxJS/blob/v4.0.7/src/core/linq/connectableobservable.js#L10-L14
>    RefCountObservable.prototype.subscribeCore = function (o) {
>      var subscription = this.source.subscribe(o);
>      ++this._count === 1 && (this._connectableSubscription = this.source.connect());
>      return new RefCountDisposable(this, subscription);
>    };

synchronous source && `subscribe`

**Comment by jhoguet** [comment]
looks the same to me - I wouldn't expect do 1 and 2 to be repeated, especially when 1 is not observed due to the replay only emitting 2 and 3

**Comment by bouzuya** [comment]
`s/.from([1, 2, 3])/.interval(1).take(3)/`

```js
import { Observable } from 'rx';

const observable = Observable
  // .from([1, 2, 3])
  .interval(1).take(3)
  .do(value => console.log(`do: ${value}`))
  .replay(null, 2)
  .refCount();
observable.subscribe(value => console.log(`observer1 onNext: ${value}`));
console.log('observer1 subscribed');
observable.subscribe(value => console.log(`observer2 onNext: ${value}`));
console.log('observer2 subscribed');
// observer1 subscribed
// observer2 subscribed
// do: 0
// observer1 onNext: 0
// observer2 onNext: 0
// do: 1
// observer1 onNext: 1
// observer2 onNext: 1
// do: 2
// observer1 onNext: 2
// observer2 onNext: 2
```

**Comment by killercentury** [comment]
I found the same issue. The shareReplay only shares the result when you use interval but not range/from/just...

**Comment by jhoguet** [comment]
thanks for the feedback, I am still ramping up on RxJS but this is the part that I find least intuitive. 

It sounds like this is by design, so I'll close this.
