### ISSUE TITLE
[Question] Reactive-Streams style backpressure

### ISSUE THREAD

**Issue by akarnokd** [Reactive-Extensions/RxJS#1055]
Does it make sense in JavaScript to do non-blocking backpressure (in Reactive-Streams fashion) and are there plans to add such support?

**Comment by paulpdaniels** [comment]
You mean like [`controlled`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/backpressure/controlled.js)?

**Comment by akarnokd** [comment]
Nevermind, I'll just roll my own library for it.
