### ISSUE TITLE
`hasObservers` methods do not all behave the same

### ISSUE THREAD

**Issue by BerkeleyTrue** [Reactive-Extensions/RxJS#1058]
While most Observable.prototype.hasObservers methods use the Disposable.checkDisposed method internally to indicate that the observable has been disposed, some neglect this and instead will error `cannot read property length of null` after being disposed.

For example:
https://github.com/Reactive-Extensions/RxJS/blob/8f12f812d497acf639588e90f74d504a9fc801ec/src/core/subjects/subject.js#L33
https://github.com/Reactive-Extensions/RxJS/blob/30c794b028b4d3d3ebbd71883374cfbe9f62eb5f/src/core/subjects/behaviorsubject.js#L47
https://github.com/Reactive-Extensions/RxJS/blob/8d9fd2c7bb3d77bc701d4b53ee2446ed636f6ec7/src/modular/replaysubject.js#L77

**Comment by mattpodwysocki** [comment]
Fixed

**Comment by BerkeleyTrue** [comment]
Thanks!
