### ISSUE TITLE
CDN for beta.0 not working

### ISSUE THREAD

**Issue by filipesilva** [Reactive-Extensions/RxJS#1061]
CDN for beta.0, as per readme, doesn't seem to work:
https://npmcdn.com/@reactivex/rxjs@5.0.0-beta.0/dist/global/Rx.js

 cc @blesh, @jeffbcross, @robwormald

**Comment by filipesilva** [comment]
Is this the new one? I poked around for a bit and it seems to be match
https://npmcdn.com/@reactivex/rxjs@5.0.0-beta.0/dist/global/Rx.umd.js

**Comment by jeffbcross** [comment]
@filipesilva sorry, that was my mistake. This is not the correct Github project though, can you file this issue at github.com/reactivex/rxjs?

**Comment by jeffbcross** [comment]
And yes, the name has changed, but that is the correct umd/global bundle.

**Comment by filipesilva** [comment]
My bad! Filed it in https://github.com/ReactiveX/RxJS/issues/1072
