### ISSUE TITLE
Issue with Documentation (onErrorResumeNext)

### ISSUE THREAD

**Issue by tarwich** [Reactive-Extensions/RxJS#1063]
When trying to figure out how to suppress an error, I found this page, which describes a non-existent method: [Rx.Observable.onErrorResumeNext](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/errors.md#ignoring-errors-with-onerrorresumenext)

I downloaded the latest build (`4.0.7`) and dropped it into the browser and tried to use the method, but it doesn't seem to exist.

**Comment by maximus8891** [comment]
https://jsfiddle.net/ds6Ljs0q

Works fine. If you could share your code please?

**Comment by tarwich** [comment]
Now that I see your fiddle, I realize the problem is that I was using `rx.lite.js`.

https://jsfiddle.net/ds6Ljs0q/1/

Should I have known it was not included or that I needed `rx.all.js`?

**Comment by maximus8891** [comment]
Here is the list of included methods.
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/libraries/lite/rx.lite.md

**Comment by tarwich** [comment]
I guess that resolves this issue. Thanks for your help!
