### ISSUE TITLE
RxJS 5 beta: ofObjectChanges and ofArrayChanges

### ISSUE THREAD

**Issue by ghpabs** [Reactive-Extensions/RxJS#1068]
I can't seem to find both methods `ofObjectChanges` and `ofArrayChanges` in the new version.

Am I missing something here?

Thanks :-)

**Comment by mattpodwysocki** [comment]
@ghpabs both `Object.observe` and `Array.observe` have both been [withdrawn from consideration](https://mail.mozilla.org/pipermail/es-discuss/2015-November/044684.html) for standardization and will be removed from Chrome, so there is no need to keep those APIs as they were just shims to those underlying technologies
