### ISSUE TITLE
Question: Testing an observable that is disposed dynamically

### ISSUE THREAD

**Issue by tusharmath** [Reactive-Extensions/RxJS#1077]
I have a dumb question, I need to dispose a subscription dynamically —

```javascript
var scheduler = new Rx.TestScheduler();
var xs = scheduler.createHotObservable(
  onNext(150, 1),
  onNext(210, 2),
  onNext(220, 3)
);

scheduler.startScheduler(() => xs)

/**
Dispose me is a special function that disposes the subscription based on some external condition.
**/
disposeMe(xs.subscribe(x => console.log(x)))

```
Even if I could internally mock the external condition that is required to dispose the subscription, via `initiateDisposal()` how can I order it with the sequence of the hot observable i have already created?

**Comment by tusharmath** [comment]
One solution that I am working with is —
```javascript
scheduler.startScheduler(() => xs.tap(x => {
    if (x === 3) {
      initiateDisposal()
    }
  }))
```

Would this be correct? I don't like the idea of putting logic into my tests.

**Comment by paulpdaniels** [comment]
With the `TestScheduler` invoking `startScheduler` will run the scheduler until the `Observable` terminates. If you want to test that a subscription is disposed dynamically you need to step the clock forward explicitly.

```javascript

var scheduler = new Rx.TestScheduler();
var xs = scheduler.createHotObservable(
  onNext(150, 1),
  onNext(210, 2),
  onNext(220, 3)
);

scheduler.advanceBy(220);

initiateDisposal();

//Check you test conditions

```

**Comment by tusharmath** [comment]
That isn't documented, if I am not wrong?
Can I also pass a value to advanceBy —

```javascript
scheduler.advanceBy(225, 4);
initiateDisposal();
scheduler.advanceBy(230, 5);
````

So technically my subscription doesn't get value `5`.

**Comment by paulpdaniels** [comment]
It could very well be that it isn't terribly well documented. `TestScheduler` is really just a [`VirtualTimeScheduler`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/schedulers/virtualtimescheduler.md) with some additional helpers for dealing test specific use cases. `advanceBy` only takes a single time argument. What is the second argument you are trying to pass?

**Comment by tusharmath** [comment]
Second argument is the value that I want to dispatch.

So I have a stream like this `---1--2--3--4--5-- ... n` to which I need to be subscribed to unless someone one calls `initiateDisposal` which would just dispose my subscription and thus all other values go ignored.

**Comment by paulpdaniels** [comment]
Your mixing two different things. The `advanceBy` is just to increment the schedulers notion of time. You have already scheduled the items to be processed when you created the hot `Observable`. Why do you not just use another `Observable` with [`takeUntil`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/takeuntil.md)?

**Comment by tusharmath** [comment]
@paulpdaniels Got it! This is awesome. Works perfectly for me.

I like the takeUntil approach as well by again I would have faced the same issue. 

advanceBy should definitely be documented. It amazing to see how u can pause a hot observable and then continue later when you are writing tests.
