### ISSUE TITLE
Forcing HistoricalScheduler to be the global default?

### ISSUE THREAD

**Issue by memelet** [Reactive-Extensions/RxJS#1079]
We have a system that processes events from hardware devices. Each event has a timestamp, and the event-source ensures that the events are delivered strictly increasing in time. We need to advance the clock only based on the event timestamps; never based on the computer clock.

Is there way to override *all* schedulers so that all streams run in "event time"? Or to put it another way, is there a way to force the HistoricalScheduler to be always used even when no scheduler is passed to the operator?

For example, could I simply overwrite 'global.Rx.defaultScheduler' to be the HistoricalScheduler?

**Comment by mattpodwysocki** [comment]
@memelet which operators are you thinking of?  It is possible to do that, yes if it's truly being used for simulation purposes.  Otherwise you can simply overwrite the operator to use whichever scheduler you want.

```js
var oldTimestamp = Observable.prototype.timestamp;

Observable.prototype.timestamp = function () {
  var scheduler = global.historicalScheduler;
  return oldTimestamp.call(this, scheduler);  
};
```

Would that work as well so you didn't have to remember to pass it in at all places?

**Comment by memelet** [comment]
This is not for simulation purposes, but for processing events based on their timestampts rather than the system clock. All of our operaters would be operating on event time, so I would not to have to specify a scheduler for every operator usage.

What we have (but with rx5, where the code base was much easier to work with) is use the lolex project to replace the node.js "clock" with an externally controlled clock. Now all operators can just use the normal schedulers but the application advances the clock as events are pushed. 

For the very small parts of this system that needs to use the system clock, we have a customer scheduler that users the original node.js "clock". So for those uses we do have to specify the scheduler in operators -- but that is a tiny percenterage. 

Of course, this setup is very specific to a service that processes timeseries events which arrive in bursts. Not really something general purpose.
