### ISSUE TITLE
throttleFirst is missing

### ISSUE THREAD

**Issue by akauppi** [Reactive-Extensions/RxJS#1094]
It seems like the `throttleFirst` method should be implemented on observables, but it gives `undefined` in practise. I'm using rx-lite 4.0.7 via `npm`.

- [this page](https://github.com/Reactive-Extensions/RxJS/blob/8f12f812d497acf639588e90f74d504a9fc801ec/modules/rx-lite-time-compat/readme.md) mentions it but the link is a [404](https://github.com/Reactive-Extensions/RxJS/blob/8f12f812d497acf639588e90f74d504a9fc801ec/doc/api/core/operators/throttlefirst.md)
- the [backpressure sample](https://github.com/Reactive-Extensions/RxJS/blob/8f12f812d497acf639588e90f74d504a9fc801ec/doc/gettingstarted/backpressure.md) uses it

I am trying to implement backpressure to a dragging coordinate stream, and `throttleFirst` seems like the right (only) way to do it.

```git grep```shows that it's only in the docs, and some old tests - not in `src`, at all:

```
$ git grep throttleFirst | grep -v .map | grep -v .min
doc/gettingstarted/backpressure.md:Another technique to deal with an observable sequence which is producing too much for the consumer is through throttling with the use of the [`throttleFirst`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/throttlefirst.md) method which emits the first items emitted by an Observable within periodic time intervals.  Throttling can be especially useful for rate limiting execution of handlers on events like resize and scroll.
doc/gettingstarted/backpressure.md:  .throttleFirst(250 /* ms */);
modules/rx-lite-compat/readme.md:- [`throttleFirst`](../../doc/api/core/operators/throttlefirst.md)
modules/rx-lite-time-compat/readme.md:- [`throttleFirst`](../../doc/api/core/operators/throttlefirst.md)
modules/rx-lite-time/readme.md:- [`throttleFirst`](../../doc/api/core/operators/throttlefirst.md)
modules/rx-lite/readme.md:- [`throttleFirst`](../../doc/api/core/operators/throttlefirst.md)
tests/perf/old/rx.all.compat.js:  observableProto.throttleFirst = function (windowDuration, scheduler) {
tests/perf/old/rx.all.js:  observableProto.throttleFirst = function (windowDuration, scheduler) {
tests/perf/old/rx.lite.compat.js:  observableProto.throttleFirst = function (windowDuration, scheduler) {
tests/perf/old/rx.lite.js:  observableProto.throttleFirst = function (windowDuration, scheduler) {
tests/perf/old/rx.time.js:  observableProto.throttleFirst = function (windowDuration, scheduler) {
```

**Comment by mattpodwysocki** [comment]
@akauppi that is a bug in the documentation, it should be using `throttle` as we renamed it back in RxJS v3 or v4.
