### ISSUE TITLE
Unable to observe changes within a deep object (more than 1 level down)

### ISSUE THREAD

**Issue by mcpDESIGNS** [Reactive-Extensions/RxJS#1113]
Unless I'm using this incorrectly, why isn't this able to see *deep* changes within a larger object?

It works great with a simple var `obj = { x : 1 };` object, but what about a normal / more complicated one?

    var obj = {
        x : 1,
        deeper : {
           y : 0
        },
        someArray : []
    };

If `obj.x` is changed, it will be aware and trigger `onNext` but if you try:

    obj.deeper.y = 1; // nothing gets triggered within the subscription
    obj.someArray.push(1); // nothing gets triggered within the subscription

Is this intentional or am I missing something?

**Comment by mathiasmoeller** [comment]
@MarkPieszak Did you find a good solution for that?
The only solution I found is this (and i don't really like this):
```
var source = rx.Observable.merge(
  rx.Observable.ofArrayChanges(a),
  rx.Observable.from(a).flatMap(function(item) {
    return rx.Observable.ofObjectChanges(item);
  })
);
```

**Comment by MarkPieszak** [comment]
Hey @mathiasmoeller, unfortunately no I got as far as that old post.

But on the bright side, now I've switched to using Immutables. Instead of doing mutable changes to arrays & objects, I completely replace them with new copies (changing only the parts that I needed).

**Comment by mathiasmoeller** [comment]
@MarkPieszak thanks for that suggestion! This should work for me as well :)
