### ISSUE TITLE
Importing custom operators as modules

### ISSUE THREAD

**Issue by alexanderGugel** [Reactive-Extensions/RxJS#1115]
Currently the recommended way to add custom operators is to set them on the Observable prototype. Assuming `flatMap` wasn't part of RxJS, it could be added by setting it as `prototype.flatMap`:

```js
Rx.Observable.prototype.flatMap = function (selector) {
    return this.map(selector).mergeObservable();
};
```

(see [Implementing Your Own Observable Operators](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/operators.md))

I think it's fair to say that mutating the prototype of a possibly shared constructor is not a good idea when writing applications that are heavily modularised (and therefore are likely to have a shared dependency on RxJS).

Possible drawbacks include naming conflicts with other dependencies that implement the same operator (in a potentially very different way), resulting code that is hard to debug due to the import having side effects on the library itself etc.

This issue was mentioned on [Twitter](https://twitter.com/dan_abramov/status/577249077584379905) a while ago:

> I wish RxJS was like Lodash in that individual functions could be imported and used.

I know this tweet has been addressed in a way via the [Gist](https://gist.github.com/mattpodwysocki/a1e070ecb43a10c36c09) referenced [afterwards](https://twitter.com/ReactiveX/status/578266804214054912), nevertheless, I don't think this actually solves the issue, it just changes the object affected by it. Of course it would be possible to subclass Observable, but that seems rather excessive and would require multiple inheritance (or mixins) when using multiple custom (or third party) operators on the same, shared observable constructor (`rx.observable` in the references example).

I would therefore propose a - what I think is a more modular and extensible way to do it. Maybe I'm missing something and a method like that already exists somewhere in RxJS (apologies in that case):

Why can't we have a method (let's just call it "through" for now) on the Observable that can be used for chaining via custom operators?

The implementation would be a trivial one-liner:

```js
Rx.Observable.prototype.through = function (fn) {
    return fn(this);
};
```

That way, flatMap could be imported as an external library and used via `through`:

```js
import flatMap from 'rx.flatMap'
observable.map(someSelector).through(flatMap(selector)).map(someOtherSelector)
```

The `flatMap` module would export a single function:

```js
export default function flatMap (selector) {
  return function (observable) {
    return observable.map(selector).mergeObservable();
  }
}
```

Custom operators would have to return the resulting observable.

Thoughts or concerns?

**Comment by paulpdaniels** [comment]
This is in progress currently if you look in the [`modular`](https://github.com/Reactive-Extensions/RxJS/tree/master/src/modular) folder.

**Comment by alexanderGugel** [comment]
@paulpdaniels All those operators are still being set directly on the prototype.

Nevertheless, there seems to be an operator that does exactly what I was looking for: https://twitter.com/ReactiveX/status/693904998137208832

Sorry for the confusion! Missed that one!
