### ISSUE TITLE
Observable stream from web socket

### ISSUE THREAD

**Issue by bolshchikov** [Reactive-Extensions/RxJS#112]
What's the best way to make an observable stream from the web socket? 
I've written the brute force implementation but there might be a better way?

```
Rx.Observable.fromWebSocket = function (websocket) {
  return new Rx.Internals.AnonymousObservable(function(observer) {
    websocket.onmessage = function (msg) {
      observer.onNext(msg);
    };
    websocket.onerror = function (err) {
      observer.onError(err);
    };
  });
};
```

here's an [example](http://jsbin.com/xayut/22/edit)

**Comment by MarkPieszak** [comment]
Very nice! Can't wait to try this. Thanks @rehia

**Comment by rehia** [comment]
You're welcome @MarkPieszak. But my post is quite old, and I'm pretty sure something more "supported" exists by now.
But great it could help!

**Comment by LongLiveCHIEF** [comment]
@rehia I can't thank you enough.  I was toiling away with a much more complicated approach, and when I finally saw how you leveraged the `packet`, I was able to use this to great advantage.

I spent some time looking for something more official, and couldn't find it, so I decided to fork and update @mattpodwysocki's `rx-node` module for RxJSv5, and then I also created [`RxSocket.io`](https://github.com/HackerHappyHour/RxSocket.io) which is starting to shape up nicely, thanks in part to your hard work in digging through socket.io's source code.  I know their docs completely lack anything on `packet`.

I prefer to have a code-reviewer before I publish anything as a "v1/release" on npm, and I was hoping that you'd be willing to give some feedback when I get to that point with [`RxSocket.io`](https://github.com/HackerHappyHour/RxSocket.io).

Also, lmk if you'd prefer to be a contributor/maintainer instead.

**Comment by rehia** [comment]
Thanks @LongLiveCHIEF for your feedback!
I'll take a look to it!
I must admit that my post is quite old now, and that I don't use Rx and socket.io so much these days.
But I'll be ok to help as I can.

**Comment by LongLiveCHIEF** [comment]
I've got plenty of org team members to do the job, but I wanted to make sure you had the opportunity if you wanted it.

**Comment by evanjmg** [comment]
Any update to this is @rehia 's solution still the go to?

**Comment by daixtrose** [comment]
IMHO @rehia 's solution violates the golden and stone-cast rule that after an `onError` or `onCompleted` an observable **must not** emit anything else. A sequence `onError - onError` is definitely not allowed, but possible with this code. Therefore extra measure has to be taken that this will never occur.

**Comment by kundankale** [comment]
can somebody help me out here? 
i have paired two android devices using wifi direct. even i can send file between two devices using socket . I want to know , can i observe socket input output stream using rxJava?
