### ISSUE TITLE
Throw arguments incorrect in documentation.

### ISSUE THREAD

**Issue by bennadel** [Reactive-Extensions/RxJS#1130]
I was [asked to file a bug](https://twitter.com/mattpodwysocki/status/700827793542656001) around the documentation for the arguments in Throw.md:

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/throw.md

It says you can use dueTime, but it doesn't appear to work.

**Comment by j4ckcyw** [comment]
I run into this as well.
