### ISSUE TITLE
Getting extra elements in flatMap?

### ISSUE THREAD

**Issue by tjwudi** [Reactive-Extensions/RxJS#1151]
Hi, I have the following code chaining a response stream after a click event stream.

```
const submitClick$ = Rx.DOM.click(this.$container.find('.submit')[0]);
submitClick$.subscribe(() => console.log('click'));
const response$ = submitClick$.flatMap(() => {
  console.log('within response$');
  return Rx.DOM.post({
    url:  /* ... */,
    headers: /* ... */,
    body: /* ... */
  });
});
```

I am also using RxDOM. When **exact one** click event is fired, I got following log.

```
click
within response$
within response$
within response$
```

`click` message is supposed to appear once, which is about right. But the `within response$` actually appeared three times. It should be also one time though. Any thoughts?

**Comment by tjwudi** [comment]
Just confirmed it's not RxDOM's issue by using `Rx.Observable.fromEvent(this.$container.find('.submit'), 'click')` instead, still having the issue.

**Comment by tjwudi** [comment]
Also used `map().concatAll()` instead of `flatMap()`, still :(

**Comment by tjwudi** [comment]
Interesting enough that the following code works OK.

```
submitClick$.map(() => 1).subscribe(() => console.log('ok'));
```

It outputs one `ok`.

**Comment by tjwudi** [comment]
OK I know why ... `response$` was subscribed three times actually in my code. So that `flatMap` got called three times. Is this the expected behavior? I think even `response$` was subscribed multiple times, it's `flatMap`/`map` callback should only be called once. That could also be a good performance deal.

**Comment by tjwudi** [comment]
A shorter version of this issue is

```
const nums$ = Rx.Observable.interval(1000);
const nums$$ = nums$.map((num) => {
  console.log('OK');
  return Rx.Observable.of(num)
});

nums$$.subscribe((num) => num);
nums$$.subscribe((num) => num);
```

See [jsbin](http://jsbin.com/mazehe/edit?html,js,console)

**Comment by tjwudi** [comment]
Possibly duplicate of #294 but that's about Subject.

**Comment by davidwdan** [comment]
@tjwudi  That is the expected behavior. `nums$` is a cold observable, so each subscription starts from the beginning. The subscription is not shared. You can learn more about hot vs cold observables here: https://egghead.io/lessons/rxjs-demystifying-cold-and-hot-observables-in-rxjs

**Comment by tjwudi** [comment]
@davidwdan Definitely helpful. Thanks!
