### ISSUE TITLE
shareReplay resubscribes to source after stream is complete

### ISSUE THREAD

**Issue by Roaders** [Reactive-Extensions/RxJS#1155]
In this JSBin:

https://jsbin.com/dupucakato/2/edit?js,console

I have a stream that represents a slow, expensive http call that I only want to call once. I shareReplay(1) the stream so that multiple subscriptions can use the result from the http call without making the call twice.

This works fine for the first 2 streams as the second stream subscribes whilst the http stream is still waiting for a result.

Stream 3 however subscribes after the http stream has completed. It still gets the cached value but the expensive http call is kicked off again and the result ignored.

Is this a bug with shareReplay? What operator should I use to do this if it is not a bug?

Many Thanks

**Comment by rhendric** [comment]
If I'm not mistaken, this is a dupe of #1112, which I just fixed! Try updating to the new 4.1 release and see if you still have trouble.

**Comment by Roaders** [comment]
Yes, brilliant, that's fixed it thanks.
