### ISSUE TITLE
[Question]: Does an observable passed to Observable.merge() immediately delete its state after being processed?

### ISSUE THREAD

**Issue by alpha-X-omega** [Reactive-Extensions/RxJS#1161]
I am facing the following issue: if I remove `saveEntry$` from `Observable.merge()`, my `cli$` executes fine.  If I include `saveEntry$` in `Observable.merge()`, the `query` parameter in my filter function under `cli$` becomes the empty string.  I want to be able to use `submitQuery$` in different merged streams and associate each stream with different states.  Is this the wrong way to do it?

The only working hack I came up with was to replace my `cli$` with `submitQuery$.forEach()`/`submitQuery$.subscribe()` and declare my local state before it.

    const submitQuery$ = DOM.select('.omnibox').events('keydown')
      .filter(({keyCode}) => keyCode === VK_RETURN)
      .map(({target}) => target.value);

    const saveEntry$ = submitQuery$
      .map(entry => Operations.saveEntry(entry));

    const operations$ = Rx.Observable.merge(
      observableA$, observableB$, saveEntry$, some_other_observables...);

    const state$ = operations$
      .startWith({log: [''], input: '', logIndex: 0})
      .scan((state, operation) => operation(state));

    const cli$ = Rx.Observable.merge(['my', 'commands'].map(cmd =>
      submitQuery$
        .filter(query => query.startsWith(cmd))
        .map(query => Operations[cmd](query))
    ))
    .startWith({realpath: '', result: ''})
    .scan((state, cmd) => cmd(state));

**Comment by phnguyen89** [comment]
I just tried simplifying it by integrating `cli$` with `state$ and still the same issue occurs.  The final fix I'm going with is to order my `Observable.merge()` so that `submitQuery$` happens last.  Really weird....?

**Comment by alpha-X-omega** [comment]
I figured out the solution: use Kefir.js since that implementation doesn't have this problem and `merge().subscribe()` problem.
