### ISSUE TITLE
ofObjectChanges obselete

### ISSUE THREAD

**Issue by bradjohnwoods** [Reactive-Extensions/RxJS#1166]
As **ofObjectChanges** is built on **Object.observe()** which is obsolete (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/observe) is there an alternative for watching object property changes?

**Comment by mattpodwysocki** [comment]
@bradjohnwoods no, there are no other alternatives unless you want to polyfill the behavior such as this https://github.com/jdarling/Object.observe

**Comment by mathiasmoeller** [comment]
@bradjohnwoods did you find any solution for this problem?

**Comment by bradjohnwoods** [comment]
I ended up using a different approach of events rather than watching
variables.
