### ISSUE TITLE
map isn't "lawful"

### ISSUE THREAD

**Issue by krainboltgreene** [Reactive-Extensions/RxJS#1169]
Not sure if this is intended, but it doesn't seem to behave as described [here](https://github.com/fantasyland/fantasy-land#functor), passing three more arguments than specified.

This results in hilariously fun situations like https://github.com/plaid/sanctuary/issues/167

Any thoughts on changing?

**Comment by roganov** [comment]
RxJS's `map` follows the signature of `Array.prototype.map`.

**Comment by mattpodwysocki** [comment]
@krainboltgreene not likely as that would be a breaking change as well as a deviation from our other versions such as Rx .NET's Select method.  Seems like a bug in sanctuary as ramda handles the inputs just fine from map.

**Comment by krainboltgreene** [comment]
@mattpodwysocki If you read the issue it's not a bug in sanctuary and not only ramda "handl[ing] it just fine", it's that sanctuary enforces Fantasy Land specification and Ramda doesn't.

Further it seems like of the other observable libraries seem to be abiding by the Fantasy Land specification. I think I'm just going to use them instead of switching away from safe functions like sanctuary's pipe.
