### ISSUE TITLE
fromPromise typings missing the Scheduler parameter

### ISSUE THREAD

**Issue by babeal** [Reactive-Extensions/RxJS#1182]
There is an issue with typings for the fromPromise method.  The second parameter, Scheduler, is not available.  

RxJs/fromPromise.js which the same method that's found in the rx.js distributed file.
...

``` javascript
module.exports = function fromPromise(promise, scheduler) {
  Scheduler.isScheduler(scheduler) || (scheduler = Scheduler.async);
  return new FromPromiseObservable(promise, scheduler);
};
```

...

Rx.a

``` javascript
export interface ObservableStatic {
        /**
        * Converts a Promise to an Observable sequence
        * @param {Promise} An ES6 Compliant promise.
        * @returns {Observable} An Observable sequence which wraps the existing promise success and failure.
        */
        fromPromise<T>(promise: Promise<T>): Observable<T>;
    }
```

**Comment by amoerie** [comment]
Just ran into this problem too. I thought it was actually deleted as a parameter, updated all my code to remove the scheduler, only to find out this is just a typings issue. I'll manually fix the typings file locally, but please prevent this from happening in the future... :-(

**Comment by zyh825** [comment]
+1
