### ISSUE TITLE
distinctUntilChanged broken or API change?

### ISSUE THREAD

**Issue by 0x80** [Reactive-Extensions/RxJS#1188]
This example from the docs 

```javascript
/* With key selector */
Observable.of({value: 42}, {value: 42}, {value: 24}, {value: 24})
  .distinctUntilChanged(x => x.value)
  .subscribe(
    function (x) {
      console.log('Next: ', x)
    },
    function (err) {
      console.log('Error: ' + err)
    },
    function () {
      console.log('Completed')
    }
  )
```

output v4 (as expected):
```
Next:  { value: 42 }
Next:  { value: 24 }
Completed
```

output v5:
```
Next:  { value: 42 }
Completed
```

**Comment by david-driscoll** [comment]
the parameters are different between rxjs5 and rxjs4 it looks like.

in rxjs4: `distinctUntilChanged = function (keyFn, comparer)`
in rxjs5: `distinctUntilChanged<T, K>(compare?: (x: K, y: K) => boolean, keySelector?: (x: T) => K)`

If this is something you think should be changed, feel free to raise issue over at https://github.com/ReactiveX/rxjs

**Comment by 0x80** [comment]
Oops I meant to post this in the v5 repo.

I have a hard time understanding the new API from just the type signature, and the links in the v5 docs are [dead](https://github.com/ReactiveX/rxjs/blob/master/class/es6/Observable.js~Observable.html#instance-method-distinctUntilChanged). How would you write the above call to distinctUntilChanged with v5 arguments?

**Comment by david-driscoll** [comment]
the comparer and the key selector are just swapped.

`.distinctUntilChanged(x => x.value)` -> `.distinctUntilChanged(null, x => x.value)`

**Comment by 0x80** [comment]
Aaah :smiley: thanks! 

Could you maybe point me to where this is documented?

**Comment by david-driscoll** [comment]
The docs are a work in progress, but as they get fleshed out they get updated @ http://reactivex.io/rxjs/

**Comment by 0x80** [comment]
Ok, I think I better stick to v4 then for now :+1:

**Comment by spankyed** [comment]
This is poorly documented.
