### ISSUE TITLE
Would using toPromise result in memory leaks?

### ISSUE THREAD

**Issue by cristi-badila** [Reactive-Extensions/RxJS#1206]
Hi, I found myself recently using the `toPromise` method on one of my observables and was curious how it was implemented so I took a quick look. What I don't quite understand is how is the resulting `Subscription` being disposed of? Won't the `Subscription` object still be hooked to the Observable even though the promise was resolved/rejected?

Here's the code for quick reference

```
module.exports = function toPromise(source, promiseCtor) {
  promiseCtor || (promiseCtor = global.Promise);
  return new promiseCtor(function (resolve, reject) {
    // No cancellation can be done
    var value;
    source.subscribe(function (v) {
      value = v;
    }, reject, function () {
      resolve(value);
    });
  });
};
```

**Comment by NoNameProvided** [comment]
I am no RxJs expert, but resolve called as the `onCompleted` method, and after onCompleted, observers are cleaned up:

```js
onCompleted: function () {
    Disposable.checkDisposed(this);
    if (this.isStopped) { return; }
    this.isStopped = true;
    for (var i = 0, os = cloneArray(this.observers), len = os.length; i < len; i++) {
      os[i].onCompleted();
    }

    this.observers.length = 0;
  },
```

So there should be no memory leak.

**Comment by cristi-badila** [comment]
@NoNameProvided thanks for taking the time to reply. The code you quoted clears things up for me.
