### ISSUE TITLE
.d.ts and Rx.Observable.fromEvent

### ISSUE THREAD

**Issue by acopalipsis** [Reactive-Extensions/RxJS#1208]
```Rx.Observable.fromEvent(new EventEmitter(), 'update');```  
> ERROR: src/index.tsx(64,15): error TS2339: Property 'fromEvent' does not exist on type 'ObservableStatic'.

**Comment by virtualvoid** [comment]
many "from" methods disappeared after 5.0.0-beta2 ... 

so I second this.

when can we get explanation ?

**Comment by paulpdaniels** [comment]
@virtualvoid RxJS5 is not maintained through this repo. @acopalipsis what version are you using? If > 4, please resubmit your issue at https://github.com/ReactiveX/rxjs.

**Comment by acopalipsis** [comment]
I use 4++ version. Problem solved, had to add the ``rx.all.d.ts`` instead of ``rx.d.ts``.
