### ISSUE TITLE
Debounce is not working

### ISSUE THREAD

**Issue by cironunes** [Reactive-Extensions/RxJS#1212]
Am I missing something or this is supposed to work?

http://jsbin.com/coxupuyixo/1/edit?js,console,output

**Comment by roganov** [comment]
This repository is for RxJS v4, while you're using [RxJS v5](https://github.com/ReactiveX/rxjs). In RxJS5 `debounce` was split into `debounce`, which takes a duration selector as an argument, and `debounceTime`, which takes a number. You clearly need `debounceTime`.

**Comment by cironunes** [comment]
Thanks for the answer @roganov. I knew that I was missing something...
