### ISSUE TITLE
error TS2339: Property 'from' does not exist on type 'typeof Observable'. 

### ISSUE THREAD

**Issue by virtualvoid** [Reactive-Extensions/RxJS#1222]
import { Observable } from 'rxjs/Observable';
import 'rxjs/Rx';
...
Observable.from(this.resourceStaffs)

it worked in beta-2

**Comment by virtualvoid** [comment]
So here's what i need to do with rxjs 5.0.0-beta.6:

    Observable
      .fromArray(this.resourceStaffs)
      .map((resourceStaff: ResourceStaff, index: number) => this._resourceService.saveResourceStaff(resourceStaff, index))
      .zipAll()
      .subscribe((objectIndices: Array<ObjectIndex<ResourceStaff>>) => { ... })

can anybody help me please ? the `.fromArray` and `.zipAll` doesn't exists anymore

**Comment by jordanluyke** [comment]
`import {Observable} from 'rxjs/Rx';` seemed to fix it for me

**Comment by jmalonzo** [comment]
@virtualvoid The repo for Rx 5.x is at github.com/ReactiveX/RxJS. You might be able to get more help there.

**Comment by virtualvoid** [comment]
@jmalonzo thanks
