### ISSUE TITLE
count() complete sequence whose source is incomplete

### ISSUE THREAD

**Issue by TimCodes** [Reactive-Extensions/RxJS#1224]
I have an obeservable sequence, where each time a call realease event occurs I map that event to an http request that returns some call logs that I then filter and need to get a count form. The problem is that even though the mapped Observable that returns the json from the http request  sequence has completed the orginal fromEvent Observable has not terminated so count will not emit anything. I need a count of the filtered amount each time the http request comes back not sure how to do this. Any help would be awesome

```
var seq = Rx.Observable
        .fromEvent(call realease event)
        .flatMap(agentObj => 
          Rx.Observable.fromPromise(callLogHelper.getUserCallLogs(agentObj.agentId))
        )
        .flatMap(logs => Rx.Observable.fromArray(logs))
        .filter(log => log.callTime >= 210)
        .count();
```

**Comment by paulpdaniels** [comment]
`flatMap` and `filter` both have index arguments that you could use to get a running count:

`.filter((value, index) => {});`

`.flatMap((value, index1) => { Observable.of(inner); }, (outer, inner, index1, index2) => {})`

**Comment by TimCodes** [comment]
@paulpdaniels  thanks for the quick response 

I need the count to be reset each time the fromEvent Obeservable emits a value.  I tried using the Index method and because the data returned  from the fromPromise Observable emits can contain the same data emitted by a previous value the idx is artificially  high. For instance a call is released and the idx is 12 and then a second later a call is released and the index jumps to 24 when it should still be 12.

**Comment by TimCodes** [comment]
ended up with this 
```
var seq = Rx.Observable
        .fromEvent(call realease event)
        .flatMap(flatMap(agentObj => 
             Rx.Observable.fromPromise(callLogHelper.getUserCallLogs(agentObj.agentId))
        ))
        .flatMap((logs) => {
             var filteredLogs = logs.filter(log => log.callTime >= 210);
             return  Rx.Observable.of(filteredLogs.length);
         })
```
