### ISSUE TITLE
Object.observe() not supported in Chrome 50

### ISSUE THREAD

**Issue by mathiasmoeller** [Reactive-Extensions/RxJS#1234]
RxJS version 4.1.0
Chrome version: 50.0.2661.102

I am using RxJS to observe an Object:
```
Rx.Observable.ofObjectChanges(observerdObject).subscribe(() => {
    doSomething();
});
```

Since Chrome removed `Object.observe()` in [version 50](https://developers.google.com/web/updates/2016/02/chrome-49-deprecations?hl=en#objectobserve-is-deprecated) I get the following error:

```
angular.js:12520 TypeError: Object.observe is not supported on your platform
    at Function.Observable.ofObjectChanges (rx.all.js:2903)
```

Is there a workaround or another way to watch for object changes?

**Comment by mattpodwysocki** [comment]
@mathiasmoeller no, since `Object.observe` was removed from the standardization process, it has also been removed from Chrome.  There is nothing we can do here short of you using a polyfill.
