### ISSUE TITLE
flatMap performance

### ISSUE THREAD

**Issue by cortopy** [Reactive-Extensions/RxJS#1238]
The following filtering of an ObservableArray is extremely slow and resource hungry:

```JS
Observer.fromArray(myArray)
  .flatMap(el => {return el; })
  .filter(el => {return !el.property; })
  .subscribe(validEl => {
    console.log(validEl);
  });
```
However, this isn't:

```JS
Observer.fromArray(myArray)
  .subscribe(arr => {
    let filteredArr = arr.filter(el => { return !el.property; });
    console.log(filteredArr);
  });
```

A quick look at my laptop resources shows that the former takes CPU usage over the roof. Having tried different variations this only happens when I use the flatMap operator.

For what I can gather the filter operator does not work on ObservableArray directly. I'm puzzled about this as the array's length is only 300

**Comment by roganov** [comment]
This seems like a perfectly synchronous code, why would you want to use Rx for this?

**Comment by cortopy** [comment]
@roganov I edited my code for the shake of simplicity. The array is returned by an observable. I'm using [@ngrx/store
](https://github.com/ngrx/store/blob/master/src/store.ts)

**Comment by davidwdan** [comment]
@roganov ngrx/store uses RxJS v5 which lives in a [different repo](https://github.com/ReactiveX/RxJS)

**Comment by cortopy** [comment]
@davidwdan thanks for the pointer. Issue now reported in that repo
