### ISSUE TITLE
interval suddenly stop to produce the value when I use switchMap.

### ISSUE THREAD

**Issue by rchaser53** [Reactive-Extensions/RxJS#1248]
I want to continue to produce the value during I am pushing the key.
But interval suddenly stop to produce the value.
(After keyup interval restart to produce the value.)

I use interval and switchMap like below.

rx.Observable
	.fromEvent(window,'keydown')
	.switchMap((e)=>{
		return rx.Observable.interval(150);
	}).subscribe((x)=>{
		console.log(x);
	});

How should I do?

**Comment by jmalonzo** [comment]
@rchaser53 What are you using interval for here? Is it for throttling/debouncing?

**Comment by rchaser53** [comment]
Sorry, my explanation isn't good.
What I'm trying to code is the same key's keydown event continues until the same key's keyup event happens.

But A key's keydown event stops when B key's keydown event happens in my code.
I want to continue A keydown event until A keyup event start.

Thank you in advance.

The code I wrote is below for your information.
(I want to make a kind of shooting game.)

```
const keyup = rx.Observable.fromEvent(window,'keyup');
const keydown = rx.Observable
					.fromEvent(window,'keydown')
					.map((e)=>{
						return e.keyCode;
					});

const shot = keydown
				.filter((keyCode)=>{
					return (keyCode === 38);
				})
				.throttle((x)=>{
					return rx.Observable.of(x).delay(300);
				});

const speedup = keydown
					.filter((keyCode)=>{
						return (keyCode === 37 || keyCode === 39);
					}).throttle((x)=>{
						return rx.Observable.timer(50);
					});

shot.takeUntil(keyup);
shot.subscribe((x)=>{
	// something to do
})

keyup.subscribe(()=>{
	// something to do
})

speedup.takeUntil(keyup);
speedup.subscribe((code)=>{
	// something to do
});
```

**Comment by BenoitAverty** [comment]
I've come up with a solution. I hope I undeerstood your problem correctly...

```
const keyDownEvent$ = Rx.Observable
  .fromEvent(window, 'keydown')
  .map(() => true);
const keyUpEvent$ = Rx.Observable
  .fromEvent(window, 'keyup')
  .map(() => false);
const events = keyDownEvent$.merge(keyUpEvent$);

const fire = Rx.Observable.interval(150)
  .withLatestFrom(events, (i, e) => e ? i : undefined)
  .filter((e) => e !== undefined));

fire.subscribe(e => console.log(e));
```

You can add your other filters (filtering the keyDownEvent stream based on which key was pressed) and customise the delay of the interval.

You can also use mapTo instead of map, but it doesn't work on jsbin for some reason.

**Comment by rchaser53** [comment]
Great! It works. Thank you so much!
