### ISSUE TITLE
Subject next function

### ISSUE THREAD

**Issue by bretthodel** [Reactive-Extensions/RxJS#1256]
I am very confused about the next function on Subjects.  I used NPM to install rxjs and I am using commonJS with Typescript (Alongside Angular 2).  I was looking at some sample code and found them using the next function on the subject object.  I have been looking all over for the documentation of the next function.  I have also looked through the rxjs source code to try to identify where it is coming from.  I have been unsuccessful.  Can somebody point me in the right direction?

--From the Subject.d.ts
```
import { Operator } from './Operator';
import { Observer } from './Observer';
import { Observable } from './Observable';
import { Subscriber } from './Subscriber';
import { Subscription } from './Subscription';
export declare class Subject<T> extends Observable<T> implements Observer<T>, Subscription<T> {
    _subscriptions: Subscription<T>[];
    _unsubscribe: () => void;
    static create<T>(source: Observable<T>, destination: Observer<T>): Subject<T>;
    protected destination: Observer<T>;
    observers: Observer<T>[];
    isUnsubscribed: boolean;
    dispatching: boolean;
    errorSignal: boolean;
    errorInstance: any;
    completeSignal: boolean;
    lift<T, R>(operator: Operator<T, R>): Observable<T>;
    _subscribe(subscriber: Subscriber<any>): Subscription<T>;
    add(subscription?: any): void;
    remove(subscription?: any): void;
    unsubscribe(): void;
    next(value: T): void;
    error(err?: any): void;
    complete(): void;
    _next(value: T): void;
    _error(err: any): void;
    _complete(): void;
}

```

**Comment by whitecolor** [comment]
You are asking in a wrong repo a I believe, this is rxjs4 (`rx` on npm) version rxjs 5 (`rxjs` on npm) resides https://github.com/ReactiveX/rxjs

**Comment by bretthodel** [comment]
@whitecolor - You are right...thank you.  I didn't realize the difference between the repos.   I now see in the migration documents from 4->5 where the next came from.
