### ISSUE TITLE
Deprecation notice?

### ISSUE THREAD

**Issue by Sequoia** [Reactive-Extensions/RxJS#1262]
If this is to be superseded by <https://github.com/ReactiveX/rxjs>, there should be a big warning at the top of the readme saying as much.

It's confusing to see "rxjs" used in a tutorial & not realize that *this* repository (linked from http://reactivex.io/ ) is not "the" rxjs.

**Comment by Thomas-P** [comment]
There are the 5.0 beta version of RxJS in another git repository.

Version 4.1: https://github.com/Reactive-Extensions/RxJS
install with npm: `npm install rx`
The actual definition file for this version is here: https://github.com/Reactive-Extensions/RxJS/blob/master/ts/rx.lite.es6.d.ts

Version 5.0beta: https://github.com/ReactiveX/rxjs
install with npm `npm install rxjs-es`
or the TypeScript version `npm install @reactivex/rxjs`
The definition files are also in the module.

Hope i could help.

**Comment by OliverJAsh** [comment]
I've noticed this confusing lots of people…
