### ISSUE TITLE
.map not working on Observable.fromEvent(..) in Angular2

### ISSUE THREAD

**Issue by squarewave24** [Reactive-Extensions/RxJS#1271]
I am following the [autocomplete example](https://github.com/Reactive-Extensions/RxJS/blob/master/examples/autocomplete/autocomplete.js) with RxJS and struggling a bit to get it working in Angular2 component. I suspect that the Observable i am using may be different from Observable in this example. 

Here is how I set it up: 

    @ViewChild('searchInput') input: ElementRef;
    ...
    var keyups = Observable.fromEvent(this.input.nativeElement, 'keyup')
    // this returns FromEventObservable instead of Observable which may be the reason? 

at this point, I can call .subscribe and see the events flow in: 

    keyups.subscribe( e => console.log(e));

however this does not show anything **** : 

      keyups.map( e => console.log('e ', e) );

my imports look like this: 

    import { Observable } from 'rxjs/Rx';

but i've also experimented with individual imports: 

     import 'rxjs/add/observable/fromEvent';
     import 'rxjs/add/operator/map';
     import 'rxjs/Rx';
      
my package.json references rx like this

    "rxjs": "5.0.0-beta.6",

I realize this is not an issue with your code but likely a version incompatibility. Any hint on how to troubleshoot this would be very appreciated!

**Comment by contrasam** [comment]
Hi @squarewave24, The version you are using is maintained separately in https://github.com/ReactiveX/rxjs, I think if you ask there you might get an answer.

**Comment by squarewave24** [comment]
hi actually i figured it out, i just needed to spend more time with RxJS. I tried to delete my issue but there didn't seem to be any way to do this

**Comment by jmalonzo** [comment]
Hi @squarewave24, I think you might be able to just close it.

**Comment by notflip** [comment]
What was the solution @squarewave24 ?

**Comment by squarewave24** [comment]
@notflip 

.map() does not get triggered if there are no subscribers. 

using .map() is fine as long as at some point you will subscribe. 

i found map useful especially in cases where i want to chain/combine multiple observables. 

Here is a full working example of a more complex situation where i join few observables, perform an action for each using .map() and finally perform some other action when they're all finished. 

         // set lookup fields
        var observables = [];
        fieldMetadata.forEach(field => {
            // lookup? 
            if (field.HasLookup)
                observables.push(
                    this.svc.getLookupData(field.FieldName).map(data => this.setLookupEditor(data, field.FieldName, 'ID', 'NAME', columnDefs, type))
                )
        })
        if (observables.length < 1) return;
        Observable.forkJoin(
            Observable.onErrorResumeNext(
                observables
            )
        ).subscribe(res => {
            this.notify.success('Lookup data downloaded');
            options.api.setColumnDefs(columnDefs);
            // this.autoSizeAll(type);
        }
            , err => console.error);
