### ISSUE TITLE
How to implement backwards countdown timer?

### ISSUE THREAD

**Issue by wizardnet972** [Reactive-Extensions/RxJS#1276]
Hi,

How to implement backwards countdown timer?

var x = Observable.of(someClass.startTime);  //someClass.startTime = 30 - the number is from api-server.
x....?

and the result should be 30, 29, 28......0 (done).

How to do it by rxjs way?

**Comment by raybooysen** [comment]
I think StackOverflow is a better place for this.  GitHub issues are for problems/issues with the library itself.
