### ISSUE TITLE
Is it possible to add Teardown logic to an already existing Observable?

### ISSUE THREAD

**Issue by nickkenens** [Reactive-Extensions/RxJS#1308]
For instance, I'm currently calling unsubscribe from an Observable that is returned from Angular 2's HTTP.

But I have some custom logic surrounding it.

Is it possible to add custom teardown logic to an already existing Observable, like the one returned from Angular 2's HTTP?

Something along the lines of `Observable.prototype.whenUnsubscribed(customTeardownLogic)` maybe?

**Comment by paulpdaniels** [comment]
Wrong repo.  Reopen at: https://github.com/ReactiveX/rxjs

**Comment by nickkenens** [comment]
Thanks for the heads up @paulpdaniels
