### ISSUE TITLE
BehaviorSubject hasObservers is not a function

### ISSUE THREAD

**Issue by pubkey** [Reactive-Extensions/RxJS#1364]
According to the [docs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/behaviorsubject.md) I can use hasObservers() on BehaviorSubject.

```js
var Rx = require('rxjs');
var s = new Rx.BehaviorSubject();
console.log('............');
console.log(s.hasObservers());
```

this will return the error:
```
 s.hasObservers is not a function
```

Version: 5.0.0-rc.3
ENV: nodejs v6.8.1

**Comment by smac89** [comment]
How did you solve this?

**Comment by pubkey** [comment]
@smac89 You can get all observers by calling `myObservable$.observers` and check with `myObservable$.observers.length>0` instead of hasObservers()
