### ISSUE TITLE
MapTo operator bug/weird behavior.

### ISSUE THREAD

**Issue by thibaultsavary** [Reactive-Extensions/RxJS#1365]
Bug/Weird behavior

`mapTo `operator has a very weird behavior if it's not a bug.

Here is the code.

The behavior I expect from this code is to modify the item on which I click, like it would with
` .map(x => new Some())`
However it seems that there's only one instance of the Some object instantiated using `mapTo` instead of `map`. This causes all item's state to be modified to false when clicking on one of them.

```
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-rxjs-debug',
  templateUrl: './rxjs-debug.component.html',
})
export class RxjsDebugComponent implements OnInit {
  public items;

  ngOnInit() {
    this.items = Observable
    .interval(2500)
    .mapTo(new Some())
    .scan((acc, curr) => [...acc, curr ], [])
    .defaultIfEmpty([])
  }

}

class Some {
  constructor(public state: boolean = true) { }
}
```

```
<section *ngFor="let item of items | async">
  <span (click)="item.state = false">{{item.state}}</span>
</section>
```

**Comment by unao** [comment]
It does not look like a bug to me; you create an object with `new Some()`, pass it to `.mapTo` and all values are mapped to it; if you want to create new object for each value just use `.map`.

**Comment by thibaultsavary** [comment]
Yeah, when reading the documentation, this behavior make total sense because it's specified that it's mapping to a constant.

But, still, not very intuitive I think, at least to me.
