### ISSUE TITLE
Observable.fromPromise().combineLatest() does not work

### ISSUE THREAD

**Issue by RyanMitchellWilson** [Reactive-Extensions/RxJS#1377]
I've just got a simple fetch function that takes a url and returns an Observable.fromPromise. I've got two streams that I am trying to combine and whenever I subscribe to them individually I get a response, but whenever I try to use combineLatest with another stream, I never get anything. Anyone else run into this same problem?

**Comment by paulpdaniels** [comment]
Do you have an example that replicates the issue?

**Comment by RyanMitchellWilson** [comment]
```
const doFetch = (url) => Observable.fromPromise(
  window.fetch(url).then((resp) => resp)
)

doFetch(someUrl).combineLatest(doFetch(someUrl), (msg1, msg2) => {
  console.log('Message 1 -> ', msg1);
  console.log('Message 2 -> ', msg2);
})
```

I never see the console logs. But if I subscribe to each different call alone I get a response and my console logs show.

**Comment by RyanMitchellWilson** [comment]
Found a quick work around for now: http://stackoverflow.com/questions/34190650/how-do-i-resolve-an-observable-inside-of-another-observable-rxjs

Example:
```
doFetch(someUrl).map((msg) => {
  return { msg1: msg }
}).flatMap((msg) => {
  return doFetch(otherUrl).map((res) => {
    msg.msg2 = res;
    return msg;
  })
}).subscribe((msg) => {
  console.log('Message 1 -> ', msg.msg1);
  console.log('Message 2 -> ', msg.msg2;
})
```

This gives you access to both of the messages from two different calls. Feels a little hacky to me but it gets the job done if you need similar functionality to combineLatest.

**Comment by RyanMitchellWilson** [comment]
So I figured out that I wasn't quite using combineLatests correctly. I was under the impression that you can use it the same as subscribe. But I found that you actually need to subscribe to a combineLatest to get the effect that I was expecting.

Like so:
```
doFetch(someUrl).combineLatest(doFetch(otherUrl), (msg1, msg2) => {
  return {msg1, msg2}
}).subscribe(({msg1, msg2}) => {
  console.log('Message 1 -> ', msg1);
  console.log('Message 2 -> ', msg2);
})
```
This prints out my console logs with the correct messages in them.
