### ISSUE TITLE
Scheduler's catch method example is wrong

### ISSUE THREAD

**Issue by wuxiandiejia** [Reactive-Extensions/RxJS#1404]
The example's link is
 https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/schedulers/scheduler.md
![image](https://cloud.githubusercontent.com/assets/7284362/21874846/92607722-d8b2-11e6-8d55-acb47551866c.png)

the result is:

![image](https://cloud.githubusercontent.com/assets/7284362/21874869/b92031a4-d8b2-11e6-88e9-a0159f0a0030.png)

In the example,the schedule method has one argument,is it right?

**Comment by RobertCawBrush** [comment]
Should be fine, the code isn't consuming an error parameter. It's just throwing it's own error.
