### ISSUE TITLE
RxJS shallows errors like Opera loves food

### ISSUE THREAD

**Issue by ev1stensberg** [Reactive-Extensions/RxJS#1414]
Hey! 

I'll try to describe the problem I have:

Over at [webpack-cli](https://github.com/webpack/webpack-cli/tree/feature/parser), we're running an inquirer prompt that is an observable. We're executing a function once the observer is done, named `parser`. If we throw an error inside the parser with our own [Error](https://github.com/webpack/webpack-cli/blob/feature/parser/lib/parser/index.js), Rx shallows the error and makes sure it doesn't get outputted. 

I've got two questions:

Is it possible to run a function outside the context of the observable once the observable is finished? In that case, could you redirect me to some place about this or explain it somehow?

</hr>

Is it possible to make the error show up? 

</hr>

![skjermbilde 2017-02-05 kl 21 04 18](https://cloud.githubusercontent.com/assets/16735925/22629451/b8c29ce6-ebe6-11e6-872d-cf5cf58bba45.png)

</hr>

Relative: https://github.com/webpack/webpack-cli/blob/feature/parser/lib/inquirer-prompt.js#L17

**Comment by ev1stensberg** [comment]
Relative: https://github.com/webpack/webpack-cli/blob/feature/parser/lib/inquirer-prompt.js#L17

**Comment by ev1stensberg** [comment]
Would be a good first contribution for me  FWIW :)

**Comment by paulpdaniels** [comment]
You shouldn't be throwing from *inside* a complete block. If you need error handling I would suggest moving the parser block into a map block further up the chain so that Rx can capture the exception.

**Comment by ev1stensberg** [comment]
@paulpdaniels Wanna come up with an example? 👍

**Comment by paulpdaniels** [comment]
Starting with the example in the code you have, after I dove in a bit on what `parser` was actually doing.

I think you should flatten it like so: 

```javascript

inquirer.promp(questions).ui.process
  .reduce(function (newOpts, ans) {
    return attachAnswers(newOpts, ans);
  }, Object.assign(config, require('./utils/initial-config')))
  .flatMap(newOpts => {
    checkEmptyAnswers(newOpts);
    return parser(null, newOpts); // I think you want the new version here
  })
  .subscribeOnError(err => process.exit(0));

```

Where `parser` now returns a stream instead of a sync value (I actually skipped to one of the branches that parser evaluates to, `validateOption`, but this should still give the idea):

```javascript

// Return a stream instead
const readFileObservable = Rx.Observable.bindNodeCallback(fs.readFileSync);

return Rx.Observable.pairs(opts)
  .map(([, opt]) => getPath(opt))
  .flatMap(part => readFileObservable(part))
  .do(null, err => {
    console.error('Found no file at:', part);
  });
```

**Comment by ev1stensberg** [comment]
Holy shit, thanks! I'm closing this now, +1 you're awesome 🎉
