### ISSUE TITLE
bufferCount seems to be storing second to last value incorrectly

### ISSUE THREAD

**Issue by rohitsodhia** [Reactive-Extensions/RxJS#1415]
While I admit this may be my lack of understanding of reactive, I'm getting strange behavior with bufferCount in my Angular 2 app. I created a service to get data from one component, and through a BehaviorSubject, send to a second component. The service is pretty straight forward:

```
export class EventFilterService {
	private filtersSubject: BehaviorSubject<Object>;
	
	constructor() {
		this.filtersSubject = new BehaviorSubject<Object>({
			search: '',
			types: [],
			dates: []
		});
	}

	setFilters(filters: {}) {
		console.log(filters);
		this.filtersSubject.next(filters);
	}

	getFilters() {
		return this.filtersSubject.asObservable();
	}
}
```

I then read the data as such:
```
	ngOnInit() {
		this.eventFilterService.getFilters().bufferCount(2, 1).filter((val:[{}]) => {
			console.log(val);
			return true; 
		}).subscribe((data) => console.log(data));
		this.eventFilterService.getFilters().debounceTime(2500).subscribe((filters) => {
			console.log(filters);
			this.filters = filters;
			this.eventService.getEvents(this.filters).subscribe((data: Event[]) => { this.processEvents(data); });
		});
	}
```

However, after the first value, when buffer hits, the two values emitted by buffer are the same, even though through tracing, I can see the value being submitted is different. In fact, when I increase the buffer to (3,1), I see that the two most recent values are the same, and the third is as expected. It seems like the value before the current is being overwritten the by current.

**Comment by rohitsodhia** [comment]
I created a plunker to show the behavior (results come up in the console): http://plnkr.co/edit/UFRNfgaPuNKfozDzX5iI

**Comment by rohitsodhia** [comment]
According to someone on gitter, this isn't a bug but me doing things wrong. I don't understand what I'm doing wrong or why, unfortunately, but sorry for putting this up.

**Comment by ndcunningham** [comment]
someone has a name! Solution for anyone else that might have this issue

http://plnkr.co/edit/BKptl5RjVYosoy5L7U5X?p=info

**Comment by rohitsodhia** [comment]
I apologize. I didn't meant to not give you credit; I'm frustrated I don't understand what's going on, and that's leaving me with poor judgement. Sincerest apologies.
