### ISSUE TITLE
feature: if no error function passed to subscribe, need to at least console.error

### ISSUE THREAD

**Issue by born2net** [Reactive-Extensions/RxJS#1417]
@feature: if no error function passed to subscribe, need to at least console.error!

I am working with rxjs5 and did not pass an error function  handler for my subscription and sure enough my errors got trapped and never displayed to the console.
I believe that be default, if a user does not provide an error handler, the least rxjs should do is catch the error and ```console.error()```  so new users (and old ones who forget) will be notified of swallowed bugs.

this relates also to Ben's blog:
https://medium.com/@benlesh/on-the-subject-of-subjects-in-rxjs-2b08b7198b93#.itwajvi1m
and so I agree that we should not trap the errors and be as verbose as possible when any exception is raised,

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by paulpdaniels** [comment]
Wrong repo.  You want https://github.com/ReactiveX/rxjs

**Comment by born2net** [comment]
sorry tx!
