### ISSUE TITLE
How do I use subscribe from two observable?

### ISSUE THREAD

**Issue by acivang** [Reactive-Extensions/RxJS#1425]
hello,everyone!

i need return a observable from subscribe at first, and i had do it like:

[http://stackoverflow.com/questions/39935721/how-to-return-observable-from-subscribe](url)

but i found it was different from upper after, because my code like:

```javascript

function getTokenThenGetData(): Observable<string> {
  return http.post(args)
    .map(res => {
      let token: string = res.token;
      return getData(token);
    })
}

function getData(token: string): Observable<any>{
  return http.post(url, token)
    .map(res => {
      retrun res.data;
    })
    .first();
}

function request(): Observable<any>{
  if(token){
    return getData(token);
  }else{
    return getTokenThenGetData();
  }
}

```

```javascript

service.request()
    .subscribe(data => {
      //DO SOMETHING
    })

```

when token existed, request.subscribe's data is server response data, if not it is object of Observable.i want to it is server response data when token not existed.How do I would do?

thank u very much!

ps:

i don't like use like:

```javascript

function t(){
  service.request()
    .subscribt(data => {
      if(typeof data === Observable){
        data.subscribe(data => {
          //DO SOMETHING
        })
      }else{
          //DO SOMETHING
      }
    })
}

```

it's not graceful

**Comment by feliperohdee** [comment]
hey there

I haven't tested, but the pseudo logic is:

        function getToken(): Observable <string> {
            return http.post(args)
                .map(res => res.token);
        }

        function getData(url: string, token: string = null): Observable <any> {    
            let operation: any = http.post(url, token);

            if(!token){
                operation = getToken()
                    .flatMap(token => http.post(url, token));
            }

            return operation
                .map(res => res.data)
                .first();
        }

**Comment by acivang** [comment]
@feliperohdee thank u very much!! i solved my problem and understood the difference between map and flatMap(or mergeMap).
