### ISSUE TITLE
why do you need filter/map etc..?

### ISSUE THREAD

**Issue by patrikx3** [Reactive-Extensions/RxJS#1431]
what is the point in rxjs if it already native in javascript like filter/map all of that?
What is the difference?

**Comment by paulpdaniels** [comment]
The native `filter` and `map` operators are for `Arrays`. RxJS is for `Observables`. There are plenty of great resources out there for understanding the motivation, you can find them if you scroll down on the main page of this repo [here](https://github.com/Reactive-Extensions/RxJS#resources)

**Comment by patrikx3** [comment]
thanks, just understanding. checking out your info. thanks so much.
