### ISSUE TITLE
suggestion: consider improving the type signature for Observable.catch

### ISSUE THREAD

**Issue by aluanhaddad** [Reactive-Extensions/RxJS#1438]
For better or worse, the catch and rethrow idiom seems to have overtaken RxJS, sometimes even when they only rethrow (not even logging the error) developers insist on explicitly catching and rethrowing all exceptions. The Angular docs are the reason for this, but not the reason for this suggestion. Catching and only rethrowing doesn't make much sense to me but I am very new to RxJS.

For reference here is what it looks like
```ts
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';

export interface Something {
  name: string;
}

export class SomeService {
  getItems() {
    return this.http('api/something')
      .map(x => (x.json() as Something).name) // Observable<string>
      .catch((err, caught) => Observable.throw(err.json())); // Observable<any>
  }
}
```
The problem with this pattern, and the pattern really is pervasive in the Angular at least, is that chaining `catch` removes all type information unless the user actually uses catch to recover by supplying a new Observable. If they return the result of an `Observable.throw` call all further operations receive `Observable<any>`.

To fix the type issue, while allowing Angular 2 users to catch and rethrow every single exception to their heart's content, I suggest that the signature of catch be changed from
```ts
export declare function _catch<T, R>(
  this: Observable<T>, selector: (err: any, caught: Observable<T>) => ObservableInput<R>
): Observable<R>;
```
to 
```ts
export declare function _catch<T, R>(
  this: Observable<T>, selector: (err: any, caught: Observable<T>) => ObservableInput<R>
): Observable<R>;
export declare function _catch<T>(
  this: Observable<T>, selector: (err: any, caught: Observable<T>) => ErrorObservable<any>
): Observable<T>;
```
This worked well when I tested it. I suppose the question is whether the idiom of catching and rethrowing is meant to be common for observables.

I would be happy to submit a PR for this if you are interested.

**Comment by paulpdaniels** [comment]
Pretty sure you want: https://github.com/ReactiveX/rxjs

**Comment by aluanhaddad** [comment]
Wow, I could have sworn I was there. Many  apologies.
