### ISSUE TITLE
combineLatest resultSelector runs once for every subscription

### ISSUE THREAD

**Issue by zaneadix** [Reactive-Extensions/RxJS#1447]
http://jsbin.com/yijurucona/5/edit?js,console,output

From the linked Observable.combineLatest example you can see that .take(4) causes the observable to emit 4 times but because their are 2 subscriptions the resultSelector function is run 8 times (once per update per subscription)

Is there a reason the resultSelector wouldn't just be run a single time and then have the result of that single execution sent out to subscribers? I'm sure I'm missing something fundamental here but currently I'm using combineLatest with the async pipe in an Angular 2 app and it ends up creating a significant bottleneck when there are a lot of subscriptions within a large template.

Is there a way to get around this behavior?

**Comment by paulpdaniels** [comment]
@zaneadix It is a hot vs cold observable issue. Have a look at [this article](https://medium.com/@benlesh/hot-vs-cold-observables-f8094ed53339), it gives a pretty good run down of the behavior you are experiencing.

*&TLDR;* You need to use `share()` or `publish()` to get the desired behavior

**Comment by zaneadix** [comment]
@paulpdaniels Thanks for making my Monday morning not suck.
![giphy](https://cloud.githubusercontent.com/assets/7071557/24864818/6476fff0-1dd3-11e7-8577-771998c82fdd.gif)
