### ISSUE TITLE
subscription.add is not a function

### ISSUE THREAD

**Issue by mrdulin** [Reactive-Extensions/RxJS#1464]
`"rx": "^4.1.0",`

I follow the official doc, I want to `unsubscribe` two `subscription`, but it give me an error.

```bash
subscription.add(childSubscription);
             ^

TypeError: subscription.add is not a function
```

Here is my code snippet: 

```js
const Rx = require('rx');

const obs1 = Rx.Observable.interval(1000);
const obs2 = Rx.Observable.interval(1000);

const subscription = obs1.subscribe(x => console.log(x));
const childSubscription = obs2.subscribe(x => console.log(x));

subscription.add(childSubscription);

setTimeout(() => {
  subscription.dispose();
}, 2000);
```

I am so confused about the official doc.

**Comment by paulpdaniels** [comment]
See my answer to your other question. You are referencing docs for v5 and above. For v4 you need to use a `CompositeDisposable` to group Disposables together.

**Comment by mrdulin** [comment]
@paulpdaniels Thanks. I am clear!
