### ISSUE TITLE
Is skipWhile working correctly?

### ISSUE THREAD

**Issue by monicao** [Reactive-Extensions/RxJS#1497]
Hi there!

I am probably misunderstanding how `skipWhile` works, but I am hoping you can help me understand.

Here's some code that illustrates my question:

```js
const obs = Rx.Observable.of(1, 2, 3, 4)

obs
  .skipWhile((x) => x < 3)
  .subscribe((x) => console.log(x))

// Console logs: 3 4

console.log("----")

obs
  .skipWhile((x) => (x % 2) === 0)
  .subscribe((x) => console.log(x))

// Console logs: 1 2 3 4
// Expected: 2 4
```

JSBin here: http://jsbin.com/jefurosuwo/4/edit?js,console
Using rxjs 5.4.2.

Thanks! <3

**Comment by paulpdaniels** [comment]
RxJS 5 is maintained at https://github.com/ReactiveX/rxjs/ 

But yes that appears to be correct behavior. `skipWhile` should skip events until the predicate evaluates to false and then it should emit the value that triggered the switch as well as all subsequent events.

**Comment by monicao** [comment]
Thanks @paulpdaniels. Closing this.
