### ISSUE TITLE
add async iterator 

### ISSUE THREAD

**Issue by zh99998** [Reactive-Extensions/RxJS#1504]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html
the new Async Iteration syntax is great
how about make observables async iteratable?
`for await (const item of an_observable) { ... }`

here is a implement
https://gist.github.com/zenparsing/4e65592f184dafc82125

**Comment by paulpdaniels** [comment]
I think you should have a look at https://github.com/ReactiveX/IxJS. Async iterators might be a better fit there. Additionally this repo is in maintenance mode and will not be accepting new features.
