### ISSUE TITLE
documentation missing for Observable#subscribe()

### ISSUE THREAD

**Issue by activedecay** [Reactive-Extensions/RxJS#1543]
Looking on this page, [for the Observable object](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html), there is no documentation for the `subscribe()` method

**Comment by Dorus** [comment]
Since that is the RxJs 5 doc site, you might want to go to the RxJs 5 repository: https://github.com/ReactiveX/rxjs

**Comment by activedecay** [comment]
Oops! Thank you
