### ISSUE TITLE
question about buffer operators

### ISSUE THREAD

**Issue by snackycracky** [Reactive-Extensions/RxJS#1547]
Hello, why do operators such as bufferWhen that call a users function every time they open a new buffer/window don't let you react to values going through ?
I would like to flush the buffer when some condition on the buffered accumulation is met.
Is there a reason for this design ? I am sure it was discussed before.

**Comment by whiteinge** [comment]
This repo is in maintenance-only mode. The bufferWhen operator is in the newer RxJS version so you'll want to ask this question over in that repo instead: https://github.com/ReactiveX/RxJS

**Comment by snackycracky** [comment]
thanks I already did
