### ISSUE TITLE
fromPromise as array

### ISSUE THREAD

**Issue by cboden** [Reactive-Extensions/RxJS#179]
How can I create an Observable collection from a promise that resolves as an array?

``` javascript
var defer = new Deferred;

var observable = Rx.Observable.fromPromise(defer.promise);
observable.subscribe(function(v) {
    console.log('onNext: ', v);
});

defer.resolve([3, 4, 5]);

// Want/expect
// => onNext: 3
// => onNext: 4
// => onNext: 5

// Actual result:
// => onNext: [3, 4, 5]
```

**Comment by arnaudbenard** [comment]
@cwharris There's a type in the code, it should be `flatMap`. Just for the next people copy pasting like me ;)

**Comment by niksubramanian** [comment]
@cwharris thanks for the simple explanation - my rxjs'd promises suddenly all make sense ;)

**Comment by Peleke** [comment]
@cwharris Just echoing everyone's thanks; this helped a lot.

This is an old discussion, but seeing as Google landed me here anyway, I should like to point out that [Rx.Observable.fromArray](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromarray.md) is deprecated; use [Rx.Observable.from](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/from.md) instead.

Took me more than a few minutes to figure that out, so I figure it worth mentioning.
