### ISSUE TITLE
A RxBook with a GitBook

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#184]
Hello @mattpodwysocki,

I just started working on a new book http://xgrommx.github.io/rx-book/ which based on Rx documentation. Also in future I would like add an interactive editor and live examples.

What do you think about it?

**Comment by mattpodwysocki** [comment]
Closing this issue as the book has been released and updated

**Comment by hansgru** [comment]
The URLs are not working in this book either :).

**Comment by hansgru** [comment]
The source code snippets are centered - and thus very very hard to read.

**Comment by mattpodwysocki** [comment]
@hansgru agreed, but those issues  belong in the repository for the [RxBook](https://github.com/xgrommx/rx-book/).
