### ISSUE TITLE
New observable operator proposal: sliding window over time

### ISSUE THREAD

**Issue by danbim** [Reactive-Extensions/RxJS#246]
For my app I've just created an operator on observables that produces a sliding window behavior for observables and I thought it might be interesting to add this to RxJs:

```
var Rx = require('rx');

var timeoutScheduler = Rx.Scheduler.timeout;
var AnonymousObservable = Rx.AnonymousObservable;
var CompositeDisposable = Rx.CompositeDisposable;

Rx.Observable.prototype.slidingWindowWithTime = function(windowSizeMs, scheduler) {

    var source = this;
    Rx.helpers.isScheduler(scheduler) || (scheduler = timeoutScheduler);

    return new AnonymousObservable(function(observer) {

        var group = new CompositeDisposable();
        var done = false;
        var buffer = [];

        group.add(source.subscribe(
            function (value) {
                buffer = buffer.slice().concat(value);
                observer.onNext(buffer);
                var schedule = scheduler.scheduleWithRelative(windowSizeMs, function() {
                    if (buffer.length > 0) {
                        buffer = buffer.slice(1);
                        observer.onNext(buffer);
                        group.remove(schedule);
                        schedule = null;
                    }
                    done && observer.onCompleted();
                });

                group.add(schedule);
            },
            observer.onError.bind(observer),
            function () {
                done = true;
                group.length === 1 && observer.onCompleted();
            }
        ));

        return group;
    });
}
```

Every new value in the source observable not older than `windowSizeMs` is added to a buffer. If a value is older than `windowSizeMs` it is removed from the buffer. On every change to the buffer subscribers to the observable are notified by calling `onNext(buffer)` and thereby the sequence observed by the subscriber always contains all last values produced during the last `windowSizeMs` milliseconds.

(The code is "inspired" by the solution posted in #175 and might not be a 100% correct by now. Thought it might be worthwhile to discuss this here first before putting more work into it...)

You can e.g., test it by running

```
Rx.Observable.interval(50).slidingWindowWithTime(200).take(20).subscribe(console.log);
```

This functionality can e.g., be used to produce averages over time:

```
Rx.Observable.interval(50).slidingWindowWithTime(200).take(20).subscribe(function(window) {
    Rx.Observable.fromArray(window).average().subscribe(console.log);
});
```

**Comment by bkon** [comment]
@danbim https://github.com/bkon/rx-op-sliding-window 
I honestly admit I was inspired by your code while building something which works with RxJS 5.

**Comment by danbim** [comment]
Thx @bkon, good to hear :)
