### ISSUE TITLE
Compare core.async to RxJS

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/RxJS#276]
How would you solve [this issue](http://www.jayway.com/2014/09/16/comparing-core-async-and-rx-by-example/) with RxJS versus core.async?

My solution would be:

``` js
var magicSequence = 'ABBABA';

var keyups = Rx.Observable.fromEvent(document, 'keyup')
  .map(function (x) { return x.keyCode; })
  .bufferWithCount(6, 6)
  .take(1)
  .timeout(5000, Rx.Observable.just([]))
  .filter(function (xs) {
    return xs.map(function (x) { return String.fromCharCode(x); }).join('') === magicSequence;
  })
  .repeat()
  .subscribe(function (x) {
    console.log('Magic Keys!');
  });
```

Any thoughts @staltz, @headinthebox, @jhusain, @benjchristensen?

**Comment by deanius** [comment]
I have learned so much from following this thread :) Very similar to a fiddle I'd made that simulated a device which 5 clicks turned on if within a certain amount of time. I too had to go to timestamps - thanks @mattpodwysocki @swannodette @acthp @staltz !

**Comment by rmcv** [comment]
Not a RxJS version, just revising the original Clojure version to show how it can be done differently with [transducer](https://clojure.org/reference/transducers)* - which works seamlessly with [core.async](https://github.com/clojure/core.async).

```clojure
(def both-buttons (chan 1 (comp (map #(vector (System/currentTimeMillis) %))
                                (partition-all (count magic-seq) 1)
                                (filter #(= magic-seq (map last %)))
                                (filter #(< (- (System/currentTimeMillis) (ffirst %)) 5000)))))
```
The logic is as follows:

- First line: timestamp each keystroke
- Second line: partition the sequence like a sliding window
- Third line: pass on if input sequence is correct
- Fourth line: pass on if the first keystroke is within 5 seconds

Here is a sample usage to consume this channel:

```clojure
(def magic-seq [:A :B :B :A :B :A])

...

(go-loop []
  (if-let [bingo (<! both-buttons)]
    (do (println "Congratulations!")
        (recur))))
```

*One caveat is I have to implement my own partition-all transducer as Clojure version doesn't come with the sliding window (offset) support.
