### ISSUE TITLE
Proposal for context parameter in `subscribe`

### ISSUE THREAD

**Issue by sergi** [Reactive-Extensions/RxJS#287]
Since when using `Rx.Observable.subscribe` inside prototypes it is relatively common to refer to members of the prototype, would it be reasonable to add an extra parameter to `subscribe` to specify the context like `array.forEach` or `array.map` do, or is this too much of an API break?

**Comment by pekeler** [comment]
thisArg doesn't work for me for `subscribe(onNext, onError, onCompleted, thisArg);`

```
var Rx = require('rx');
var that = this;

// doesn't work
Rx.Observable.timer(10).subscribe(
  function(x) {console.log(this === that);},
  function(err) {},
  function() {},
  this
);

// works
Rx.Observable.timer(10).subscribe(
  function(x) {console.log(this === that);}.bind(this),
  function(err) {},
  function() {}
);

// works
Rx.Observable.timer(10).subscribeOnCompleted(
  function() {console.log(this === that);},
  this
);
```

This is using 2.3.24. Am I missing something?
