### ISSUE TITLE
Errors from Node streams

### ISSUE THREAD

**Issue by OliverJAsh** [Reactive-Extensions/RxJS#368]
I'm creating an observable from a Node readable stream:

``` js
/* jshint node: true */

var Rx = require('rx');
var stream = require('stream');

var readableStream = new stream.Readable();
readableStream.setEncoding('utf8');

var observable = Rx.Node.fromReadableStream(readableStream);

readableStream.push('foo');
readableStream.push(null);

observable.subscribe(
    console.log.bind(console, 'observable onNext'),
    console.log.bind(console, 'observable onError'),
    console.log.bind(console, 'observable onCompleted')
);

// => observable onNext foo
// => observable onCompleted
```

This works fine. However, when the readable stream emits an error:

``` js
/* jshint node: true */

var Rx = require('rx');
var stream = require('stream');

var readableStream = new stream.Readable();
readableStream.setEncoding('utf8');

var observable = Rx.Node.fromReadableStream(readableStream);

readableStream.emit('error', new Error('foo'));

observable.subscribe(
    console.log.bind(console, 'observable onNext'),
    console.log.bind(console, 'observable onError'),
    console.log.bind(console, 'observable onCompleted')
);

// => events.js:72
// =>         throw er; // Unhandled 'error' event
// =>               ^
// => Error: foo
// =>     at Object.<anonymous> (/Users/Oliver/Development/tmp/rxjs-test/stream.js:11:30)
// =>     at Module._compile (module.js:456:26)
// =>     at Object.Module._extensions..js (module.js:474:10)
// =>     at Module.load (module.js:356:32)
// =>     at Function.Module._load (module.js:312:12)
// =>     at Function.Module.runMain (module.js:497:10)
// =>     at startup (node.js:119:16)
// =>     at node.js:906:3
```

This uncaught exception occurs because the stream emits the event before the subscription has been created, which means that there is no event handler for `error` in time for the error being emitted. This contrasts the behaviour when a stream emits data, as the `readable` event always occurs in the next tick.

The obvious solution to my example above would be to emit the error after the subscription. However, this is not an ideal option: I want a function that creates a stream and returns an observable.

I think this overlaps with a similar issue I'm having but with `EventEmitter`s: https://github.com/Reactive-Extensions/RxJS/issues/366

**Comment by danielecr** [comment]
Closed? well, but suppose I have some code inside a switchMap method applyied to a stream, I want any error to be catched from there, no? but errors rised by an event emitter are not catched by Observable.
It can make sense, because error should be async, so I have to take care about every event emitter that throw an error if not subscribed. Suppose that I am copying a file with stream reader and writer:

```
     let obs$ = Observable.of(doc)
        .switchMap( (doc) => {
        let localpathname = doc.localpath

        console.log('copying',localpathname, 't', doc.targetFile)

        let wStream = fs.createWriteStream(doc.targetFile);
        let rs = fs.createReadStream(localpathname)
        let error$ = Observable.fromEvent(rs,'error').switchMap(Observable.throw);
        let werror$ = Observable.fromEvent(wStream,'error').switchMap(Observable.throw);
        rs.pipe(wStream);

        let close$ = Observable.fromEvent(wStream,'close');
        return Observable.race(error$, werror$, close$);
    }).subscribe(succesCopy, failCopy, complete)
```
My question is

Q: here I am using race() method in the hope it will be async, I do not expect any errors after 'close' on writeStream, so: this code is _really_ async as wanted?
