### ISSUE TITLE
What is the reactive/functional way to iterate over a dictionary?

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/RxJS#433]
I could not find an information on how to iterate over a dictionary. 

Normally I would iterate as so:

``` js
for (var key in dictionary) {
    console.log("key: " + key ", value: " + dictionary[key]);
}
```

Currently I have a function

``` js
function fromDictionary(dictionary) {
    return rx.Observable.fromArray(Object.keys(dictionary))
      .map(function(key){           
        return {key:key, value:dictionary[key]};        
      });
}
```

then used as so:

``` js
fromDictionary(dictionary)
    .subscribe(function(keyValue){
        console.log("key: " + key + ", value: " + value);
    });
```

Is there a better way to iterate over a dictionary?

**Comment by rightfold** [comment]
Oh God no. Don't use objects as dictionaries, use proper data structures types like those provided by immutable-js and mori. They are much easier to use and don't have shitty quirks like `toString` always being there.
