### ISSUE TITLE
Last release seem to be broken

### ISSUE THREAD

**Issue by SBoudrias** [Reactive-Extensions/RxJS#434]
Hey, got a couple bug reports on Yeoman tonight about rxjs throwing: https://github.com/yeoman/yo/issues/247

Must be related to the latest release.

**Comment by qngODC** [comment]
lc loopback:relation
? Select the model to create the relationship from: serviceArea
? Relation type: belongs to
? Choose a model to create a relationship with: zone
? Enter the property name for the relation: (zone) 


/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:77
    throw e;
          ^
true

**Comment by antgonzales** [comment]
I'm getting this issue as well. Tried running with -v `0.10.36` and `5.4.0`.

```
? Bot adapter (campfire) slack                            got back false



/opt/nodes/0.10.36/lib/node_modules/yo/node_modules/rx/dist/rx.js:77
    throw e;
          ^
true
```

**Comment by teyushen** [comment]
try 
yo hubot --owner="OWNER <owner@example.com>" --name="TestBot" --description="Test Bot" --adapter=slack
or
yo hubot --defaults

**Comment by Eater4** [comment]
Still Doesn't Work. Same issue `
/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:77
    throw e;
    ^
true`

**Comment by SETTER2013** [comment]
C:\Users\****\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:77
    throw e;
    ^
 true

How to fix the error?

**Comment by antgonzales** [comment]
@Eater4 @SETTER2013 This worked for me:

```
yo hubot --owner="OWNER owner@example.com" --name="TestBot" --description="Test Bot" --adapter=slack
```

**Comment by Eater4** [comment]
Got past that error, encountered this error 'npm ERR! node v4.2.6
npm ERR! npm v3.5.2
npm ERR! path npm-debug.log.3087090565
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.3087090565'
npm ERR! at Error (native)
npm ERR! { [Error: EACCES: permission denied, open
'npm-debug.log.3087090565']
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'open',
npm ERR! path: 'npm-debug.log.3087090565' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR! /home/nate/HuBot/npm-debug.log'

**Comment by SETTER2013** [comment]
yo hubot --owner="OWNER owner@example.com" --name="TestBot" --description="Test Bot" --adapter=slack


What do I do with this?

**Comment by SETTER2013** [comment]
D:\host\home\loopback-start>slc loopback:relation
(node:6432) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
? Select the model to create the relationship from: country
? Relation type: has many
? Choose a model to create a relationship with: city
? Enter the property name for the relation: (cities)


C:\Users\apetrov\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:77
    throw e;
    ^
 true
