### ISSUE TITLE
commonjs 

### ISSUE THREAD

**Issue by kof** [Reactive-Extensions/RxJS#462]
Why don't you organize the code in cjs like [react](https://github.com/facebook/react) does it.

The big advantage is one can pick parts he needs and is not forced to include complete builds.

**Comment by trxcllnt** [comment]
@mattpodwysocki started a project for this a while back, I'm any contributions would be appreciated! https://github.com/Reactive-Extensions/RxJS-Modules

**Comment by mattpodwysocki** [comment]
Closing as per this will be done in the new ReactiveX/RxJS and we have some samples in the modular code as well
