### ISSUE TITLE
An alternative for Bacon.update or Bacon.when

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#463]
Hello @mattpodwysocki,

What is alternative in Rx for Bacon.update or Bacon.when? I guess that it's very helpful operator. Small example for a simple counter http://jsbin.com/jenanuceme/1/edit?html,js,output

**Comment by xgrommx** [comment]
Could someone help me?

**Comment by mattpodwysocki** [comment]
@xgrommx we already have an equivalent to `Bacon.when` with [`Rx.Observable.when`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/when.md)

Such code could be written as such without using jQuery:
```js
function $$(elementString) {
  return document.querySelector(elementString);
}

function click(element) {
  return Rx.Observable.fromEvent(element, 'click');
}

function onLoad () {

  var $display = $$('#display');

  function getValue() {
    return +$$('#display').textContent;
  }

  var $plusClick = click($$('#plus')).map(getValue),
      $minusClick = click($$('#minus')).map(getValue),
      $resetClick = click($$('#reset'));

  var $updates = Rx.Observable.when(
    $plusClick.thenDo(function (x) { return x + 1; }),
    $minusClick.thenDo(function (x) { return x - 1; }),
    $resetClick.thenDo(function () { return 0; })
  ).startWith(0);

  $updates.subscribe(function (x) {
    $display.textContent = x;
  });
}
window.onload = onLoad;
```

**Comment by xgrommx** [comment]
As I understood, if I will use ```startWith``` I will have ```Bacon.update```. Also I have one small question, if I want use composition of two or many observables in condition like in ```Bacon.update``` https://github.com/baconjs/bacon.js/#join-patterns-and-baconbus how can I solve it? For example this http://en.wikipedia.org/wiki/Dining_philosophers_problem

**Comment by xgrommx** [comment]
Sorry, I found that Rx already have an operator  ```and```. I think this operator is just right.

**Comment by xgrommx** [comment]
@mattpodwysocki I think this good example for demonstration how user could use a ```when``` operator:

```js
var chopsticks = [new Rx.Subject(), new Rx.Subject(), new Rx.Subject()];

var hungry = [new Rx.Subject(), new Rx.Subject(), new Rx.Subject()];

var eat = i => {
  return () => {
    setTimeout(() => {
      console.log('Done');
      chopsticks[i].onNext({});
      chopsticks[(i+1) % 3].onNext({});
    }, 1000);
    return 'philosopher ' + i + ' eating';
  };
};

var dining = Rx.Observable.when(
  hungry[0].and(chopsticks[0]).and(chopsticks[1]).thenDo(eat(0)),
  hungry[1].and(chopsticks[1]).and(chopsticks[2]).thenDo(eat(1)),
  hungry[2].and(chopsticks[2]).and(chopsticks[0]).thenDo(eat(2))
);

dining.subscribe(console.log.bind(console));

chopsticks[0].onNext({}); chopsticks[1].onNext({}); chopsticks[2].onNext({});

for (var i = 0; i < 3; i++) {
  hungry[0].onNext({}); hungry[1].onNext({}); hungry[2].onNext({});
}
```

**Comment by mattpodwysocki** [comment]
@xgrommx that's great!  If you'd like to turn it into an official example with a web page, we'd be more than happy to accept it!

**Comment by xgrommx** [comment]
@mattpodwysocki Oh sure I can added it to the official documentation and to my rx book.

**Comment by gyzerok** [comment]
@mattpodwysocki thank you for once answering this question, but let me ask you one more to make this topic complete.

How do i get prev state of .when stream inside its functions? In other words how to transpile following example to Rx?
```javascript
var foo = Bacon.update([],
        [bar], function (prevFoo, bar) {
               return prevFoo.concat(bar);
        }
);
```

**Comment by urmastalimaa** [comment]
I'm not very familiar with the `Bacon` example, but your best bets are 
```js
bufferWithCount(2)
``` 
or possibly 
```
reduce
```

**Comment by xgrommx** [comment]
@gyzerok If you look inside ```update``` method from Bacon you can found ```scan```. I just try reproduce this operator in Rx and I use it so:

```js
let PersonStore = Rx.Observable.when(
    Actions.changeFirstName.debounce(2000).thenDo(firstName => person => person.set('firstName', firstName)),
    Actions.changeLastName.thenDo(lastName => person => person.set('lastName', lastName)),
    Actions.changeCountry.thenDo(country => person => person.setIn(['country', 'name'], country)),
    Actions.addFriend.thenDo(friend => person => person.set('friends', person.get('friends').push(friend))),
    Actions.save.debounce(2000).thenDo(_ => person => {
        console.log(person.toJS());
        return person;
    })
).scan(I.fromJS(defaultPerson), (person, action) => action(person)).publishValue(I.fromJS(defaultPerson)).refCount();
```

We can pass callback function to ```scan``` method. ```publishValue(I.fromJS(defaultPerson)).refCount()``` is alternative for ```Bacon.toProperty(I.fromJS(defaultPerson))```

**Comment by gyzerok** [comment]
@xgrommx Thank you for your answer! May I ask you to convert my particular example from Bacon to Rx? So I can get it right.

**Comment by xgrommx** [comment]
@gyzerok Welcome! As you can see ```person`` is previous value, ```action(person)``` is new value. Maybe in the future I could find more better example but now I use it. If you have some questions I'll try answer =)

**Comment by gyzerok** [comment]
@xgrommx I cannot find any information about ```thenDo``` method in the docs. Is it deprecated?

**Comment by gyzerok** [comment]
@xgrommx I guess I get general solution for this. Mb it can be better?
```javascript
function update(initial, ...patterns): Observable {
  const streams = patterns.filter((_, i) => i % 2 === 0);
  const callbacks = patterns.filter((_, i) => i % 2 !== 0);
  const pairs = streams.map((_, i) =>
    [streams[i], callbacks[i]]
  );
  return Rx.Observable.when.apply(this, pairs.map(p =>
    p[0].thenDo(data => prev => p[1](prev, data))
  )).scan(initial, (prev, f) => f(prev));
}
```

**Comment by xgrommx** [comment]
@gyzerok You can look on this http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/thendo.html

**Comment by xgrommx** [comment]
@gyzerok Look on this https://github.com/xgrommx/react-rx-flux/blob/master/src/store.js#L31
