### ISSUE TITLE
support `restart` in observable prototype

### ISSUE THREAD

**Issue by huang47** [Reactive-Extensions/RxJS#473]
The use case is restart the subscription when o2 emits an value

Currently we do following instead

```
// o1, o2 are observable instances
o2.
    startWith(true).
    flatMapLatest(function () { return o1; }).
    forEach(onNext, onError, onCompleted);
```

And it could be better to support `restart` and make it public.

```
o1.restart(o2).forEach(onNext, onError, onCompleted);
```

If we augment Rx.Observabe.prototype which doesn't get picked up by ConnectableObservable instances

```
var co = o.publishValue();
co.connect();

console.log(typeof co.restart) // undefined
```

**Comment by huang47** [comment]
It should be available for both.
I think that's because pipe is added inside of rxjs source file, not a new one.

If you create a new file named `rx.augment.js`

```
// inside of rx.augment.js
var Rx = require('./rxjs/');
if ( ! Rx.Observable.prototype.pipe) {
    Rx.Observable.prototype.pipe = function pipe() {
    };
}

module.exports = Rx;
```

```
// in node REPL
> var Rx = require('./rx.augment');
var co = Rx.Observable.of(1, 2, 3, 4).publish();
typeof co.pipe1
```

**Comment by huang47** [comment]
Oh yes, you are correct, I didn't require in the right order

**Comment by mattpodwysocki** [comment]
@huang47 I'm not sure there is a need for this in core.  @jhusain @headinthebox @benjchristensen, thoughts here?

**Comment by urmastalimaa** [comment]
I have had a similar use case: a countdown which you can restart.
However I'd argue against including it in the core because
* it seems to be mostly useful when dealing with cold observables which usually require fine tuned subscription control
* the solution with `flatMapLatest` is quite simple

**Comment by mattpodwysocki** [comment]
@huang47 I'm going to side with @urmastalimaa in this case as it is pretty easy and you can easily extend the `Observable` prototype yourself in this case.
