### ISSUE TITLE
WhyRX vs Highland bullet point list is all misleading, empty FUD

### ISSUE THREAD

**Issue by ericelliott** [Reactive-Extensions/RxJS#479]
RE: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/mapping/highland/whyrx.md

First, let me say that I really love the work you guys are doing, and that I think Rx is awesome, but I have some mean things to say about your docs. I wish I didn't, but I do. You guys are misleading people, egregiously, and it *makes RxJS look bad and desperate,* and nobody wants that... even Highland fans don't want that. We all want reactive programming to do well so that we all benefit from the larger, more vibrant community. So let's not take cheap pot shots at each other, please. Here comes the ugly:

This is really the worst [bullet point engineering](http://en.wikipedia.org/wiki/Bullet-point_engineering) list I have ever seen in more than 15 years in the software business. That bullet point list couldn't be more misleading if it was claiming it would turn you into superman and let you travel through time by flying around the world.

Please dial back the rhetoric, get more specific more early on, and lay off the over-hyped kool-aid.

* Highland does not depend on jQuery (it works without it - jQuery stuff is there only for convenience, kindof like how RxJS has a bunch of methods that deal with Node streams for convenience)
* Libs I use assume Node streams API
* Highland works in Node and Browsers
* What standards? You mean the Reactive Extensions? What makes those standards more important than the Node streams API to *JavaScript Developers?*
* Highland has backpressure support
* You can build what you want with Highland (including robots)
* Highland has great API docs (admittedly could use more tutorials, recipes & examples)

**Comment by ericelliott** [comment]
For the Backpressure bullet point, you should get specific. Say "RxJS supports multicast backpressure" and then in the extended description, tell us why that's important and point us to an example or two.

**Comment by mattpodwysocki** [comment]
@ericelliott yes, it has a dependency on jQuery for browser events.  Notice, the lack of addEventListener/removeEventListener in the code.  In fact, check out the home page of [highland.js}(http://highlandjs.org/):

For the Stream constructor:
EventEmitter / jQuery Elements - Pass in both an event name and an event emitter as the two arguments to the constructor and the first argument emitted to the event handler will be written to the new Stream.

**Comment by mattpodwysocki** [comment]
@ericelliott removed the bullet points and just added meat to the conversation. Hopefully that works better for you

**Comment by mattpodwysocki** [comment]
@ericelliott Just added some more about cooperative backpressure and some mods about `fork` and `observe`. If there is wording you don't like, please feel free to change it.  Else, can we close the issue?

**Comment by ericelliott** [comment]
I like having bullet points, I just didn't like that the bullet points were misleading. If we can reword them so that it doesn't sound like a hatchet job, that would be ideal. =)

**Comment by ericelliott** [comment]
> it has a dependency on jQuery for browser events.

This could be:

* Highland uses jQuery for DOM events. RxJS uses DOM standards.

Be sure to link to relevant code or examples from the detailed description body. If we're going to do a comparison, that is an invitation for criticism. We need to support it with evidence. =)

I really appreciate that you're willing to consider these issues instead of dismissing them out-of-hand. I think it makes a much more persuasive argument.

"RxJS works with Libs you use" could be:

* Highland streams share the Node streams API. RxJS has convenient adaptors, instead.

**Comment by mattpodwysocki** [comment]
@ericelliott I'll continue the work here, but is it good enough to close the issue?

**Comment by ericelliott** [comment]
Yeah, this is much better. Thanks!
