### ISSUE TITLE
Add retryWhen(notifier)

### ISSUE THREAD

**Issue by blesh** [Reactive-Extensions/RxJS#482]
I have a need at Netflix to have my RxJS socket implementation exponentially step back while retrying. The current implementation of `.retry(count)` is inadequate for this.

@benjchristensen told me of [a `retryWhen` operator they developed for RxJava](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Observable.java#L6257) that should suit my needs. I think the implementation in RxJava is a little more complicated than is necessary for RxJS, however, in that there's probably no need to pass an optional scheduler as an argument, because of RxJS's `scheduleOn` operator.

A simple example of the proposal is something like:

```js
var notifier = Rx.Observable.timer(1000);
var retried = myErrantObservable.retryWhen(notifier);
```

**Comment by cboden** [comment]
awesome :+1:! Would be cool to use this to implement an exponential backoff strategy for WebSocket reconnect.

**Comment by haf** [comment]
I would love this as well; it's needed anytime one goes against a HTTP server, so that's fairly often. @mattpodwysocki was it implemented elsewhere?

**Comment by blesh** [comment]
@haf ... it was implemented and merged some time ago. Check the version of RxJS you're using. It should be there.

**Comment by haf** [comment]
@blesh That was it, thanks!
