### ISSUE TITLE
An operator for a single, refCounted observable that can be "reconnected" automatically

### ISSUE THREAD

**Issue by blesh** [Reactive-Extensions/RxJS#487]
I ran into an issue that while developing my websocket that was a little tricky to work around, but I've developed a pattern for it, and I've made it into an operator.

The Problem:

1. The websocket subject (RxJS-DOM) must *complete* in order to close the underlying sockets.
2. I don't want to have more than one underlying socket for n child observables I've mapped, filtered, etc. in my app.
3. I want to keep those child observables and when I subscribe to them, they'll connect the underlying socket if necessary.
4. If all of my child observables are unsubscribed, I want to close the underlying socket.
5. refCounted observables cannot be "resubscribed". :(

My solution looks like this (as an operator):

```js
Rx.Observable.prototype.single = function(){
  var source = this;
  
  var hasObservable = false;
  var observable;
  var getObservable = function(){
    if(!hasObservable) {
      observable = source.do(function(){}, function(){
        hasObservable = false;
      }, function(){
        hasObservable = false;
      }).publish().refCount();
      hasObservable = true;
    }
    return observable;
  };
  
  return Rx.Observable.create(function(o) {
    return getObservable().subscribe(o);
  });
};

```

I'm not married to the name, at all, but it works like this:

```js
var source = Rx.Observable.interval(100).take(2).single();

var one = source.map(function() { return 'one' });
var two = source.map(function() { return 'two' });

one.subscribe(console.log);
two.subscribe(console.log);

setTimeout(function(){
  one.map(function(x) { return '!!' + x; }).subscribe(console.log);
  two.map(function(x) { return '!!' + x; }).subscribe(console.log);
}, 1000);

// -> Next: one
// -> Next: two
// -> Next: one
// -> Next: two
// ... 800 ms delay ...
// -> Next: !!one
// -> Next: !!two
// -> Next: !!one
// -> Next: !!two
```

**Comment by blesh** [comment]
Again... I think `single` is a *stupid* name.. so I'm willing to take any suggestion there.

**Comment by trxcllnt** [comment]
Ah, interesting. Resubscribes are ignored because the ConnectableObservable's Subject ignores subscribers after it's been onCompleted, but there's no way to re-inject the Connectable with a new Subject. Couldn't this also be solved by calling `multicast` with a Subject that allows re-subscriptions?

Here's two possible alternate implementations:
```javascript
var Rx = require('rx');
var source = Rx.Observable.defer(function() {
        console.log('source subscribed to');
        return Rx.Observable.interval(100).take(2);
    });

function InfiniteSubject() {
    Rx.Subject.apply(this, arguments);
}

InfiniteSubject.prototype = Object.create(Rx.Subject.prototype);
InfiniteSubject.prototype.onCompleted = function() {
    Rx.Subject.prototype.onCompleted.apply(this, arguments);
    this.isStopped = false;
}

Rx.Observable.prototype.rinseRepeat = function(rinse) {
    var source = this, rinsed = rinse(this);
    return Rx.Observable.create(function(observer) {
        return rinsed.subscribe(
            observer.onNext.bind(observer),
            observer.onError.bind(observer),
            function onCompleted() {
                rinsed = rinse(source);
                observer.onCompleted();
            }
        );
    });
}

runTest(source.multicast(new InfiniteSubject()).refCount());

runTest(source.rinseRepeat(function(socketSource) {
    return socketSource.publish().refCount();
}));

function runTest(source) {
    var one = source.map(function() { return 'one' });
    var two = source.map(function() { return 'two' });

    one.subscribe(console.log);
    two.subscribe(console.log);

    setTimeout(function() {
        one.map(function(x) { return '!!' + x; }).subscribe(console.log);
        two.map(function(x) { return '!!' + x; }).subscribe(console.log);
    }, 1000);
}
```

**Comment by blesh** [comment]
Ah.. @trxcllnt is a fellow Netflixer it appears!

The InfiniteSubject is an interesting idea. I'll need to investigate this approach, as I hadn't considered multicast.

The rinseRepeat method reflects my first efforts, actually. I can't exactly remember why I landed on what I currently have.

**Comment by mattpodwysocki** [comment]
@blesh I'd go with the approach that @trxcllnt has instead of introducing a new operator here.  Especially since `single` is already taken to define whether there is a single element that matches the predicate.

**Comment by blesh** [comment]
Yeah, the name is dumb, ignore the name, it was a placeholder. 

Whichever way is chosen, there doesn't seem to be a great native way to do this with RxJS. It's either needs an operator or a new Subject type. Anyone like me that's fairly new to RxJS is likely to throw their hands up if they encounter this scenario. (i.e. a socket that closes on complete or error, but you need to reopen by resubscribing when the network comes back online, etc)

It seems like there's a need for something to be added. @trxcllnt's suggestions seem the most flexible. 

It also seems like there should be a "recipes" doc somewhere that shows people how to put together some of these things. My solution wasn't easy to figure out for me, because, again, I still consider myself pretty new to RxJS.

**Comment by blesh** [comment]
Okay, after experimenting with these two approaches from @trxcllnt, neither of them do exactly what I want them to do.

The issue is this:

- I have a "parent" observable (a socket).
- I have many "child" observables (observables that need to subscribe to something over the socket).
- If the if the parent errors, it must bubble the error out to the children, which must retry, which also causes the parent to retry.
- There can only be one instance of the parent (lest I create n sockets)

My pattern listed in the OP is the only way I can accomplish this.

[Here is a JSBin with all three examples](http://jsbin.com/xobiruy/3/edit?html,js,output)

The results (assuming the children all `retry(4)`)

### singleInstance (method name TBD)
This is the outcome I *want*:
```
subscribe to  a
subscribe to  b
a:0
b:0
a:1
b:1
subscribe to  a
subscribe to  b
a:0
b:0
a:1
b:1
subscribe to  a
subscribe to  b
a:0
b:0
a:1
b:1
subscribe to  a
subscribe to  b
a:0
b:0
a:1
b:1
x error
x error
```

### multicast(new InfiniteSubject()).refCount()
```
subscribe to  a
subscribe to  b
a:0
b:0
a:1
b:1
subscribe to  a
subscribe to  a
subscribe to  a
x error
subscribe to  b
subscribe to  b
subscribe to  b
x error
```

### rinseRepeat(o => o.publish().refCount()) 
```
subscribe to  a
subscribe to  b
a:0
b:0
a:1
b:1
subscribe to  a
subscribe to  a
subscribe to  a
x error
subscribe to  b
subscribe to  b
subscribe to  b
x error
```

**Comment by trxcllnt** [comment]
Even if I override both onError and onCompleted on Subject to not set the isStopped or exception values,  the synchronous `retry` is hitting the `refCount` Observable's `subscribe` function before the dispose is run, so it's never disposing of the connection to its source.

Adding an onError handler to `rinseRepeat` yields the behavior you need, but it's annoying this can't be done with a new Subject type :-1: 

```javascript
Rx.Observable.prototype.rinseRepeat = function(rinse) {
    var source = this, rinsed = rinse(this);
    return Rx.Observable.create(function(observer) {
        return rinsed.subscribe(
            observer.onNext.bind(observer),
            function onError(error) {
                rinsed = rinse(source);
                observer.onError(error);
            },
            function onCompleted() {
                rinsed = rinse(source);
                observer.onCompleted();
            }
        );
    });
};
```

**Comment by blesh** [comment]
What are other use cases for `rinseRepeat`?  I'd like to submit a PR around this, it seems like a common problem that isn't easy to solve. Also, I'll talk to the RxJava guys and see if there's already any operators in their world that fit the bill.

**Comment by trxcllnt** [comment]
I can't think of any other use cases off the top of my head, bt seems like a cross between onErrorResumeNext and letBind.

**Comment by cboden** [comment]
I believe I'm attempting to do the same thing as @blesh. I've created an Observable for my WebSocket then used `rinseRepeat` from @trxcllnt to wrap it. In the latest update I'm seeing onCompleted be called once per Observer connected which I don't think is expected behaviour, after connecting to the refCount'ed source?

**Comment by blesh** [comment]
So what I needed to do was create an Observable that is refCounted, but could be reused. So it would still complete, but it could be subscribed to again even after that.

FWIW, if you're needing a WebSocket implementation that does this, I have one here that we're using at Netflix: http://github.com/blesh/RxSocketSubject  ... it's built around the RxJS-DOM implementation. (currently I have a polyfill for that in there still, since I wrote this before the updated `fromWebSocket` was released, but I'll remove that polyfill soon)

**Comment by blesh** [comment]
This situation keeps coming up, and so far the operator I've recommended has been the only effective way I've found of making this work.

**Comment by blesh** [comment]
Ran into this problem again today.

I need to be able to reconnect to a single underlying socket subject. So I do this.

Then I want to buffer/debounce messages I'm getting from this, but I don't want to have N buffers where N is the number of subscribers, but if I publsh().refCount() I can't have reconnection logic because I can't resubscribe to my buffered messages...

I need the `.singleInstance` operator, again, @mattpodwysocki ... It's my only hope.  Expect a PR because the library needs this feature, IMO.

**Comment by blesh** [comment]
I hit this scenario *again* today. This seems to be commonplace around dealing with something like the socket subject (RxJS-DOM and RxSocketSubject) where I want: 1. a single instance, 2. the connection to close when nothing is subscribed, and 3. the connection to be reopened on next subscription if it's closed.

**Comment by blesh** [comment]
I've been attacking this from multiple angles. So far the only way I've found to accomplish what I'm trying to do is my original implementation. :\

**Comment by jonahbron** [comment]
It looks like this observable hasn't been added to the build process yet.  Is there a way to import it directly?
