### ISSUE TITLE
When will `withLatestFrom` land in RxJS?

### ISSUE THREAD

**Issue by qur2** [Reactive-Extensions/RxJS#494]
I'm using the package from npmjs.org and there the latest is 2.3.22. By looking at the tags in the repo, it seems that it's indeed the latest version.

Will `withLatestFrom` be part of the next release? Is there any estimate about when it will be released? 

I need this one to try simplify some of my code. Thank you!

**Comment by mattpodwysocki** [comment]
Sorry, see [this tweet](https://twitter.com/mattpodwysocki/status/555449295386984449). One or two issues to fix with the tests before we are good to go

**Comment by qur2** [comment]
Thanks for the quick answer!
