### ISSUE TITLE
Updating 2.3.22 -> 2.3.23 breaks app, "No listener found"

### ISSUE THREAD

**Issue by mieky** [Reactive-Extensions/RxJS#498]
I have an application using Bower for frontend package management. After Bower replaced RxJS v2.3.22 with v2.3.23, our app broke with a "Error: No listener found". Downgrading to .22 has everything working again.

```"Uncaught Error: No listener found (bower_components/rxjs/dist/rx.all.js:1187"```

**Comment by mieky** [comment]
The project itself is unfortunately not open-source, but I'll help debug if I can.

**Comment by staltz** [comment]
Also, 2.3.23 should have been 2.4.0 since it adds functionality but is backwards compatible.

http://semver.org/
>MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

**Comment by mattpodwysocki** [comment]
@mieky can you turn on long stack traces for us to see where the actual error occurred?
```js
Rx.config.longStackSupport = true;
```

**Comment by mr-mig** [comment]
We have a problem in NodeJS with `2.3.23`.
The problem is the same - "no listener found".
In our case the root cause is that `EventEmitter` is transformed into Observable with a `Rx.Observable.fromEvent` call, which has a check for `off` method: https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/fromevent.js#L122

`EventEmitter`s apparently do not have the off method.

**Comment by mr-mig** [comment]
I believe this is the commit which brought the mess and regression: https://github.com/Reactive-Extensions/RxJS/commit/795a945aa9f23b2aeb47887026386262de72f156

**Comment by mattpodwysocki** [comment]
@mr-mig that's strange, because it should have been caught by this case here which checks for addListener/removeListener: https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/fromevent.js#L112-L117

**Comment by mattpodwysocki** [comment]
@mr-mig in fact, I can replicate the behavior that it does indeed work just fine with EventEmitters:
```js
> var Rx = require('rx');
undefined
> var EventEmitter = require('events').EventEmitter;
undefined
> var ee = new EventEmitter();
undefined
> var source = Rx.Observable.fromEvent(ee, 'data');
undefined
> source.subscribe(console.log);
{ isStopped: false,
  observer:
   { isStopped: false,
     _onNext: [Function],
     _onError: [Function],
     _onCompleted: [Function] },
  m:
   { isDisposed: false,
     current: { isDisposed: false, action: [Function] } } }
> ee.emit('data', 'foo');
foo
true
> ee.emit('data', 'foo');
foo
true
```

**Comment by pozadi** [comment]
looks like `typeof` missed here https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/fromevent.js#L122

**Comment by mr-mig** [comment]
@mattpodwysocki sorry, messed with the debug info. It seems that I am trying to wrap the thingy, which pretend to be an `EventEmitter`, but not a real nodejs `EventEmitter`...

**Comment by mattpodwysocki** [comment]
@mr-mig not a problem.  Fixing and republishing.  Sorry about that regression.

**Comment by mattpodwysocki** [comment]
@staltz fair enough, will do that in the next round.  Issue fixed and pushed to NPM, Bower, NuGet, etc

**Comment by mieky** [comment]
For the record, this happened on Google Chrome versions 39 and 42 with jQuery 2.1.0 and rx.dom being used. 2.3.24 indeed fixed this, thanks for the quick reaction!
