### ISSUE TITLE
Stack size exceeded with `expand` and `takeWhile`

### ISSUE THREAD

**Issue by valeriangalliat** [Reactive-Extensions/RxJS#499]
Hello,

I'm running the following snippet:

```js
var Rx = require('rx');

var i = 0;

infiniteRange(0, 20)
  .takeWhile(function () {
    return i++ < 2;
  })
  .forEach(function (x) {
    console.log(x);
  });

function infiniteRange(start, increment) {
  return Rx.Observable
    .return(start)
    .expand(function (x) {
      return Rx.Observable
        .return(x + increment);
    });
}
```

* I expect the output to be `10 20` and then exit properly, but while I get `10 20`, it's followed by a `RangeError: Maximum call stack size exceeded` in `node_modules/rx/dist/rx.all.js:1187`.

* Adding a `.map(function (x) { return x; })` between `takeWhile` and `forEach` solves the problem (in this very case, but in other operator combinations it won't always help).

* If I add a debug `map` before `takeWhile`, I can see that it's called "infinitely" even after if the `takeWhile` condition is false.

* Using `subscribe` instead of `forEach` don't help.

* It works fine if I implement `infiniteRange` as:

  ```js
  function infiniteRange(start, increment) {
    return Rx.Observable
      .range(start, Number.MAX_VALUE)
      .map(function (x) { return x * increment; });
  }
  ```

  ... instead of using `expand`, and with this `range`, the debug `map` is not called until `Number.MAX_VALUE`, it stops as expected when the `takeWhile` condition turns false.

* I use RxJs 2.3.23 and Node 0.10.35.

**Comment by mattpodwysocki** [comment]
@valeriangalliat running the latest RxJS 2.3.24 on Node 0.10.35, I cannot reproduce this issue.

**Comment by valeriangalliat** [comment]
Thank you @mattpodwysocki for trying to reproduce.

This is odd, I'm on another PC and I have the same problem, this time with latest RxJS 2.3.24 and Node 0.10.35 (exactly like you):

```
➜  npm ls
/home/val/tmp
└── rx@2.3.24

➜  node --version
v0.10.35
➜  uname -a
Linux arch 3.17.6-1-ARCH #1 SMP PREEMPT Sun Dec 7 23:43:32 UTC 2014 x86_64 GNU/Linux
➜  cat test.js
var Rx = require('rx');

var i = 0;

infiniteRange(0, 20)
  .takeWhile(function () {
    return i++ < 2;
  })
  .forEach(function (x) {
    console.log(x);
  });

function infiniteRange(start, increment) {
  return Rx.Observable
    .return(start)
    .expand(function (x) {
      return Rx.Observable
        .return(x + increment);
    });
}
➜  node test.js
0
20

/home/val/tmp/node_modules/rx/dist/rx.all.js:1213
          throw e;
                ^
RangeError: Maximum call stack size exceeded
```

**Comment by valeriangalliat** [comment]
A friend on MacOS also tried and didn't have the call stack problem.

On my side, I could reproduce the bug on OpenBSD (Node 0.10.32), but I had no problem with FreeBSD (Node 0.10.35, but I don't believe that's related to the Node version anyway).

**Comment by valeriangalliat** [comment]
I don't have this insane bug with [this `infiniteRange` implementation](https://github.com/Reactive-Extensions/RxJS/issues/503#issuecomment-70843076), so I'm closing this issue.

Though I'm still flabbergasted by the platform-specific `--stack-size` bug with the previous code. I will try to live with this question unanswered. :smile:
