### ISSUE TITLE
ControlledObservable onCompleted not firing

### ISSUE THREAD

**Issue by zhaoyeming** [Reactive-Extensions/RxJS#501]
Maybe it's intended but I cannot find documentation on this. Here is an example:

```
var source = Rx.Observable.range(1, 2).controlled();

source.subscribe(
    function (n) { console.log(n) },
    function (err) {},
    function () { console.log('onCompleted') }
);

source.request(1);
source.request(1);
source.request(1);

// 1
// 2
// (nothing happens)
```

**Comment by garthcn** [comment]
I came across the same issue and didn't find a way to 'complete' the stream and trigger `onComplete`.

**Comment by paulpdaniels** [comment]
@zhaoyeming @garthcn  After diving into the source code a bit I finally realized that there can only be one request in-flight at a time.  That is, every time you make a new request you are cancelling the previous request.  To get your desired behavior you need to use request(3); // or request(2);

However,

@mattpodwysocki I did notice what I believe to be a bug in ControlledSubject. If enableQueue is activated and the source observable completes or errors while there is an item in the queue.  That completion will never get propagated downstream.  My thought is that the upstream source could be materialized and place the augmented events onto the queue instead.

**Comment by garthcn** [comment]
@paulpdaniels thanks for looking into this. 

I tried `request(2)` and it still only prints out 1 and 2 without calling `onComplete`. If I do `request(3)`, it won't even print 1 or 2. Instead it does nothing. In fact if I call `request(x)` where x > queue_length, it does nothing. 

I think the problem may lie in https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/backpressure/controlled.js#L84

It looks like it will only call `onCompleted` when `this.hasCompleted` is true; but it sets `hasCompleted` to true in `onCompleted`: https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/backpressure/controlled.js#L49

I'm not sure if my understanding of the code is correct. 

Again thanks for looking into this!

**Comment by paulpdaniels** [comment]
Interesting, I tried it with a TestScheduler and it worked, perhaps this is some bug with using the TimeoutScheduler.  You are partially right, though I think the hasCompleted flag is only relevant if you have explicitly disabled queuing via the enableQueue parameter.  
Of more concern is https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/backpressure/controlled.js#L50 which will simply ignore the completion event if there are other events that have been queued.

**Comment by mattpodwysocki** [comment]
@paulpdaniels if you think there is a bug, could you recommend what we do to fix it?

**Comment by paulpdaniels** [comment]
I'm putting together a PR for this hopefully by the end of the weekend.

**Comment by paulpdaniels** [comment]
@garthcn Is this issue fixed for you? Can it be closed?

**Comment by mattpodwysocki** [comment]
@garthcn @paulpdaniels closing the issue and will reopen if not fixed.
