### ISSUE TITLE
Trailing comma in core/intro.js

### ISSUE THREAD

**Issue by jfsiii** [Reactive-Extensions/RxJS#505]
There is [a trailing comma in core/intro.js](https://github.com/Reactive-Extensions/RxJS/blob/36acb835fbdd7b6e2c20d2cef989782cd3d8a6da/src/core/intro.js#L25).

The [compatibility section of the README](https://github.com/Reactive-Extensions/RxJS/tree/36acb835fbdd7b6e2c20d2cef989782cd3d8a6da#compatibility) says IE6+ is supported, but [this site](http://rauschma.github.io/js-feature-matrix/) says IE 6 & 7 will error on a trailing comma.

It also causes an error in Closure Compiler, which prevents compression.

**Comment by mattpodwysocki** [comment]
@jfsiii fixed!
