### ISSUE TITLE
Dispose not propagated with recent release

### ISSUE THREAD

**Issue by cboden** [Reactive-Extensions/RxJS#513]
From v2.3.20 to v2.3.21 a change was introduced where an observable I have is no longer being disposed. 

[Here is a jsbin](http://jsbin.com/nuvivebubi/1/edit) giving a basic demonstration of the output differing if you switch version of the RxJS lib.

**Comment by cboden** [comment]
It seems `.subscribe` on the `subject` works but `undefined` is returned instead of a disposable object.

**Comment by mattpodwysocki** [comment]
@cboden fixed the regression. Apologize!
