### ISSUE TITLE
Performance Upgrades

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/RxJS#519]
Upgrade the following operators so that we don't use chained scopes for composition:
- `Rx.Observable#filter`
- `Rx.Observable#map`
- `Rx.Observable#merge`
- `Rx.Observable#mergeAll`
- `Rx.Observable#switch`
- `Rx.Observable#toArray`

Add method fusion to the following operators to cut down on the number of `Observer` objects created:
- `Rx.Observable#filter`
- `Rx.Observable#map`

Investigate performance for creation operators
- `Rx.Observable.of`
- `Rx.Observable.from`
- `Rx.Observable.fromArray`
- `Rx.Observable.range`

All new work should go in the following folder: [perf](https://github.com/Reactive-Extensions/RxJS/tree/master/src/core/perf/operators)
Each should have a performance test associated.

**Comment by Rigeroso** [comment]
4fc39ae introduces a bug in src/core/linq/observable/fromnodecallback.js:20 and others:
```
var len = arguments.length, results = new Array(len - 1);
```
arguments.length might be 0, if the callback yields no value, which will lead to a RangeError (new Array(-1).

**Comment by mattpodwysocki** [comment]
@Rigeroso can you give me an example where that would be the case?  Remember, this expects the function to be in the style of a node.js callback, being error first, then result, whatever it may be.  

```js
fs.rename('/tmp/hello', '/tmp/world', function (err) {
  if (err) throw err;
  fs.stat('/tmp/world', function (err, stats) {
    if (err) throw err;
    console.log('stats: ' + JSON.stringify(stats));
  });
});
```

This becomes simply:
```js
var rename = Rx.Observable.fromNodeCallback(fs.rename),
    stat = Rx.Observable.fromNodeCallback(fs.stat);

rename('/tmp/hello', '/tmp/world')
  .flatMap(function () { return stat('/tmp/world'); })
  .subscribe(
        function (stats) { console.log('stats: ' + JSON.stringify(stats)); },
        function (err) { console.warn(err); });
```

**Comment by Rigeroso** [comment]
For example in [node-serialport](https://github.com/voodootikigod/node-serialport) the open method yields an error or nothing.

```
serialPort.open(function (error) {
  if ( error ) {
    console.log('failed to open: '+error);
  } else {
    console.log('open');
    serialPort.on('data', function(data) {
      console.log('data received: ' + data);
    });
    serialPort.write("ls\n", function(err, results) {
      console.log('err ' + err);
      console.log('results ' + results);
    });
  }
});
```
I don't know whether there is an example in the node core API, but I think it is a valid node style callback.

**Comment by mattpodwysocki** [comment]
@Rigeroso should be closed, sorry I've left this open
