### ISSUE TITLE
dist/rx.async.map.js missing?

### ISSUE THREAD

**Issue by softwarepsychology** [Reactive-Extensions/RxJS#521]
Hello, is the dist/rx.async.map.js file missing? The bower.json includes the file but seems to be missing in the dist directory

**Comment by paulpdaniels** [comment]
Not sure if you mean the rx.async.min.js or rx.async.map.  Regardless, both are in the dist folder.

**Comment by mattpodwysocki** [comment]
@softwarepsychology it was missing from the bower file I believe...

**Comment by softwarepsychology** [comment]
I now see   "dist/rx.async.compat.map.js" in bower.json instead of just   "dist/rx.async.compat.map" . Is that a typo?

**Comment by mattpodwysocki** [comment]
@softwarepsychology yes, probably a typo, will fix

**Comment by mattpodwysocki** [comment]
Fixed and will be part of the next release
