### ISSUE TITLE
TestScheduler same-time ordering

### ISSUE THREAD

**Issue by akarnokd** [Reactive-Extensions/RxJS#523]
Hello, I'm trying to port the ```join``` and ```groupJoin``` tests over to RxJava and I've run into an ordering problem with ```JoinOp_Normal_I``` test: Instead of getting ``` onNext(712, "7man"), onNext(712, "6man") ```, I get them swapped with RxJava's ```join``` implementation. 

This could be just a bug in RxJava's ```join```, but I suspect RxJS's ```TestScheduler``` might not order tasks scheduled at the same time the same way RxJava's ```TestScheduler``` does. In RxJava, tasks scheduled to the exact same time have a monotonic counter as well so ties are always broken up in FIFO order.

Could someone confirm RxJS's TestScheduler does such logic or not?

**Comment by paulpdaniels** [comment]
From looking at the PriorityQueue implementation used by the TestScheduler, specifically

https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/internal/priorityqueue.js#L9

and 

https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/internal/priorityqueue.js#L72

That is at the very least that appears to be the _intent_. I tried out a small JSFiddle which appears to support that as well.

http://jsfiddle.net/x98jgz1L/

**Comment by mattpodwysocki** [comment]
@paulpdaniels @akarnokd the true intent of the GroupJoin tests should be found here: https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/Tests.System.Reactive/Tests/Linq/ObservableStandardQueryOperatorTest.cs#L7974

Never mind what they are in RxJS. It's a bug that's been sitting there for a while.

**Comment by akarnokd** [comment]
Thanks.
