### ISSUE TITLE
Some sort of mergeLatest similar to bacon's with.

### ISSUE THREAD

**Issue by blesh** [Reactive-Extensions/RxJS#524]
[This StackOverflow question](http://stackoverflow.com/questions/28153548/rxjs-equivalent-of-bacon-when-with-properties-which-are-sampled-but-not-par/28157642) reminded me I wanted to create an issue around this...

I've found myself doing the following pattern repeatedly:

```js
var foos = observableOfFoos();
var bars = observableOfBars();
var bazs = observableOfBazs();

var mergedLatest = Observable.merge(
   foos.map(x => ({ key: 'foo', value: x })),
   bars.map(x => ({ key: 'bar', value: x })),
   bazs.map(x => ({ key: 'baz', value: x }))
).scan({ foo: null, bar: null, baz: null }, (s, d) => {
  s[d.key] = d.value;
  return s;  
});
```
Or at times:

```js
var mergedLatest = Observable.merge(
   foos.map(x => ({ index: 0, value: x })),
   bars.map(x => ({ index: 1, value: x })),
   bazs.map(x => ({ index: 2,  value: x }))
).scan([null, null, null], (s, d) => {
  s[d.index] = d.value;
  return s;  
});
```

It seems like this could be made into an operator to improve developer ergonomics. I guess Bacon has a `.when()` function that accomplishes something similar.

I'd propose something similar to what is present in bacon's when, like:

```js
Observable.mergeLatest(foos, bars, bazs, (foo, bar, baz) => {
    return { foo: foo, bar: bar, baz: baz }; // any result here.
});
```

**Comment by trxcllnt** [comment]
How is this different from combineLatest?

**Comment by blesh** [comment]
@trxcllnt ... it's different because I knew how to do it this way, and I didn't know about combineLatest. 👍

Okay... I'm just going to go back to my stuff and stop being dumb now...

**Comment by trxcllnt** [comment]
@blesh no worries ^_0

**Comment by blesh** [comment]
It seems like the organization of the documentation and/or the naming practices around these operators might need rethought. I'm unsure how I would have found combineLatest. I was looking for some sort of merge I guess. I've even looked more than once thinking "There's no way this doesn't exist".

**Comment by trxcllnt** [comment]
@blesh have you seen the static and instance operator decision trees? I do wish they were more prominently displayed, but I modeled them after the one @richardszalay did for raix, which helped me immensely when I was first learning Rx.

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/which-static.md
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/which-instance.md
original: https://github.com/richardszalay/raix/wiki/Reactive-Operators

**Comment by blesh** [comment]
Now I haven't seen that, thanks. I'll take a look through it.

@trxcllnt --- FWIW, one way that what I'm doing differs slightly from combineLatest is it emits even if it hasn't received a "latest" from every observable.

**Comment by trxcllnt** [comment]
@blesh this is true, though you could also use startWith(null) to seed the values, e.g.
```javascript
var a = Observable.never(),
    b = Observable.return("b"),
    c = Observable.from(1, 2, 3),
    concat = Array.prototype.concat,
Observable.combinLatest(
    a.startWith(null),
    b.startWith(null),
    c.startWith(null),
    concat.bind([])).
    skip(1). // skip because the first Array will be [null, null, null]
    subscribe(function(latest) { console.log(latest); });
```

**Comment by blesh** [comment]
Heh... and for `startWith` I've been doing `Observable.merge(Observable.just(42), a)` ... 

:facepalm:
