### ISSUE TITLE
Make shareReplay connectable

### ISSUE THREAD

**Issue by cboden** [Reactive-Extensions/RxJS#527]
When calling `shareReplay()` on an `Observable` it would be nice to be able to `connect()` to it to start recording the `Observable`.

**Comment by urmastalimaa** [comment]
`shareReplay` is just short for `replay().refCount()`, so you can just use `replay()` which is _connectable_.

**Comment by mattpodwysocki** [comment]
@cboden I agree with @urmastalimaa that that's already available to you via `replay`.  You don't need to do anything more than call `connect` yourself.  Is there any other concern here?

**Comment by cboden** [comment]
```javascript
var myReplay = myObservable.replay();
var myDisposable = myReplay.connect();
var mySharedReplay = myReplay.refCount(); // subscribe to this
```

Is that correct? All subscribers connecting to `mySharedReplay` would receive the same data that bubbles through the connected Observables, which would only go through once?

**Comment by urmastalimaa** [comment]
@cboden 
```js
var myObservable = Rx.Observable.return(5).do(function(){console.log("side effect")});
var replayedObservable = myObservable.replay();
var myDisposable = replayedObservable.connect();
// => side effect

replayedObservable.subscribe(console.log.bind(console));
// => 5
replayedObservable.subscribe(console.log.bind(console));
// => 5
```

Note that `replayedObservable` is a _ConnectableObservable_. 
If you want to hide that, then you can use `var mySharedObservable = replayedObservable.asObservable()` and share that with others.

**Comment by cboden** [comment]
Thanks @urmastalimaa. Hopefully last question then: If `.replay()` ensures the side effect is only happening once what is the difference between `.replay()` and `.shareReplay()` (aside from the *ConnectableObservable` being returned)?

**Comment by urmastalimaa** [comment]
Check out https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/sharereplay.md.

Basically with `.shareReplay()` or anything that uses `.refCount()` you are giving control over when the underlying observable is subscribed to and when that subscription is disposed to the number of active subscribers on the 
`var sharedObservabled = underlyingObservable.shareReplay()` 
observable and it's fluctuation.

When you are using `.replay()` and `.connect()` then you have precise control over when the subscription to the underlying observable begins and ends.

When there are side effects concerning _subscribe_/_dispose_ you should prefer `.connect()` alternatives.

**Comment by cboden** [comment]
I understand now. Thank you very much for your explanations and patience @urmastalimaa!
