### ISSUE TITLE
Duplicated dist code when importing RxJS as npm module

### ISSUE THREAD

**Issue by staltz** [Reactive-Extensions/RxJS#531]
Hi, I noticed this difference when upgrading RxJS 2.3.14 to 2.3.18: lots of duplicate code when RxJS is packaged as a dependency in an application and distributed with Browserify (I tested multiple versions of Browserify and concluded that they all behave the same, hence the problem has to be with RxJS).

For instance, using Rx 2.3.14 here in Cycle's dist file, you can see `flatMapLatest` defined only in one place:
https://github.com/staltz/cycle/blob/v0.4.0/dist/cycle.js#L4930

Using Rx 2.3.18 here in Cycle's dist file, you can see `flatMapLatest` defined in two places:
https://github.com/staltz/cycle/blob/v0.5.0/dist/cycle.js#L5041
https://github.com/staltz/cycle/blob/v0.5.0/dist/cycle.js#L14316

Versions above 2.3.18, such as 2.3.24, also suffer from this.

It's not just flatMapLatest. A lot of code is duplicated.

Related: https://github.com/staltz/cycle/issues/2

**Comment by mattpodwysocki** [comment]
@staltz that's strange, I would have imagined browserify would just take the index.js which should only reference the code only once.  Am I mistaken in this behavior?

**Comment by staltz** [comment]
The way I'm requiring RxJS is just using the conventional `var Rx = require('rx')` which should be pointing to index.js.
I am requiring rx in multiple places in the code, though. But that isn't new compared to older versions.

**Comment by mattpodwysocki** [comment]
@staltz I think I know what's going on here. I'm pulling in `rx.all.js` and then pulling in `rx.testing.js` and `rx.sorting.js` which are looking for `rx.js`, so let's go ahead and fix that.

**Comment by mattpodwysocki** [comment]
@staltz fixed as of https://github.com/Reactive-Extensions/RxJS/commit/7ed4dd3c7b6324e11a7ad0fb32cb925e516594ab

**Comment by staltz** [comment]
@mattpodwysocki This issue is still happening on v2.3.25
