### ISSUE TITLE
subscribe ignores thisArg

### ISSUE THREAD

**Issue by pekeler** [Reactive-Extensions/RxJS#533]
thisArg doesn't work for me for `subscribe(onNext, onError, onCompleted, thisArg);`

```
var Rx = require('rx');
var that = this;

// doesn't work
Rx.Observable.timer(10).subscribe(
  function(x) {console.log(this === that);},
  function(err) {},
  function() {},
  this
);

// works
Rx.Observable.timer(10).subscribe(
  function(x) {console.log(this === that);}.bind(this),
  function(err) {},
  function() {}
);

// works
Rx.Observable.timer(10).subscribeOnCompleted(
  function() {console.log(this === that);},
  this
);
```

**Comment by mattpodwysocki** [comment]
@pekeler that's an error in the documentation as a `[thisArg]` is not supported on `subscribe` but is supported on its variants such as `subscribeOnNext`, `subscribeOnError` and `subscribeOnCompleted`.  Would it even make sense to have it on `subscribe`? I'm open if it makes any difference.

**Comment by pekeler** [comment]
I don't feel too strongly about this. Fixing the docs would be great, too.

**Comment by mattpodwysocki** [comment]
@pekeler ok, I'll fix the docs

**Comment by pekeler** [comment]
Thx!
