### ISSUE TITLE
transducers library names

### ISSUE THREAD

**Issue by monfera** [Reactive-Extensions/RxJS#535]
The two library names on this page appear mixed up: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/transducers.md

AFAIK James Long published his lib first, and named it as one would: transducers.js
Then I guess Cognitect released it and needed to find another name: transducers-js

Btw. a comparison would be interesting, as the former is half the size of the latter, yet the API is fairly similar. The library from James seems to have performed pretty well on this microbenchmark: http://jsperf.com/like-a-linq-libraries-performance/12
No idea w.r.t. the Cognitect version.

**Comment by mattpodwysocki** [comment]
@monfera ok, will fix.

**Comment by monfera** [comment]
Thanks and congrats for your amazing library!

**Comment by mattpodwysocki** [comment]
@monfera you're most welcome!
