### ISSUE TITLE
Filtering skips map in master

### ISSUE THREAD

**Issue by cboden** [Reactive-Extensions/RxJS#537]
The sample code below demonstrates the issue I'm having in master:
```javascript
Rx.Observable.range(1, 3)
.map(myClassFactory)
.filter(function(x) {
    return true;
})
.subscribe(function(x) {
    console.log(x instanceof MyClass);
});

function myClassFactory(x) {
    return new MyClass(x);
}

function MyClass(x) {
    this.x = x;
}

MyClass.prototype.x = 0;
```

Output is:
> false
false
false

Expected:
> true
true
true

Oddly enough, if I put a side effect in between filter and map (a `.do` with a noop action) the mapped objects come through.

**Comment by mattpodwysocki** [comment]
@cboden fixed by removing the map/filter optimization
