### ISSUE TITLE
window with replay?

### ISSUE THREAD

**Issue by cboden** [Reactive-Extensions/RxJS#539]
I have a data source that I am displaying as a table on my website. The user is then able to filter the dataset. I have a [demo jsbin](http://jsbin.com/worotivema/1/edit?js,output) showing what I currently have and am trying to do.

**Comment by paulpdaniels** [comment]
shareReplay() isn't working because window doesn't resubscribe when a new window is created, I think you need replay further down stream, though off the top of my head I'm not entire sure how to refactor it.

**Comment by cboden** [comment]
I had to re-think my approach to it. Turns out I was over-complicating my thinking. I managed to get my desired result by using the filter as the initial source. [New jsbin](http://jsbin.com/zivuviluve/1/edit?js,output).

**Comment by paulpdaniels** [comment]
In the new one even the replay() is not required, since the source sequence will be resubscribed to every time switcher onNexts

**Comment by cboden** [comment]
That's just my bad example  :)   My actual app the source is a hot WebSocket.

**Comment by cboden** [comment]
Crap. Apparently I was mistaken. The replay is not working.  :-/
