### ISSUE TITLE
ISubject Typescript Definition

### ISSUE THREAD

**Issue by oliverw** [Reactive-Extensions/RxJS#585]
The current typescript definition looks like this:

```typescript
interface ISubject<T> extends Observable<T>, Observer<T>, IDisposable {
	hasObservers(): boolean;
}
```

In the rare event that you actually have to implement ISubject, this forces you to implement a metric ton of methods. Wouldn't this version make more sense:

```typescript
interface ISubject<T> extends IObservable<T>, IObserver<T>, IDisposable {
	hasObservers(): boolean;
}
```

**Comment by mattpodwysocki** [comment]
@oliverw sorry it took me so long to get to this, but it is as you asked for
