### ISSUE TITLE
Mapping observable constructed from an array is skipping odd indices

### ISSUE THREAD

**Issue by dwsmorris** [Reactive-Extensions/RxJS#587]
var integers = Rx.Observable.from([0,1,2,3]);

integers.map(function(value) {
  // only 0 and 2 are coming, 1 and 3 have been lost
}).subscribe();

This issue has been introduced between 2.3.14 and 2.3.16.
Seen in related mapping functions.

**Comment by mattpodwysocki** [comment]
@dwsmorris cannot reproduce.  Can you give me a full reproduction?  For example, this works on the latest just fine:
```js
var Rx = require('rx');

var integers = Rx.Observable.from([0,1,2,3]);

integers.map(function(value) {
  return value * value;
}).subscribe(console.log);
```

Output
```bash
λ node ..\foo.js
0
1
4
9
```

**Comment by dwsmorris** [comment]
hi matthew,
 
apologies - I mislogged this bug completely.
the issue is actually related to zip:
 
<!DOCTYPE html>
<html><head></head>
<body>
 <script type="text/javascript" src="rx.lite.js"></script>
 <script>
  var integers = Rx.Observable.from([0, 1, 2, 3]);
  var resultStream = integers.zip(integers, function (a, b) {
   return [a, b];
  }).subscribe(function (pair) {
   console.log(pair[0] + ":" + pair[1])
  });
 </script>
</body>
</html>
 
output at 2.3.14:
0:0
1:1
2:2
3:3
I think this is correct.
 
output at current head:
0:1
2:3
 
----------------------------------
 
I was actually performing something like the following:
 
  var resultStream = integers.zip(integers.map(function (value) { return value * value; }), function (a, b) {
   return [a, b];
  }).subscribe(function (pair) {
   console.log(pair[0] + ":" + pair[1])
  });

which now yields:
0:1
2:9
 
instead of the expected:
0:0
1:1
2:4
3:9
as it did back at v2.3.14
 
-----------------------------------
please close or modify the original case, or let me know if I can/should do that.
 
thanks,
darryl
 
Date: Thu, 12 Feb 2015 11:52:18 -0800

**Comment by mattpodwysocki** [comment]
@dwsmorris yes, please file a different issue on this.
