### ISSUE TITLE
"Which Operator to Use? - Instance Operators" contains broken link

### ISSUE THREAD

**Issue by jzvandenoever** [Reactive-Extensions/RxJS#592]
This holds for the following documentation page https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/which-instance.md

The link to the filter/where documentation page is broken. Currently it points to https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/filter.md which does not exist.

I presume it should be pointing at https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/where.md

**Comment by jzvandenoever** [comment]
The following links on that same page are also affected:
* groupJoin - https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/groupJoin.md
* amb - https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/amproto.md
* shareLast - https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/sharelast.md (As far as I can tell this is not something that exists as an operator currently.)
* flatmapLatest - https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/flatmaplastest
*  toArray - https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/toArray.md

**Comment by mattpodwysocki** [comment]
@jzvandenoever merged
