### ISSUE TITLE
examples/databinding computed value bug

### ISSUE THREAD

**Issue by hege91** [Reactive-Extensions/RxJS#598]
The "<firstName> <lastName>" computed value evaluates to "<firstName> undefined". (commit 89b9dd) (using chrome 40 on windows)
I suspect the `len--;` line in `combineLatest` is causing the problem. (dist/rx.lite.compat.js:2747 commit: 31d888)

**Comment by mattpodwysocki** [comment]
@hege91 fixed as of latest edge build
