### ISSUE TITLE
Publish rx-lite to NPM

### ISSUE THREAD

**Issue by Zolmeister** [Reactive-Extensions/RxJS#607]
Documentation here suggests there should be an npm package for rx-lite
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/libraries/rx.lite.md

However, it does not seem to have been published yet.

Thanks.

**Comment by Zolmeister** [comment]
Update: The documentation has changed via https://github.com/Reactive-Extensions/RxJS/commit/642f61b60aa257aeec78d7e66029b6b17f2f26ad (@dotfold)

This is now simply a request to publish `rx-lite` on npm. This would allow client-side projects using webpack and browserify to use rx-lite easily

**Comment by dotfold** [comment]
As @mattpodwysocki asked me (when I asked the same question) what is the motivation for using `rx-lite` specifically?

**Comment by Zolmeister** [comment]
The answer is the same as why it even exists in the first place.
Minified + gzipped rx.lite.js (alone) the size is **~40%** smaller than rx.all.js
You even reccomend using the lite version in the browser yourself (see npm readme).

Webpack and browserify have transformed the client-side landscape to include client-side js modules on npm a norm. In fact, the framework I'm working on ([Zorium](https://github.com/Zorium/zorium)) depends entirely on a webpack npm pipeline.

**Comment by dotfold** [comment]
Browserify and webpack workflows were exactly what I was thinking of too. :+1:

**Comment by jaredly** [comment]
But webpack and browserify will only bundle up what you `require()`. So you can just `require("rx/path/to/rx-lite.js")`.
Is there another reason to have a separate npm package?

**Comment by Zolmeister** [comment]
@jaredly while it is _possible_ to reach inside and grab it (the path is `rx/dist/rx.lite.js`), you are then creating an implicit dependency which would break if the path ever changed. Unless this was documented as the proper way to require it, I wouldn't expect any developer to feel safe doing something like that in production code.

(It's also messier; because the dependency exists in package.json then all developers on the project have to know never to use the regular module or risk creating an even worse file-size situation)

**Comment by Zolmeister** [comment]
Any update on this?

**Comment by Zolmeister** [comment]
@jaredly @dotfold

**Comment by mattpodwysocki** [comment]
@Zolmeister Question.  Would you prefer `rx-lite` published as well as `rx-lite-compat`.  In addition, would it then make sense to have a `rx-lite.extras` and a `rx-lite-extras.compat` as well?  That's what I'm planning on publishing today.

**Comment by Zolmeister** [comment]
@mattpodwysocki Personally I only plan on using `rx-lite`, and am unclear what `rx-lite.extras` adds past just using `rx`. But of course if it's not too much trouble there is not downside to adding all of them.

**Comment by mattpodwysocki** [comment]
@Zolmeister well, they should be all in there respectively:
- `rx-lite`
- `rx-lite-compat`
- `rx-lite-extras`
- `rx-lite-extras-compat`

Let me know if you have any issues there

**Comment by Zolmeister** [comment]
Awesome, thanks!

**Comment by salper** [comment]
Hi. Seems like these packages are not up to date. Will these be maintained in the future ?
