### ISSUE TITLE
Rx.Subject behavior

### ISSUE THREAD

**Issue by ivan-kleshnin** [Reactive-Extensions/RxJS#609]
Is this correct behavior, that `observer` argument of `Rx.Subject` receives only values pushed to `subject` while `subscriber` receives only those from `observable`? Everything else were intuitive but this confuses me a lot. 

```javascript
var observer = {onNext: function(v) {console.log("observer sees:", v);}};
var observable = Rx.Observable.from([1, 2]);
var subject = Rx.Subject.create(observer, observable);

var subscription = subject.subscribe(function (v) {
 console.log("subscriber sees:", v);
});

subject.onNext(3);
subject.onNext(4);
```

```
subscriber sees: 1
subscriber sees: 2
observer sees: 3
observer sees: 4
```

I expected all of them will have the same input.

**Comment by paulpdaniels** [comment]
Yes this is the correct behavior.  The subject contract simply says that it is both an observer and an observable.  In most cases it is used as a pass-through, `new Rx.Subject()`.  In some cases though, you want the input and output streams to be separate.

You can find several examples of this in the [RxJS-DOM](https://github.com/Reactive-Extensions/RxJS-DOM) project.  Look at the fromWebSocket and fromWorker operators.

**Comment by ivan-kleshnin** [comment]
So how should I create an `Rx.Subject` to see both default and push values sequentially in one handler?
I don't see similar examples or I **can't** see them through other code.

**Comment by paulpdaniels** [comment]
Well if you wanted it encapsulated in a Subject you would have to roll your own I imagine, none of the current subjects have an immutable set of values to prepend to each subscriber.  I would suggest using an operator to do this though:

```javascript

var subject = new Rx.Subject();
var source = subject.startWith(1, 2);


var subscription = source.subscribe(function (v) {
 console.log("subscriber sees:", v);
});

subject.onNext(3);
subject.onNext(4);


//subscriber sees:1
//subscriber sees:2
//subscriber sees:3
//subscriber sees:4


```

**Comment by ivan-kleshnin** [comment]
Thanks, it's getting clear :thumbsup:
