### ISSUE TITLE
Question about promise chains/queues in Rx

### ISSUE THREAD

**Issue by aaronshaf** [Reactive-Extensions/RxJS#613]
Is there a more elegant way in Rx of accomplishing a queue? I am essentially trying to chain the downloads here. I would use "throttle", but as I understand it, throttling or pausing would "throw away" some of the incoming items. 

```javascript
var promiseChain = Promise.resolve()

var subscription = Rx.Node.fromStream(fileStream)
  .map( (data) => {
    return csv.parse(data.toString())
  } )
  .flatMap((images) => images)
  .map((image) => {
    promiseChain = promiseChain.then(download.bind(null, image))
  })
  .subscribe()
```

**Comment by aaronshaf** [comment]
Here is another attempt, this time using `controlled`:

```javascript
var fileStream = fs.createReadStream("./images.csv")

var source = Rx.Node.fromStream(fileStream)
  .map( (data) => {
    return csv.parse(data.toString())
  } )
  .flatMap((images) => images)
  .controlled()

var subscription = source.map((image) => {
    download(image).then(() => {
      source.request(1)
    })
  })
  .subscribe()
```

I still wonder if there is a better way to do this. Intuitively, I would want something like:

```javascript
var fileStream = fs.createReadStream("./images.csv")

Rx.Node.fromStream(fileStream)
  .map( (data) => {
    return csv.parse(data.toString())
  } )
  .flatMap((images) => images)
  .limit(1) // or even: parallelLimit(3)
  .map((image) => {
    return download(image)
  })
  .subscribe()
```

**Comment by aaronshaf** [comment]
Here is my latest:

```javascript
var fileStream = fs.createReadStream("./images.csv")

var source = Rx.Node.fromStream(fileStream)
  .map((data) => {
    return csv.parse(data.toString())
  })
  .flatMap((images) => images)
  .controlled()

var subscription = source.forEach(function(image) {
  somethingAsync(() => {
    source.request(1)
  })
})

source.request(1)
```

Feel free to suggest a more elegant way, or if this is the best way, please close the issue. Thanks for listening.

**Comment by urmastalimaa** [comment]
```javascript
Rx.Node.fromStream(fileStream)
  .map((data) => {
    return csv.parse(data.toString())
  })
  .flatMap((imageUrls) => imageUrls)
  .concatMap(download) // assuming download takes imageUrl and returns a promise
  .subscribe(handleImageData)
```

downloads the images one by one

**Comment by aaronshaf** [comment]
That does not seem to work:

http://jsbin.com/toqem/3/edit?js,console

**Comment by aaronshaf** [comment]
Looks like this is what I want:

> "In future versions of RxJS, the idea of the controlled observable will be baked into the subscription itself which then allows the backpressure to be an essential part of the contract or requesting n number of items." https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/backpressure.md

#508 looks relevant.

**Comment by urmastalimaa** [comment]
My mistake, you also need to add [defer](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/defer.md) to start resolving the promise only when the time is right.
Corrected [jsfiddle](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/defer.md)
and fixed example
```javascript
Rx.Node.fromStream(fileStream)
  .map((data) => {
    return csv.parse(data.toString())
  })
  .flatMap((imageUrls) => imageUrls)
  .concatMap(function(imageUrl){
     return Rx.Observable.defer(function(){
       return download(imageUrl);  // assuming download takes imageUrl and returns a promise
     });
   }) 
  .subscribe(handleImageData)
```

**Comment by mattpodwysocki** [comment]
@aaronshaf does the sample from @urmastalimaa work for you?

**Comment by aaronshaf** [comment]
Yes, thank you, @urmastalimaa!

**Comment by aaronshaf** [comment]
Here is an updated jsbin:

http://jsbin.com/kodoni/1/edit?js,console

**Comment by aaronshaf** [comment]
This is wonderful.

But I am left wondering why returning a promise

**Comment by mattpodwysocki** [comment]
@aaronshaf because by definition, Promises are "hot", therefore they run immediately regardless of being subscribed to or not.  By adding `defer`, we delay the effect of it being hot until someone actually subscribes to the inner observable.

**Comment by aaronshaf** [comment]
Makes sense now. Thank you _so_ much, neighbors, for the help & explanation.

**Comment by veenedu** [comment]
@urmastalimaa 
You code works for me too. I was using `flatMap` and `concatMap` fixed the thing.

How can I create an observable, which I can subscribe to, which gets called once after all urls have been downloaded.

```
var downloadStream$ = Rx.Node.fromStream(fileStream)
  .map((data) => {
    return csv.parse(data.toString())
  })
  .flatMap((imageUrls) => imageUrls)
  .concatMap(function(imageUrl){
     return Rx.Observable.defer(function(){
       return download(imageUrl);  // assuming download takes imageUrl and returns a promise
     });
   }) 
 
 downloadStream$.subscribe(called_after_each_download);
 
 //I am looking for help here
 downloadStream$.someThing.subscribe(called_once_after_all_downloaded);
```

**Comment by urmastalimaa** [comment]
You probably want to use https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/forkjoin.js

```
var allDownloadResults = Rx.Node.fromStream(fileStream)
  .map((data) => {
    return csv.parse(data.toString())
  })
  .flatMap(function(imageUrls) {
    Rx.Observable.forkJoin(imageUrls.map(download));
  }
 ```
