### ISSUE TITLE
groupBy(..).concatAll() not working as expected

### ISSUE THREAD

**Issue by urmastalimaa** [Reactive-Extensions/RxJS#615]
I ran into an issue using `concatAll` combined with `groupBy`.
```javascript
Rx.Observable.range(1, 4)
  .groupBy(
    function(x){return x % 3; }, 
    function(x){return x; }
  ).concatAll()
  .subscribe(console.log.bind(console))
// Expected: 1, 4, 2, 3
// Actual: 1, 4
```

When used with `range`, it works as expected.
```javascript
Rx.Observable.range(1, 4)
  .map(function(x){
    return Rx.Observable.range(3, x)
  }).concatAll()
  .subscribe(console.log.bind(console))
//  3, 3, 4, 3, 4, 5, 3, 4, 5, 6
```

**Comment by mattpodwysocki** [comment]
@urmastalimaa actually it is working as expected.  Here's why:

The first group sends `onCompleted` after sending 4 (which % 3 == 1, just like the first element), so `concatAll` can not subscribe to the group for 2 and 0 until that time. At that point, the prior values of 2 and 3 have already been sent to the groups which were never subscribed to.  However, instead of using `concatAll` you use `mergeAll`, you will get the behavior you think you want.

```js
Rx.Observable.range(1, 4)
  .groupBy(
    function(x){return x % 3; }, 
    function(x){return x; }
  ).concatAll()
  .subscribe(console.log);
// =>: 1, 4

Rx.Observable.range(1, 4)
  .groupBy(
    function(x){return x % 3; }, 
    function(x){return x; }
  ).mergeAll()
  .subscribe(console.log);
// =>: 1, 2, 3, 4
```

Does that make sense?

**Comment by ljani** [comment]
@mattpodwysocki Thanks for clarification. I've tried to wrap my head around this and I cannot figure out how do I ensure the order. If you don't mind, could you give me a short example?

First, let me try to explain what I'm looking for. Consider this:

```
Rx.Observable.range(1, 4)
    .groupBy(x => x % 2)
    // Artificial delay, in real world this could be caused by processing?
    .map(group => group.delay(group.key === 1 ? 1000 : 0))
    .mergeAll()
    .subscribe(console.log.bind(console))
```

By changing the delay from `group.key === 1` to `group.key === 0` either the group `1 3` or the group `2 4` comes first. How should I ensure that the first value (in this case `1`) received by the `groupby` will be also be first group always and only after that the second group is concat'd? In other words, I want to ensure that `1 3` becomes always first even if it was delayed. Does this make any sense to you?
