### ISSUE TITLE
Current npm package broken

### ISSUE THREAD

**Issue by crispy1989** [Reactive-Extensions/RxJS#621]
This may not be the best place for this, but I wanted to make sure it came to your attention.  (I also commented the same on the commit that updated the package.json version to 2.4.2, although the commit itself doesn't seem to be at fault: https://github.com/Reactive-Extensions/RxJS/commit/8df6cf88b0703339eaec37c01513b1d7f7862d17 )

It looks like version 2.4.2 got published to npm without updating the latest tag. The new published version is somehow missing its index.js in the root, which is causing node to break when trying to require it.

Even though the latest tag wasn't updated, some packages include version '*' (including dependencies of rx itself), which is causing npm to pull in 2.4.2 instead of the 'latest' tag 2.4.1; and npm'd dedup'ing behavior is causing other packages that reference approximate versions (such as '^2.4.0') to instead use the broken 2.4.2 .

It appears that, at the moment, any package depending on rx is broken if npm install is run without a previous version of rx being cached. You'll need to publish a new version (2.4.3) because npm won't let you overwrite an existing version. You may also want to consider using 'npm unpublish' to remove the broken version.

**Comment by RobinQu** [comment]
+1

In package.json:

```
"main": "index.js",
```

But no index.js after install rx@2.4.2

![image](https://cloud.githubusercontent.com/assets/342549/6611968/df1c2c8e-c8ae-11e4-9c46-4e4a6b448d42.png)

**Comment by mike-treadway** [comment]
We use bower, which depends on rx. Since we already had a local repository, we just pulled down rx@2.4.1, updated its version in package.json to 2.4.3, and published to our local repo.

I'm watching this thread to see when it gets fixed so I can unpublish that version.

**Comment by mattpodwysocki** [comment]
@crispy1989 was already fixed and deployed 2.4.3 just now
