### ISSUE TITLE
controlled observable can lose request resulting in hanging, code attached to reproduce the race condition of sync/async request next

### ISSUE THREAD

**Issue by jeffbski** [Reactive-Extensions/RxJS#625]
I believe I found a **race condition that can occur in a controlled observable** where the controlled observable will **lose a request and cause the system to hang** (since the request never gets handled so another one will be asked for).

The situation occurs when I **vary between requesting the next item synchronously vs asynchronously** (on next turn). I believe that if I stick to one or the other, it doesn't hit the race condition.

I can't figure out exactly what is causing the issue in the controlled observable code, but I think it **must be clearing out the requestedCount before it has been fulfilled**.

I would assume that it should be allowable to request another item synchronously or asynchronously in which case this feels like a defect in the controlled observable prototype. If not, then we at least need to update the docs indicating that you can't request in the same turn of the event loop.

**The following node.js code will reproduce the issue**. The example is a simple subject which produces 2 events every 100ms. The onNext handler simply logs these out, and alternates between requesting the next item synchronously vs asynchronously on the next turn of the event loop. The controlled observer is supposed to handle one item at a time, so once finished, request another one. The sync, async before making the request simulates doing some real work which varies between being synchronous and asynchronous which was my real use case.

The following node.js code reproduces the race condition and stops handling events after a few turns

```javascript
'use strict';

var Rx = require('rx');

var subject = new Rx.Subject();
var count = 0;
function createEvents() {
  subject.onNext(count++);
  subject.onNext(count++);
}
setInterval(createEvents, 100); // simulate endless events

var source = subject.timestamp().controlled();

// process one event at a time
var subscription = source.subscribe(
  function (x) {
    console.log(x.value + ': ' + x.timestamp);
    // alternate between immediate and delayed request(1), causes hanging
    if (x.value % 2) {
      console.log('immediate request');
      source.request(1); // request next
    } else {
      console.log('delayed request');
      setTimeout(function () {
        source.request(1); // request next
      }, 0);
    }
  },
  function (err) { console.error('err', err); },
  function () { console.log('completed'); }
);

source.request(1); // start by requesting first item
```

**Comment by jeffbski** [comment]
For convenience source and related docs for controlled observable:

 - https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/backpressure/controlled.js - source for controlled observable
 - https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/controlled.md - docs for controlled observable
 - https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/backpressure.md#controlled-observables - brief mention  about usage of controlled observable

**Comment by paulpdaniels** [comment]
One problem is that the source in src does not match the dist, this is my fault for not running the grunt concat-all before submitting the PR.  So if you are testing make sure to run the grunt concat before use.

More to your point it looks like the problem is coming in [here](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/backpressure/controlled.js#L101) because the system is requesting recursively, it seems that the requestedItems is getting reset on the way out, which is basically cutting off the sequence.

I will have a look at it later tonight, but it seems like this might be similar to #597.  Perhaps the controlled behavior should always be async to avoid this kind of recursion.

**Comment by jeffbski** [comment]
Thanks I appreciate you taking a look, let me know if you determine a way to fix it or whether we just need to call request asynchronously.

**Comment by mattpodwysocki** [comment]
@jeffbski any status on this issue?

**Comment by jeffbski** [comment]
@mattpodwysocki I just pulled the latest Rx from npm and it is still an issue. The above example blocks after a couple iterations. 

The work around is to delay the source.request(1) to the next turn of the event loop (nextTick), but it doesn't seem like that should really be necessary. 

If that is really the only way to fix, maybe that could be done inside of the implementation for `controlled` so that the user wouldn't have to know the restriction and get caught calling it wrong. It can take a while to figure out what caused the problem.

**Comment by paulpdaniels** [comment]
@jeffbski @mattpodwysocki - I have a fix locally on one of my machines, I just need to test it, I'll try and PR it soon.  Essentially though I am taking the same approach as suggested in #597 and adding an optional `scheduler` argument to `controlled()` which will  default to defaultScheduler or currentThreadScheduler, not sure which yet.  The former should fix this behavior though.

**Comment by jeffbski** [comment]
Thanks @mattpodwysocki and @paulpdaniels your PR indeed fixes the issue. I did have to do a grunt build to get the latest compiled files used for master (those must be updated separately?) but once I did that everything works like you expected (which is no surprise since you added a test as well). I assume that once a new version is uploaded for npm it will already have the compilation done.

**Comment by mattpodwysocki** [comment]
@jeffbski @paulpdaniels version 2.5.2 has been published

**Comment by jeffbski** [comment]
+1 thanks.

On Sat, Apr 11, 2015 at 1:11 PM, Matthew Podwysocki <
notifications@github.com> wrote:

> @jeffbski <https://github.com/jeffbski> @paulpdaniels
> <https://github.com/paulpdaniels> version 2.5.2 has been published
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Reactive-Extensions/RxJS/issues/625#issuecomment-91894246>
> .
>



-- 
Jeff Barczewski
Founder of CodeWinds
http://codewinds.com/
Web developer training - screencasts, podcast, blog
