### ISSUE TITLE
flatMapLatest example needs to provide more clarity

### ISSUE THREAD

**Issue by khoomeister** [Reactive-Extensions/RxJS#627]
The `flatMapLatest` [example code](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/flatmaplatest.md) is difficult to understand in terms of whether the numbers generated come from the outer observable or the `flatMapLatest` observable.

I played around with it for awhile, and the below tweaked example really cleared things up for me.  Perhaps it might help others to come to a quicker understanding of `flatMapLatest`.

```javascript
var source = Rx.Observable
  .range(1, 3)
  .flatMapLatest(function(x) {
    return Rx.Observable.from([x + 'a', x + 'b']);
  });

var subscription = source.subscribe(
  function (x) {
    console.log('Next: %s', x);
  },
  function (err) {
    console.log('Error: %s', err);
  },
  function () {
    console.log('Completed');
  });

// Next: 1a
// Next: 2a
// Next: 3a
// Next: 3b
// Completed
```

**Comment by mattpodwysocki** [comment]
@khoomeister that's fine, I can certainly change it for you to reflect that.

**Comment by GDoronin** [comment]
@khoomeister Your example is really more explanatory, and it helped at least one man already (i.e. me).

@mattpodwysocki It looked like a 5 minutes fix, fixed it while reading it. Hope you don't mind.

**Comment by mattpodwysocki** [comment]
@khoomeister are we good to close this then?

**Comment by khoomeister** [comment]
Yes, thanks @mattpodwysocki and @GDoronin :smiley:
