### ISSUE TITLE
Question about throttling and/or laziness with RxJs

### ISSUE THREAD

**Issue by darrencruse** [Reactive-Extensions/RxJS#628]
Apologize for posting here since this is really just a question but wasn't sure where to ask...

I've written a program to run over the files under a certain directory and identify any that are missing from our amazon s3 account.  My concern is we have 1.4TB of files in our S3 account so I'd like my RxJs pipeline to not load all the filenames into memory, and also not submit all these amazon S3 requests at the same time (and swamp our network!).

Below is the skeleton of some code I got working today (kind of trial and error I'm brand new to RxJs).  Can someone advize me is it possible for me to do the two things I mentioned above?  Make the retrieval of the filename's lazy so they're not all in memory (if it matters that "rx-directory" is an npm module that does a pretty straightforward tree walk and returns Rx.Observable.fromArray), and then also limit the number of concurrent "fs.exists" calls (i.e. what are really s3 "head" requests)?

The "merge" I put in trying to limit that concurrency based on a stackoverflow comment - but I couldn't see it was doing anything.

Again sorry to impose but really appreciate any help - if there was better place for me to ask this feel free to needle me. :)

```
var Rx = require("rx");
var rxDirectory = require("rx-directory");
var S3FS = require('s3fs');

var fs = new S3FS({ accessKeyId: 'XXXX', secretAccessKey: 'XXXX' }, 'mys3bucket');

rxDirectory.recursive(topDir)
.map(function (filename) {
    return new Promise(function (resolve, reject) {
      fs.exists(filename, function(exists) {
          resolve({ file: filename, exists: exists });
      });
    });
})
.merge(2)
.subscribe(function (fileInfo) {
  if(!fileInfo.exists) {
    console.log('Missing file:', fileInfo.file);
    totalMissing++;
  }
},
function (err) {
  console.log('Error: ' + err);
},
function () {
  console.log('\nMissing file check complete.');
});
```

**Comment by darrencruse** [comment]
just noticed this btw it was super helpful:  https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/backpressure.md

I truthfully didn't have my head straight about how Rx works when I started with it yesterday morning.
I think I'm understanding better now that there is no inherent laziness or pause/resume back-pressure kind of thing in what I've coded above.

Actually I just added some console.log's to try and educate myself better on how things work.  I can see the files are still being walked and interleaved with the "fs.exists" amazon s3 calls.  But surprising to me it looks like *all* amazon S3 calls get made before any respond and then all of them respond together at the end.  At which point the final "subscribe" is interleaved with the S3 responses coming in.

So I'm thinking my concerns over tons of memory used might have been unfounded - but maybe not my concerns over swamping the network with amazon S3 requests esp. if I run this over my entire 1.4TB directory tree!

I wonder if I could have structured this differently somehow to "serialize" the pipeline so it would have had to wait for the S3 response before starting with the next file.  i.e. no concurrent requests at all just doing one file at a time.

**Comment by darrencruse** [comment]
Hope I don't seem like a crazy person replying to my own messages... :)  But if anybody reads this I can mention I did get something partial working by switching to use "readdirp" which is a module that provides a pausable stream of the files beneath a directory.

This allowed me to control the "concurrency" i.e. limit the number of simultaneous requests I was sending to amazon S3.

The remaining problem - when I try and run this against my huge 1.4TB directory memory goes through the roof (almost like a memory leak it looks like it climbs without end so I'm having to kill it).

But if anybody's interested here's some code just giving the basic idea (omitted some things for brevity):
```
[...]
var readdirp = require('readdirp');

var outstandingRequests = 0;

var stream = readdirp({ root: topDir });
var subscription = Rx.Node.fromStream(stream)
.flatMap(function (fileinfo) {
    return new Promise(function (resolve, reject) {
      var filename = topDir + '/' + fileinfo.path;
      fsImpl.exists(filename, function(exists) {
        if(outstandingRequests > 0) {
          outstandingRequests--;
        }
        if(outstandingRequests < concurrency) {
          stream.resume();
        }
        resolve({ file: filename, exists: exists });
      });
      outstandingRequests++;
      if(outstandingRequests >= concurrency) {
        stream.pause();
      }
    });
})
.subscribe(function (fileInfo) {
  if(!fileInfo.exists) {
    console.log('Missing file:', fileInfo.file);
  }
},
[...]
```
Like I say it kind of works for what I need except for the memory usage.

If anybody knows why that might be happening greatly appreciate any suggestions....

**Comment by paulpdaniels** [comment]
One possibility for your unbounded growth (sorry I don't actually know how best to set up a test environment for this) is probably [here](https://nodejs.org/api/stream.html#stream_readable_pause).  Notice the line that says "any data that becomes available will remain in an internal buffer", your pausing will prevent additional downstream processing, but I think the readdirp is still chugging away behind the scenes, filling up the buffer with all the file names.

Also, have you tried just running the readdirp to see if the same issue pops up?  I haven't looked at the source, but if it was running a breadth first search of your drive that would certainly stack up (pun intended).

**Comment by paulpdaniels** [comment]
@darrencruse were you able to find the problem? Can this issue be closed?

**Comment by mattpodwysocki** [comment]
Closing due to lack of response
