### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by alanmoo** [Reactive-Extensions/RxJS#633]
Not sure if it's the same as https://github.com/Reactive-Extensions/RxJS/issues/621, but I'm having issues pulling this in again with the most recent change.

`Error: Cannot find module 'rx'`

**Comment by mattpodwysocki** [comment]
@alanmoo crap, what the hell is wrong with NPM?  It's done this twice now where nothing should have failed...  Unpublished...

**Comment by alanmoo** [comment]
Thanks so much. Not sure what's going on (or even what package I'm using that uses RX, so I couldn't figure out how to work around it). Your speediness is letting me go home on time on a Friday though, thanks.
