### ISSUE TITLE
Support for Union Type Return Values on Operators

### ISSUE THREAD

**Issue by jeffbcross** [Reactive-Extensions/RxJS#637]
I'm new to RxJS and Typescript, so there's a high probability that I'm Doing It Wrong™.

It seems like typescript definitions for operators, such as `flatMapLatest`, should support returning `Observable` of `TResult` or `TResult`.
For reference: https://github.com/Reactive-Extensions/RxJS/blob/a24b363491d96edfc6f271e3747effdfea26c76c/ts/rx-lite.d.ts#L372

This implementation would make the compiler complain:
```javascript
let observable:Rx.Observable<MyClass> = Rx.Observable.fromArray([myInstance]);
observable.flatMapLatest((o:MyClass):MyClass => {
  o.foo = 'bar';
  return o;
});
```

Compiler says: 

    Argument of type '(o: MyClass) => MyClass | Observable<MyClass>' is not assignable to parameter of type '(value: MyClass, index: number, source: Observable<MyClass>) => Observable<MyClass>'.                                     
    Type 'MyClass | Observable<MyClass>' is not assignable to type 'Observable<MyClass>'.
    Type 'MyClass' is not assignable to type 'Observable<MyClass>'.

If I change the definition file to add `TResult` as another acceptable return value, compiler is happy.

Happy to submit a PR if this is valid.

**Comment by Igorbek** [comment]
@jeffbcross `flatMapLatest` expects to get observable from selector function. Your usage seems to be applicable for `map`/`select` operator.

```ts
let observable:Rx.Observable<MyClass> = Rx.Observable.fromArray([myInstance]);
observable.select(o => {
  o.foo = 'bar';
  return o;
});
```

And, BTW, altering selectors are not a good practice. It's better to use `do`/`tap` operator for your example.

**Comment by jeffbcross** [comment]
Thanks for the feedback!

My example of directly manipulating the object was a bad one, and may distract from my point. It is actually immutable in my application, and I'm returning a new instance of the same type.

I'd used `flatMapLatest` in plain JavaScript prior to moving to TypeScript, and would return the unwrapped value without issue. I'm guessing Rx wraps it as an observable for me. Shouldn't the type definition reflect this?

**Comment by Igorbek** [comment]
It doesn't work: https://jsfiddle.net/8911fsdb/
It raises exception: [TypeError] undefined is not a function

**Comment by jeffbcross** [comment]
I stand corrected! My memory must've failed me; I should've been more diligent with a reproduction. Thanks for your help!
