### ISSUE TITLE
Proposal: move Node-specific operators to new rx.node.js library

### ISSUE THREAD

**Issue by staltz** [Reactive-Extensions/RxJS#639]
This issue is best explained by [an issue in React Native](https://github.com/facebook/react-native/issues/447). npm is not anymore a Node-only tool, it's also very important in the frontend world, so I suggest we separate Node-specific operators out of npm's `rx` module.

**Comment by mattpodwysocki** [comment]
@staltz yes, let's bump to 2.5 and move the Node.js specific stuff to rx-node, if that's not already taken...

**Comment by mattpodwysocki** [comment]
@staltz here are the beginnings of the library here at [`rx-node`](https://github.com/Reactive-Extensions/rx-node).  Will start removing the rest from `index.js` and move `pipe` into the main operators.

**Comment by staltz** [comment]
Looking great

**Comment by mattpodwysocki** [comment]
@staltz done as of v2.5.1

**Comment by staltz** [comment]
Perfect, confirmed it's working fine.
