### ISSUE TITLE
 Cannot use 'in' operator to search for 'WScript' in undefined

### ISSUE THREAD

**Issue by christyharagan** [Reactive-Extensions/RxJS#640]
I am using rxjs v2.4.7 and chrome 46 beta, and I get the error:

```
 Cannot use 'in' operator to search for 'WScript' in undefined
```

Coming from:
src/core/concurrency/defaultscheduler.js
at line 1262

The line reads:
```javascript
if ('WScript' in this) {
```

Upon inspection, this snippet comes from a function definition in which ```this``` can never be set:

```javascript
var localTimer = (function () {
  //
}());
```

However, I find it unbelievable that I'm the only one affected by this, so I fully accept I might be doing something stupid. 

My temporary fix is to change the line in question to:

```javascript
if (this && 'WScript' in this) {
```

**Comment by paulpdaniels** [comment]
Do you have some sample code to reproduce it?

**Comment by mattpodwysocki** [comment]
@christyharagan apologies for delay as I've been battling the good ol norovirus. This is now fixed.
