### ISSUE TITLE
ReactiveX??

### ISSUE THREAD

**Issue by ccorcos** [Reactive-Extensions/RxJS#641]
I decided to use Highlandjs in a project instead of RxJS because I couldnt find good documentation for this project. Then I ran across ReactiveX: http://reactivex.io/  

If this is the documentation, you should link to it from github readme and from the github pages website.

**Comment by mattpodwysocki** [comment]
@ccorcos ok, changed our site instead of the outdated GitHub pages to ReactiveX.  Just a question, was what was in the doc folder not enough to get started?

**Comment by ccorcos** [comment]
Its probably fine for reference. But I wasn't satisfied with browsing through it, learning about everything and seeing examples. Which is what I liked about highland.. I like docs pages like underscore, lodash, and meteor where its all there on one page. That said, the graphics and everything on ReactiveX are awesome. I just had no idea!

**Comment by mattpodwysocki** [comment]
@ccorcos well, I hope you'll give us another chance...

**Comment by ccorcos** [comment]
haha thats the plan! I'll keep you posted
