### ISSUE TITLE
Zip Variant -- parallel streams

### ISSUE THREAD

**Issue by ccorcos** [Reactive-Extensions/RxJS#642]
Is there some concept of parallel streams where you can get multiple arguments to your transform function?  e.g. `.map(function(a,b) { return [a+b, a*b]})`

I want to do something to the effect of:

```
A: -----1---------2---------------------3-----------4---------
B: ------------5--------6----------7------------------------8-
transform
C: ------1-----1--2-----2----------2----3-----------3-------3-
   ------x-----5--5-----6----------7----7-----------7-------8-
```

C is just an array of two values but can be thought of as two streams in parallel. I've found this useful especially when `b = a.map( ... ).switch()`.

**Comment by urmastalimaa** [comment]
The last two values for C should be `4-7` and `4-8`, but you have just described `combineLatest`.

**Comment by ccorcos** [comment]
thank you!
