### ISSUE TITLE
thisArg does not work for second chained filter

### ISSUE THREAD

**Issue by vaplat** [Reactive-Extensions/RxJS#643]
When chaining multiple filters for single observable thisArg does not work for second and subsequent one. Filter function is called with window as this.

**Comment by paulpdaniels** [comment]
There was a problem with the `this` binding in the FilterObservable.  I'll put together a PR for this, I'll need check the other operators as well, it looks like map is affected as well.

**Comment by vaplat** [comment]
Yes, in internalFilter function as it does not properly apply this in the anonymous function it creates.
I have monkey patched it locally.

**Comment by mattpodwysocki** [comment]
@vaplat this should be closed as per 2.4.8
