### ISSUE TITLE
Observable.fromCallback selector receives arguments object instead of individual arguments

### ISSUE THREAD

**Issue by mfellner** [Reactive-Extensions/RxJS#654]
I stumbled upon this issue while implementing my own version of `fromCallback` that doesn't call `onComplete` on the Observable.

If one creates an Observable from a callback that takes multiple arguments, the `selector` function will be called with the arguments wrapped in an arguments object, e.g.,
```javascript
{ '0': { '0': 'arg0', '1': 'arg1' } }
```
instead of with the individual arguments, e.g.,
```javascript
{ '0': '(2)', '1': 'arg2' }
```
This is because the `handler` function calls the `selector` by simply passing it the arguments object:
```javascript
function handler() {
    var results = arguments;

    if (selector) {
        try {
            results = selector(results);
        } catch (e) {
```
https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/fromcallback.js#L19

I think it would be better if the selector received the individual arguments, as would the callback. This could be done by using `apply`:
```javascript
function handler() {
    var results = arguments;

    if (selector) {
        try {
            results = selector.apply(context, results);
        } catch (e) {
```

**Comment by mattpodwysocki** [comment]
@mfellner fixed as per this build https://github.com/Reactive-Extensions/RxJS/commit/11029a42a89f9b2d86f217c9cfdae96184384619
