### ISSUE TITLE
rx.all.compat.js broken in IE8

### ISSUE THREAD

**Issue by mburnell** [Reactive-Extensions/RxJS#657]
Change 5761f5c056a2ab6253bd1da4481e67ea9f7d193a breaks IE8 (specifically, the Scheduler.default alias is not OK, as "default" is (mis)interpreted as a keyword. Was this alias accidentally included in the compatibility version?

**Comment by benjamingr** [comment]
@mburnell make a PR that puts it in bracket notation?

**Comment by mattpodwysocki** [comment]
@mburnell my mistake, fixed!

**Comment by mburnell** [comment]
@mattpodwysocki Thanks!
