### ISSUE TITLE
SingleAssignmentDisposable is actually SerialDisposable—why?

### ISSUE THREAD

**Issue by gaearon** [Reactive-Extensions/RxJS#658]
[Docs](https://github.com/Reactive-Extensions/RxJS/tree/master/doc/api/disposables) claim there to be several disposables:

* [SerialDisposable](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/disposables/serialdisposable.md)
* [SingleAssignmentDisposable](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/disposables/singleassignmentdisposable.md)

However, [the names in source are different](https://github.com/Reactive-Extensions/RxJS/tree/master/src/core/disposables).

It seems that  [booleandisposable.js](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/disposables/booleandisposable.js) is actually *both* `SerialDisposable` and `SingleAssignmentDisposable`:

```js
  var SingleAssignmentDisposable = Rx.SingleAssignmentDisposable = (function () {
    function BooleanDisposable () {
  
  ...

  var SerialDisposable = Rx.SerialDisposable = SingleAssignmentDisposable;
```

How is that possible? Judging by the docs, they should have *vastly* different semantics. (Single assignment disposable should throw if `setDisposable` is called twice.)

Both naming and this misbehavior is quite confusing, considering disposable are used throughout the library and are its essential part. Am I missing something?

**Comment by mattpodwysocki** [comment]
@gaearon you're not missing anything. It was cut for size purposes, not that any were misbehaving. Will fix over time

**Comment by gaearon** [comment]
Thanks for addressing so soon!
