### ISSUE TITLE
WithLatestFrom doesn't propagate unless all observables emit a value

### ISSUE THREAD

**Issue by Mosho1** [Reactive-Extensions/RxJS#659]
The `WithLatestFrom` documentation says:

>Merges the specified observable sequences into one observable sequence by using the selector function **only when the source observable sequence (the instance) produces an element**.

However, this isn't the case and if any of the observables provided as an argument haven't already produced at least one value, the new observable returned will not emit a value. I would expect some different behavior, perhaps `undefined` to be the argument the selector function is called with instead, as long as the respective observable is empty.

**Comment by mattpodwysocki** [comment]
@Mosho1 what is the use case for this particular case?

**Comment by Mosho1** [comment]
@mattpodwysocki My use case was a submission event for a search that I wanted to use to select the proper search term from either the search input or the currently focused element out of a drop down suggestion list. Something like:

    submitEvent.withLatestFrom(searchTerm, focused, function (a, b, c) {
		return c || b;
	})

I ended up using `startWith` though, which works just fine. If you don't feel this is the intended use perhaps updating the documentation to be clearer should be considered. If there is a more idiomatic way to produce the behavior I was looking for, I'd be happy to hear it.

**Comment by urmastalimaa** [comment]
It seems that you need to use either `merge` (or possibly `amb`) on the search input and suggestion list.

**Comment by mattpodwysocki** [comment]
@Mosho1 closing as `withLatestFrom` is not what you are looking for.  If you need other behavior, please suggest a new operator with the semantics you want
