### ISSUE TITLE
Behavior of scan with seed

### ISSUE THREAD

**Issue by menelaos** [Reactive-Extensions/RxJS#669]
I'm trying to use RxJS with React in the following way:

```javascript
let appState$ = actionStream$.scan(initialState, update);
appState$.subscribe(render);
```

A minimal working example:
```javascript
let clickStream$ = Rx.Observable.fromEvent(document, "click");
let myState$ = clickStream$.scan(0, (acc, e) => acc + 1);
myState$.subscribe(x => console.log(x));
```

I was under the impression that `myState$` should be outputting
`0` until the first click occurs, but unfortunately it doesn't.

Is this the intended behavior? Cf. `scanl` in Haskell:
```haskell
scanl (+) 0 [] == [0]
```

The following code is a workaround
```javascript
let appState$ = actionStream$.scan(initialState, update)
                             .startWith(initialState);
appState$.subscribe(render);
```
but specifying `initialState` twice seems redundant to me.

**Comment by paulpdaniels** [comment]
i think you are misunderstanding how scan works (for rx at least, no comment on Haskell). The seed is not a value that is actually propagated, it is just there to provide some initial state. You should get no values before first click, and then the first value you receive will be 1.

**Comment by urmastalimaa** [comment]
@menelaos You can also use `scan` without the initialState which removes the redundancy. 
You are correct that scan is different in Rx from haskell but that is due to the asynchronous nature of Rx.

**Comment by menelaos** [comment]
@urmastalimaa Thanks, didn't think of that. Why does the "asynchronous nature of Rx" implicate the current implementation of `scan`? Elm's [`foldp`](http://package.elm-lang.org/packages/elm-lang/core/1.1.0/Signal#foldp) e.g. chooses to emit the initialState from the beginning. Is there a certain use case that led to Rx's current design choice?

**Comment by urmastalimaa** [comment]
@menelaos 
To be honest I have no basis for that argument other than the behavior of the `reduce`-like operators. 
I personally like that the initialState is not emitted as it's not usually a value I'm interested in.

**Comment by mattpodwysocki** [comment]
@menelaos because we will not emit until we get a value from the source, unless the source is empty, therefore initialValue only matters if the sequence is empty or the basis of a computation.
