### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by gyzerok** [Reactive-Extensions/RxJS#670]
Using the following code I get memory leaks. What's the problem?

```javascript
var server = require('http').createServer(handler);
var io = require('socket.io')(server);
server.listen(1337, function () {
  console.log('API started on ' + 1337);
});

function handler(req: Object, res: Object): void {
  res.writeHead(200);
  res.end();
}

var Rx = require('rx');
var conns = Rx.Observable.create(observer => {
  io.on('connection', socket => observer.onNext(socket));
});

var mockedMovies = Rx.Observable
    .range(1, 10000)
    .map((x) => ({title: x}))
    .reduce((memo, x) => memo.concat(x), []);

var movieNames = mockedMovies
    .map(
      movies => movies.map(
        movie => movie.title
      )
    );

var suggestions = conns
  .flatMap(onSuggestions)
  .withLatestFrom(movieNames, combine);

suggestions.subscribeOnNext(send);

function onSuggestions(socket: any): Observable {
  return Rx.Observable.create(observer => {
    socket.on('suggestions', (ack) => observer.onNext(ack));
  });
}

function combine(cb: Function, data: Array<string>): Object {
  return { data: data, cb: cb };
}

function send({ data, cb }): void {
  cb(data);
}
```

In original code ```movies``` stream stands for database cache.

**Comment by urmastalimaa** [comment]
You have listener leaks in two places.
```js
io.on('connection', socket => observer.onNext(socket));
```
and
```js
socket.on('suggestions', (ack) => observer.onNext(ack));
```

You can use `Rx.Observable.fromEventEmitter` to create an `Observable` from `EventEmitter`.

**Comment by gyzerok** [comment]
@urmastalimaa there is no ```.fromEventEmitter``` method. Suppose you mention ```.fromEvent```. Using this method results in error.

```javascript
var conns = Rx.Observable.fromEvent(io, 'connection');
```
```
.../node_modules/rx/dist/rx.js:579
    throw e;
          ^
Error: No listener found
```

**Comment by urmastalimaa** [comment]
Okay, then the listener leaks do not matter at this moment. 
However whenever you are creating observables from `EventEmitter` type of objects you should ensure that the listeners are cleaned upon disposal.

Maybe you can provide a simpler reproduction. In your original code I believe that `db` is undefined.

**Comment by gyzerok** [comment]
@urmastalimaa 
I fixed server-side code. There is no db ofc.
Here is my client-side code for test purposes. I'm using pm2 to follow memory usage.
```html
<html>
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
</head>
<body>
  <script>
    var socket = io('http://127.0.0.1:1338');
    var interval = Math.floor(1000 * 60 / 1000);
    setInterval(function () {
      socket.emit('suggestions', function () {
        console.log('received');
      });
    }, interval);
  </script>
</body>
</html>
```

**Comment by gyzerok** [comment]
What I'm doing:
1. Run server under [pm2](https://www.npmjs.com/package/pm2)
2. Open 1 tab with client-side code
3. See the memory leaking away

**Comment by mattpodwysocki** [comment]
@gyzerok as socket.io does not expose an off method to remove event listeners, we have to do some manual coding here, unfortunately.  I don't know if this is correct, calling removeHandler to destroy the handler, but it might be...

Anyhow, what you're going to want to use is `Rx.Observable.fromEventPattern` which allows you to customize how you attach and detach events.  This also then shares the handler, so that every time the observable is used, the same handler will be used so there should be no memory leaks.

```js
var server = require('http').createServer(handler);
var io = require('socket.io')(server);
server.listen(1337, function () {
  console.log('API started on ' + 1337);
});

function handler(req, res) {
  res.writeHead(200);
  res.end();
}

function fromSocketEvent(io, event) {
  return Rx.Observable.fromEventPattern(
    function (h) { return io.on(event, h); },
    function (h, d) { d.removeListener(event, h); }
  )
}

var Rx = require('rx');
var conns = fromSocketEvent(io, 'connection');

var movies = Rx.Observable
    .range(1, 10000)
    .map(function (x) { return { title: x }; })
    .reduce(function (memo, x) { return memo.concat(x); }, []);

var movieNames = movies
  .map(function (movies) { return movies.map(function(movie) { return movie.title; }); })

var suggestions = conns
  .flatMap(onSuggestions)
  .withLatestFrom(movieNames, combine);

suggestions.subscribeOnNext(send);

function onSuggestions(socket) {
  return fromSocketEvent(socket, 'suggestions')
}

function combine(cb, data) {
  return { data: data, cb: cb };
}

function send(obj) {
  cb(obj.data);
}
```

**Comment by gyzerok** [comment]
@mattpodwysocki I do need listener on socket.io all the time my server lives. Thats why, I guess there is not necessary to provide any disposal logic. Memory still leaks with your solution.

**Comment by pozadi** [comment]
Perhaps this is observables you create in `onSuggestions` function? As far as I understand you create them for each client, but they all don't dispose correctly.

**Comment by gyzerok** [comment]
@pozadi yes you are right. I create them for all the client. 
**But** for testing purposes I run just one client.

P.S. Is this correct way to handle with this?
```javascript
function onSuggestions(socket: any): Observable {
  return Rx.Observable
    .create(observer => {
      socket.on('suggestions', (ack) => observer.onNext(ack));
      socket.on('disconnect', () => observer.onCompleted());
    });
}
```

**Comment by mattpodwysocki** [comment]
@gyzerok in a way, yes, but publish/refCount would be advisable here.

```js
function onSuggestions(socket: any): Observable {
  return Rx.Observable
    .create(observer => {
      socket.on('suggestions', (ack) => observer.onNext(ack));
      socket.on('error', (err) => observer.onNext(err));
      socket.on('disconnect', () => observer.onCompleted());
    }).share(); // equals publish().refCount()
}
```

**Comment by gyzerok** [comment]
@mattpodwysocki done with share, but still leaks.

In my opinion memory may leak because of cold observable behaviour. Since it remembers all the history, memory leaks. Am I right? If so, how can I fix it?

**Comment by gyzerok** [comment]
@mattpodwysocki after adding ```share``` in one more place I've fixed the leak (but not sure for 100%). Can you explain me the reason, please?

```javascript
var conns = Rx.Observable
  .fromEventPattern(
    function (h) { return io.on('connection', h); },
    function (h, d) { d.removeListener('connection', h); }
  )
  .share();
```

**Comment by gyzerok** [comment]
I dont know exactly but it look like its not RxJS issue. I have memory leak even with following code.

```javascript
var server = require('http').createServer(handler);
var io = require('socket.io')(server);
server.listen(1338, function () {
  console.log('API started on ' + 1338);
});

var fs = require('fs');
function handler(req: Object, res: Object): void {
  res.writeHead(200);
  res.write(fs.readFileSync(process.cwd() + '/test.html'));
  res.end();
}

io.on('connection', function (socket) {
  socket.on('suggestions', function (cb) {
    cb([]);
  });
});
```
```html
<html>
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
</head>
<body>
  <script>
    var socket = io('http://127.0.0.1:1338');
    var interval = Math.floor(1000 * 60 / 1000);
    setInterval(function () {
      socket.emit('suggestions', function () {
        console.log('received');
      });
    }, interval);
  </script>
</body>
</html>
```

**Comment by DetweilerRyan** [comment]
@gyzerok I believe you are correct that this memory leak is not an RxJS problem but is a problem with socket.io.  Instead of subscribing to the 'connection' event on the io object (which is simply provided for convenience in the socket.io api) subscribe to the 'connection event on the io.sockets object ( the default socket.io namespace)

```
var server = require('http').createServer(handler);
var io = require('socket.io')(server);

var Rx = require('rx')

var connectionStrm = Rx.Observable.fromEvent( io.sockets, 'connection' );
```



checkout the socket.io documentation here: http://socket.io/docs/rooms-and-namespaces/

**Comment by mattpodwysocki** [comment]
@gyzerok I think @DetweilerRyan nailed it here that it's not a leak with RxJS
