### ISSUE TITLE
proper use of fromEventPattern selector arg for Backbone Events

### ISSUE THREAD

**Issue by ChetHarrison** [Reactive-Extensions/RxJS#679]
Matt,

The signature for a Backbone event listener is

`Backbone.Events.on("foo", handler);`

and to fire an event you do a 

`Backbone.Events.trigger("foo", someDataToPassToListener);`

Events are extended on all of the BB "classes". I noticed that I needed to add a `selector` function to pull the `someDataToPassToListener` argument out of the event call (there is certainly more flexible logic that could be applied to the selector function). Is the right way to go about this or is this a hack?

```javascript
        this.observable =  Rx.Observable.fromEventPattern(
            handler => _this.on("all", handler),

            handler => _this.off("all", handler),

            // this is the "selector" argument. If present
            // this function is called with the event obj.
            // arguments passed in the trigger will be
            // available at index 1.
            args => args[1]
        );
```

I also noticed that all of the vender lib logic was yanked from `fromEventPattern` does that live somewhere else or is the current thought to just roll your own?

Thanks!

**Comment by mattpodwysocki** [comment]
@ChetHarrison you are correct that this is the most idiomatic way to map to Backbone events.  We yanked the whole third party stuff just because it became annoying as new libraries came along.  Instead, what we found is that a lot of libraries had `.on` and `.off` methods where we could easily wrap around that.

**Comment by ChetHarrison** [comment]
Yeah, I could see that coming. Thanks for all your amazing work on admin this repo!!!!

Chet Harrison
949 933 1307
