### ISSUE TITLE
perf bug: sample's implementation not reactive

### ISSUE THREAD

**Issue by lmeyerov** [Reactive-Extensions/RxJS#683]
I filed this last year and got into a big debate about this, but wanted to report that we got hit by it again. `Sample`, by default, uses `setInterval`. We use Rx all over our UI, and often throttle with sample. Because `sample` uses `setInterval`, our idle state is therefore not idling.

Example: http://jsfiddle.net/ed8g0ond/2/

If sample was reactive, it would be scalable. However, as the runtime cost is in the number of constructed sample instances, rather than event occurrences, it is bad for dynamic UIs.

**Comment by lmeyerov** [comment]
To give a feel for how this surfaces in practice:

1. With `sample` calls:

![image](https://cloud.githubusercontent.com/assets/4249447/7335177/9127c7d8-eb61-11e4-944b-7e627ba2815f.png)

2. With `sample` calls disabled:

![image](https://cloud.githubusercontent.com/assets/4249447/7335179/a6171108-eb61-11e4-9814-ff496d7e3646.png)

**Comment by lmeyerov** [comment]
Continuing my conversation with myself, `sample` => `throttleFirst` is close enough. Perhaps this should be a warning & recommendation in the docs until it gets fixed?

**Comment by paulpdaniels** [comment]
I dont understand the diagram, what is that showing?

**Comment by lmeyerov** [comment]
Each `.sample()` call added a `setInterval` poller. A full UI app will use it multiple times, meaning many concurrent `setInterval` loops. The result is that, even if no events are entering Rx, Rx is still calling a polling function every millisecond.

In contrast, `throttleFirst` is *not* implemented with a persistent `setInterval`, so it's safe to use. There is 0 idling cost when no external events are occurring.

**Comment by paulpdaniels** [comment]
Can't you just swap out the scheduler? Or use the sampler overload? Then you could just have just one timer and hook up all your samples to it.

**Comment by lmeyerov** [comment]
Our code worked around the bug; I filed the issue because it shouldn't have had to.

**Comment by paulpdaniels** [comment]
What is the alternative in this case? Timer based sampling requires some kind of polling, which throttle first does not, since you can't actually check if the current event is going to be the last of the period.

**Comment by paulpdaniels** [comment]
On second look, I take your point.  There may be a better way to do this, I need to run through the edge cases though too to make sure.

**Comment by paulpdaniels** [comment]
My findings on this have been twofold: 
1) There does not appear to be a way to fix this without changing the behavior of `sample()`
2) There appears to be a bug in the `sample()` implementation.

Consider for example the following code,

```javascript

var scheduler = new Rx.TestScheduler();

var xs = scheduler.createColdObservable(onNext(0, 1), onNext(20, 2), onNext(39, 3), 
onNext(40, 4), onCompleted(300));

var result = scheduler.startWithCreate(function() {
   return xs.sample(20, scheduler); 
});

//Next: 2
//Next: 4
//Completed

```

The expectation right now seems to be that the sample interval reports for the interval (i_start, i_start + length]. However in the case above we see that the first interval is actually [i_start, i_start + length], one tick larger than subsequent intervals. To enforce consistency, I would suggest that we change to [i_start, i_start + length), that is, the sampled element will actually be sampled from the prior interval, but released on the following tick. So in the above example we should actually see (1, 3, 4) since the second and fourth elements would now fall into the later intervals.

@mattpodwysocki Does that seem reasonable from your perspective? If so I can work up a PR for this.

**Comment by lmeyerov** [comment]
The main property I'm advocating is not to emit events when nothing is happening, and underneath, not to compute anything (so a reactive implementation).

I'd expect the behavior & impl to be roughly:

X.sample(y) = 
  1. On x, v := x. 
  2. On x, setTimeout y to emit v, unless already a pending timeout.

Is the current sample visibly emitting events even during long periods of inactivity?

**Comment by paulpdaniels** [comment]
We are on the same page on the reactivity front, my solution would work similarly to what you wrote.  However, it will change the behavior of `sample`. The primary change being that if you receive an event in the current tick, you cannot also schedule it for that tick. So in my above example, if you receive an event at 20 ticks (something that would currently make it into the first interval), it cannot be scheduled until the next tick (or in sample's case the next interval).
