### ISSUE TITLE
Error: Cannot find module './dist/rx'

### ISSUE THREAD

**Issue by jonahbron** [Reactive-Extensions/RxJS#684]
Using the latest version of RxJS (2.5.2), any attempt to require `rx` is met with this error:

Error: Cannot find module './dist/rx'

I see that `/dist/` does not exist in the installed NPM package.  Is it supposed to be?

**Comment by mattpodwysocki** [comment]
@jonahbron cannot reproduce.  Just installed Rx locally and it comes up fine.  You may have an issue with NPM.  What's your version of NPM?

**Comment by jonahbron** [comment]
Currently using 1.4.28. I'll try to update and install again.

**Comment by jonahbron** [comment]
It seems to have been an NPM issue. I updated (2.8.4), and now it works fine.  Thanks!

**Comment by philipgiuliani** [comment]
I'm having the same issue after including https://github.com/tusharmath/Multi-threaded-downloader into my project. Somebody has an idea how to fix this?
