### ISSUE TITLE
Why Subject don't have join method ?

### ISSUE THREAD

**Issue by winsonwq** [Reactive-Extensions/RxJS#685]
as titled. I tried to convert it to Observable object, the method is not there neither.

**Comment by paulpdaniels** [comment]
Which library are you using? rx.lite and rx do not provide it by default you need to include either rx.all or rx.coincidence.

**Comment by mattpodwysocki** [comment]
@winsonwq as @paulpdaniels stated, you need to pull in the right libraries in order for join to show up.
