### ISSUE TITLE
 Error: Cannot find module ./rx in <eval> at line number 125 at column number 6

### ISSUE THREAD

**Issue by gurusharma08** [Reactive-Extensions/RxJS#687]
hello iam using vertx container as iam running any part  of the program iam getting an error 
 Error: Cannot find module ./rx in <eval> at line number 125 at column number 6

As my code is as below:

var Rx = require("rx.vertx");

// Create an observable that is also an handler of async result
var observable = Rx.observableFuture();
observable.subscribe(
    function(server) {
        // Server is listening
    },
    function(err) {
        // Server could not start
    }
);

var server = vertx.createHttpServer({ "port":1234, "host":"localhost" });
server.listen(observable.toHandler());

**Comment by mattpodwysocki** [comment]
@gurusharma08 cannot reproduce
