### ISSUE TITLE
Rx Visualization

### ISSUE THREAD

**Issue by benjamingr** [Reactive-Extensions/RxJS#689]
Hey, I'm working on simple visualizations for various RxJS use cases for a presentation I'm giving in a few weeks.

I'd love ideas for use cases to demonstrate as well as to know if this sort of thing is something you'd like to incorporate to the learning process for RxJS in the future.

For example, here's one of the basic ones - [search-with-throttle](https://jsfiddle.net/y63p8b9b/embedded/result/)

**Comment by xgrommx** [comment]
Hello @benjamingr I think http://www.rxmarbles.com also a good visualizator =)

**Comment by mattpodwysocki** [comment]
@benjamingr have you seen [Rx-Visualization](http://jaredly.github.io/2015/03/06/visualizing-reactive-streams-hot-and-cold/) in visualizing hot and cold streams?  In terms of data analysis, we have examples of pulling data from Wikipedia in our examples folder.  Also, we have stock analysis where you can easily do graphical analysis on this.  Does that help?

**Comment by benjamingr** [comment]
Thanks to both of you - both are helpful. I've checked the example folder - I'll keep this issue open until the 17th if you don't mind in case someone else has some insight and then close it on the day of the presentation. Thanks again :)

**Comment by mattpodwysocki** [comment]
@benjamingr closing as per previous comment
