### ISSUE TITLE
Multiple observable onNext args.

### ISSUE THREAD

**Issue by aychtang** [Reactive-Extensions/RxJS#69]
Right now the onNext function seems to only pass one element into the observable sequence. Can/Should we be able to create sequences which provide multiple arguments upon subscription?

**Comment by blittle** [comment]
This can be easily solved with ES6 de-structuring of the single parameter: 
```javascript
myObj.getObservable()
  .subscribe(({req, res}) => {
    req.send();
  })
```

**Comment by ORESoftware** [comment]
@blittle ha, I think it's a good solution, but like that won't be confusing for both newbs and non-newbs alike

**Comment by cwharris** [comment]
@ORESoftware If you're using typescript, you could make it far less confusing.
