### ISSUE TITLE
flatMapLatest dispose

### ISSUE THREAD

**Issue by benjamingr** [Reactive-Extensions/RxJS#690]
Hey, I'm using RxJS on the client side and for a demo I want something similar to `flatMapLatest` only that it disposes observables that are no longer relevant.

For example, if I'm performing an AJAX request for a key-stream, I want to cancel all but the relevant request. What would be an elegant way to do this?

**Comment by paulpdaniels** [comment]
Looking at the implementation of `switch()` which underlies `flatMapLatest()` it already disposes (effectively cancelling) the previous subscription once the new observable comes in. Is that behavior not sufficient?

**Comment by benjamingr** [comment]
I initially assume this was so, I guess the problem I'm facing was because I returned a promise and promise coercion to observables is unaware of cancellation or abortion of the operation, perhaps observables created this way need a second parameter for disposing - for example


    .flatMapLatest(o => {
          return promiseSearch(o); // this will never work, also no dispose
    })


    .flatMapLatest(o => {
          var req = promiseSearch(o);
          return fromPromise(req , () => req.abort()); 
    })

Or something like that.

**Comment by urmastalimaa** [comment]
`flatMapLatest` disposes the listeners for the previous requests. 
This means that you won't get non-relevant values in the stream. 
To actually cancel the requests you need to provide some kind of canceling mechanism for your requests.

If your request is a promise with a `cancel` method then you could use something like this:
```js
function cancelablePromiseToObservable(promise){
  return Rx.Observable.fromPromise(promise)
    .finally(promise.cancel)
  });
}
```

**Comment by benjamingr** [comment]
Yes, this makes sense, I should have realized Rx would have no way to guess how this sort of disposing would work - especially since ES6 promises famously don't have any cancellation semantics.
