### ISSUE TITLE
Unexpected  behaviour

### ISSUE THREAD

**Issue by gyzerok** [Reactive-Extensions/RxJS#693]
The following to code blocks works similarly except code with Rx creates new mongo db connection pool for every request. For me its an unexpected behaviour. Am I wrong? What is the correct solution than?

I suppose that every time I query ```db$``` I get new ```mongo.connect``` call. But I dont want it. I just want to cache my db object and use it later.

```javascript
var Rx = require('rx');
var mongo = require('mongodb');
var config = require('./src/config');

var connect = Rx.Observable.fromNodeCallback(mongo.connect, mongo);
var db$ = connect(config.db.url);

function find() {
  var req$ = db$.flatMapLatest(function (db) {
    var collection = db.collection('collection');
    var cursor = collection.find({}, {title: 1});
    var query = Rx.Observable.fromNodeCallback(cursor.toArray, cursor);
    return query();
  });
  req$.subscribe(function (results) {
    console.log(results.length);
  });
}

setInterval(find, 1000);
```

```javascript
var mongo = require('mongodb');
var config = require('./src/config');

mongo.connect(config.db.url, function (err, db) {
  function find() {
    var collection = db.collection('collection');
    collection.find({}, {title: 1}).toArray(function (err, results) {
      console.log(results.length);
    });
  }

  setInterval(find, 1000);
});
```

**Comment by urmastalimaa** [comment]
Every `setInterval` invokes the `mongo.connect` again, 
because the database instance isn't stored in any way.

A simple fix is to avoid using `setInterval` and instead create the interval when a connection has been established:

```js
var req$ = db$
  .flatMapLatest(function (db) {
    return Rx.Observable.interval(1000)
      .map(function() { return db});
  }).flatMap(function (db) {
    var collection = db.collection('collection');  
    var cursor = collection.find({}, {title: 1});
    var query = Rx.Observable.fromNodeCallback(cursor.toArray, cursor);
    return query();
  });

req$.subscribe(function (results) {
  console.log(results.length);
});

```

**Comment by gyzerok** [comment]
@urmastalimaa thank you for your reply. This code is not my real code. I just simplify one for this issue.
In my real code there is no ```setInterval``` at all. There I have to query ```db$``` Observable in a callback for socket.io event.

**Comment by urmastalimaa** [comment]
If you can initiate the database connection beforehand, then you could do something like this:

```js
var connect = Rx.Observable.fromNodeCallback(mongo.connect, mongo);
var db$ = connect(config.db.url).replay(null, 1);
var connectionDisposable = db$.connect();

//...
db$.flatMapLatest ( function(db) {
//...
```

The `replay` operator allows replaying the items (in this case, the database connection) for new subscribers of the observable. 
It also captures side effects so that multiple subscribes do not cause multiple connections.

**Comment by gyzerok** [comment]
@urmastalimaa awesome! Does ```shareReplay``` method do the same?

**Comment by urmastalimaa** [comment]
`shareReplay` is implemented as `replay(...).refCount()`, so they are very similar. 
With `replay` you have to call `connect()` to start the subscription, while `shareReplay` automatically starts the subscription whenever the number of subscribes goes from 0 to 1.

**Comment by gyzerok** [comment]
Ok, huge thanks for your help. Suppose its not a RxJS bug, but rather my brains bug. Closed.
