### ISSUE TITLE
make dragndrop example work for a class not an ID.

### ISSUE THREAD

**Issue by laurencefass** [Reactive-Extensions/RxJS#694]
I'm trying to adapt the drag and drop to work for a class of divs not just an ID. 
https://github.com/Reactive-Extensions/RxJS/blob/master/examples/dragndrop/dragndrop.html

simple changes to give the div a class nor an ID dont work and i lose ability to drag the element

3 simple changes:

HTML line 7 i.e. \<div class="dragTarget">Drag Me!\</div>
CSS line 1 i.e. .dragTarget { style attributes unchanged }
JS line 4 i.e  var dragTarget = document.getElementsByClassName('dragTarget');

Im not skilled enough to know if this is a bug in RXJS or that the example is not generalised enough. The documentation on events suggests these changes should be sufficient.

**Comment by paulpdaniels** [comment]
My first guess would be that the events 'mouseup' and 'mousedown' are not supported on an HTMLCollection, which is what `getElementsByClassName()` returns.  You probably have to apply the observable to each item in the collection.

**Comment by laurencefass** [comment]
theres an example here: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/events.md. suggests maybe it should work:

var result = document.getElementById('result');
var sources = document.querySelectorAll('div');

var source = Rx.Observable.fromEvent(sources, 'click');

var subscription = source.subscribe(function (e) {
  result.innerHTML = e.clientX + ', ' + e.clientY;
});

**Comment by mattpodwysocki** [comment]
@laurencefass this was an easy fix as `getElementsByClassName` and `getElementsByTagName` return an `HTMLCollection` so we can detect this via `Object.prototype.toString.call(el) === '[object HTMLCollection]';`.

**Comment by laurencefass** [comment]
thanks matt, when you say 'easy fix' do you mean you have fixed Rx core and that the example above will now just work? or do you suggest i approach the solution an alternative way?
