### ISSUE TITLE
delayed range

### ISSUE THREAD

**Issue by laurencefass** [Reactive-Extensions/RxJS#697]
i want to create a range that delays its output. my common sense suggests this should be possible and its simple to understand but it doesnt work...

    var delay = Rx.Observable.range(1,10).delay(500);       

i found this example that does what i need but it looks really complicated. This second working implementation surely cant be the simplest way to push some simple numbers on a delay...

    var delay = Rx.Observable.empty().delay(500);
    var items = Rx.Observable.fromArray([1,2,3,4,5]).map(function (x) {
        return Rx.Observable.return(x).concat(delay);
    }).concatAll();

Question: What is the simplest implementation in RXJS?

Thanks

Laurence

PS: I really wish the first one worked, or an explanation why it doesnt would be great.

**Comment by laurencefass** [comment]
thanks this works 

i dont understand the  function(x, y) { return x; }) what is the purpose of y?

**Comment by urmastalimaa** [comment]
Zip takes a selector function, which combines the results of range and interval. If you only care about the values from range then the function I provided just returns the first argument.

**Comment by laurencefass** [comment]
im very grateful for your help. thank you.

**Comment by mattpodwysocki** [comment]
@laurencefass yes, @urmastalimaa has the right answer, although he could have shortened it a bit to the following because you don't have to declare y if you have no intention of using it:
```js
var source = Rx.Observable.range(0, 10).zip(Rx.Observable.interval(500), function(x) { return x; });
```

If you don't want the initial 500ms delay for the first item, you can user `timer` instead.
```js
var source = Rx.Observable.range(0, 10).zip(Rx.Observable.timer(0, 500), function (x) { return x; });
```

**Comment by paulpdaniels** [comment]
Realize this is closed, but I'll also point out that generateWithRelativeTime would also work in this scenario (more callbacks, single operator):

```javascript

var source = Rx.Observable.generateWithRelativeTime(
0,
function (x) { return x < 10; },
function (x) { return x + 1; },
Rx.helpers.identity,
function (x) { return 500; })

```
