### ISSUE TITLE
Broken Link Clean up

### ISSUE THREAD

**Issue by paulpdaniels** [Reactive-Extensions/RxJS#705]
I have notice a fair number of PRs that come in related to broken links. Is there any interest in a utility that we can drop into the grunt build that will detect and report broken doc links during the build?

Anybody have any recommendations? If not I was planning to give it a shot using a library like [marked](https://github.com/chjj/marked).

**Comment by mattpodwysocki** [comment]
@paulpdaniels well, it's either broken links or its related to copy/paste code.  Or a new operator is added and not the docs in all places.  If you have an idea how to fix that, I'm all ears!

**Comment by paulpdaniels** [comment]
@mattpodwysocki You are right there are several use cases, I was targeting the links as the low hanging fruit, since parsing the markdown and then checking if the path actually exists is relatively trivial. 

Operator misplacement would be the next target perhaps, since we could actively inspect either the build step or the directory structure to determine if operator files are missing.

Copy/Paste that would be more difficult, best you might be able to achieve is to interrogate the diff to and look for duplicate code sections and warn about them during the build, but I could see that getting annoying if that was the *intention*
