### ISSUE TITLE
Align bower.json with official spec

### ISSUE THREAD

**Issue by donaldpipowitch** [Reactive-Extensions/RxJS#724]
Some weeks ago the ambiguous `"main"` property in the `bower.json` was defined as an array of _"[unminified] entry-point files, one-per-filetype"_ (see [here](https://github.com/bower/bower.json-spec/pull/43)). That means: just _one_ `.js` file, no `.min.js` and no `.map`. The only file left would probably be `"dist/rx.js"`.

To support different builds of RxJS you would need to separate the builds into independent repositories similar to [lodash](https://github.com/lodash/lodash) and [lodash-compat](https://github.com/lodash/lodash-compat).
Or you choose similar solution to Angulars strategy: this repository could be used as it is, but _just_ for development and completely _without_ a published `bower.json`. Instead you would generated a dedicated repository prefixed with `bower-` for _every_ build. You could also use this "opportunity" to get rid of some bloat and just put some file into the repositories (- like [bower-angular](https://github.com/angular/bower-angular) just a `.js`, `.min.js`, `min.js.map`, maybe the `.d.ts`). bower-angular also includes an `index.js` in tandem with a `package.json` to support commonjs. If you want to do that, too, I would use `module-` or `package-` instead of `bower-` as a prefix. Currently files like `travis.sh` are included in the Bower package which aren't necessary.

**Comment by mattpodwysocki** [comment]
@donaldpipowitch I removed the .min and .map files from there to keep the main files only.  Is that good enough for now?

**Comment by donaldpipowitch** [comment]
It's okay. If you can I would also reduce the array to just `"dist/rx.js"`.

**Comment by mattpodwysocki** [comment]
@donaldpipowitch what is the advantage of only shipping a single file when we have multiple files we care about?

**Comment by donaldpipowitch** [comment]
No "big" advantage, just convention of the spec. If a user cares about multiple files the user needs to depend on multiple modules. This is how the spec is defined. (To be honest I can see advantages in this approach, but didn't vote for it.)

**Comment by mattpodwysocki** [comment]
@donaldpipowitch closing for now unless there is a real need for `rx.all.js` to be the only main file

**Comment by donaldpipowitch** [comment]
Well, the need is there if you use tools like https://github.com/taptapship/wiredep. Think of it that way: the `package.json` only exports one file, too.

**Comment by mattpodwysocki** [comment]
@donaldpipowitch fair enough I'll reopen then and fix it

**Comment by donaldpipowitch** [comment]
Thank you.
