### ISSUE TITLE
Implemented 'waterfall' method from async.js

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#73]
How can I implemented 'waterfall' method from async.js in Rx?

**Comment by frankbenoit** [comment]
1. @mattpodwysocki  the async.js mapping link from above is dead, can you please update?
2. Can this be added to the library?
3. the closing of 'defer' is missing a ');'

**Comment by xgrommx** [comment]
Please https://github.com/Reactive-Extensions/RxJS/blob/master/doc/mapping/async/comparing.md#asyncwaterfall @frankbenoit
