### ISSUE TITLE
Add combineTemplate to RxJS core

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/RxJS#731]
Any opinion on adding `combineTemplate` from [here](https://github.com/ahomu/rx.observable.combinetemplate) which is a mirror of bacon.js's [`combineTemplate`](https://github.com/baconjs/bacon.js/#bacon-combinetemplate)?

**Comment by staltz** [comment]
I'd prefer to avoid Rx from becoming some form of lo-dash jungle: lots of operators to learn, but most of them are simple shortcuts to bring 5% (negligible) increase in productivity, but add a lot more API noise and make the learning curve worse. Seems like one can use combineLatest easily for this use case. It has a bit more boilerplate, but read above what I said.

```js
var password$, username$, firstname$, lastname$; // <- Observables
var loginInfo$ = Rx.Observable.combineLatest(
  password$, username$, firstname$, lastname$,
  (password, username, firstname, lastname) =>
  ({
    magicNumber: 3,
    userid: username,
    passwd: password,
    name: { first: firstname, last: lastname }
  })
);
```

**Comment by ericponto** [comment]
I find my main use case of `combineLatest` is exactly what `combineTemplate` brings. So I would be in favor of adding it. I think it could stay out of rx.lite and be in one of the add on type of packages to avoid some of that API noise @staltz mentioned.
