### ISSUE TITLE
Add flatMapFirst to RxJS core

### ISSUE THREAD

**Issue by boccob** [Reactive-Extensions/RxJS#732]
Does it make sense to add `flatMapFirst` that is analog of `flatMap` which adds new observable only if the previous one ended?
It already exists in bacon - [flatMapFirst](https://baconjs.github.io/api.html#observable-flatmapfirst)
And in kefir - [flatMapFirst](https://rpominov.github.io/kefir/#flat-map-first).
And there is no obvious way to do the same in RxJS without creating new function and without adding new variables with current state of mapped observable.

I already added it to a project on which I work at the moment and I can do a pull request.

**Comment by urmastalimaa** [comment]
How would `flatMapFirst` be different from `concatMap`?

**Comment by boccob** [comment]
With `flatMapFirst` value from initial observable will not be mapped to result observable if the previous one is not ended.
Example:
```
Source:     ------1----2----3x
Spawned 1:        -------1x
Spawned 2:             -------2x
Spawned 3:                  -------3x
Result:     -------------1---------3x
```
And `Spawned 2` will not be created because `Spawned 1` is not completed when `2` appeared in `Source`.

Actually I had case when I needed to create new request for each click on element. And I didn't want to create new requests while I didn't get response. Simplified example here: http://jsbin.com/noquqa/2/edit?js,console,output

**Comment by bman654** [comment]
It already exists (undocumented) as [exclusive](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/exclusive.js) and [exclusiveMap](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/exclusivemap.js).

**Comment by boccob** [comment]
Thank you!
Does it make sense to add documentation and tests for it?

**Comment by boccob** [comment]
Actually I found that there is another issue about documentation for this methods. So I'm closing this issue.
