### ISSUE TITLE
Per-method NPM packages

### ISSUE THREAD

**Issue by aldendaniels** [Reactive-Extensions/RxJS#733]
Lodash has started publishing [per-method NPM packages](https://www.npmjs.com/browse/keyword/lodash-modularized). This makes it very easy for NPM users to pick and choose exactly what they need without doing custom builds. Would this same approach make sense for RxJS?

**Comment by mattpodwysocki** [comment]
@aldendaniels it could and we're getting there with the modules approach for 3.x

**Comment by aldendaniels** [comment]
Thanks for the heads up! Very cool.
