### ISSUE TITLE
concatAll does not support promises

### ISSUE THREAD

**Issue by miracle2k** [Reactive-Extensions/RxJS#742]
Wanted to do this:
    
    CART = new Rx.BehaviorSubject(contents);
    CART.concatAll().subscribe(function(v) {
       console.log('new cart', v);
    });

    CART.onNext(fetch());

This will raise an exception:

    Uncaught TypeError: a.subscribe is not a function
    a.handleSubscribe @ rx.lite.js:2829

**Comment by miracle2k** [comment]
I think I misunderstand this.

    CART.concatAll().subscribe()
    CART.onNext(1)

triggers the error as well.

I am trying to use concatAll because a simple ``CART.subscribe()`` does not resolve the promise.

What I actually want to do is ensure that the promises are resolved in the right order.

**Comment by miracle2k** [comment]
I understand better now; ``concatAll`` isn't as magical as I imagined, and strictly expects a sequence of sequences.

I can make this work now using exactly that approach (each item added to CART is a sequence), but it complicates the code quite a bit. I didn't find a way a different way to make RxJS ensure that the promises are resolved.

**Comment by erykpiast** [comment]
So, basically you want to start fetching data when final Observable is subscribed?

**Comment by miracle2k** [comment]
Basically what I want is fire off a bunch of XHR requests and get the results in order.

I wanted to combine this with a subject so that I could have one variable that I can both subscribe to, and use ``getValue()`` to fetch the last server response.

I mistakingly assumed that the subject class would handle these promises for me transparently.

I am now doing this:

      request = new Rx.BehaviourSubject('default');
      request_in = new Rx.Subject();
      request_in.concatAll().subscribe(request);

      // access the current request
      request.getValue()
      // subscribe to requests
      request.subscribe()
   
      // queue up a request
      request_in.onNext(promise)

This is straightforward enough, though of course I would prefer a single variable.
