### ISSUE TITLE
Memory leak from usual drag-and-drop example

### ISSUE THREAD

**Issue by heycalmdown** [Reactive-Extensions/RxJS#744]
I'm very newbie who is following typical RxJS examples. I think I am doing wrong with composting `Observable`s, but couldn't figure out exactly what is a missing piece. So let me show you folks simple drag-and-drop example I made:

```javascript
        var mouseup = Rx.Observable.fromEvent(dragTarget, 'mouseup');
        var mousemove = Rx.Observable.fromEvent(document, 'mousemove');
        var mousedown = Rx.Observable.fromEvent(dragTarget, 'mousedown');

        var mousedrag = mousedown.flatMap(function (md) {
            var startX = md.offsetX, startY = md.offsetY;
            return mousemove.map(function (mm) {
                return {
                    left: mm.clientX - startX,
                    top: mm.clientY - startY
                };
            }).takeUntil(mouseup);
        });
        subscription = mousedrag.subscribe(function (pos) {
            dragTarget.style.top = pos.top + 'px';
            dragTarget.style.left = pos.left + 'px';
        });

        Rx.Observable.fromEvent(document.getElementById('btn'), 'click')
          .take(1).subscribe(function () {
            this.dispose();
            subscription.dispose();
            document.getElementById('container1')
              .removeChild(document.getElementById('container2'));
          });
```

http://jsfiddle.net/heycalmdown/aqwtyc62/1/
https://jsfiddle.net/heycalmdown/aqwtyc62/1/embedded/result/

The page shows you an image which you can drag-and-drop and there is a tiny button under the image to remove a container `div` from its parent. It's usual behavior in SPA.
So, I'd like to clear all listeners before detach a DOM tree.

When I checked with the profiler from the Chrome Dev Tools, I can see three types of the `Observable`s.

* AnonymouseObservable 12
* ConnectableObservable 4
* MapObservable 1

After removing the DOM tree, I got

* AnonymouseObservable 6
* ConnectableObservable 2
* MapObservable 0

How or when can I have a chance to dipose rest of the `Observable`s?

**Comment by heycalmdown** [comment]
any ideas?

**Comment by heycalmdown** [comment]
hello, anyone?

**Comment by paulpdaniels** [comment]
does it stack? as in does the leak grow if its repeated?

**Comment by heycalmdown** [comment]
https://jsfiddle.net/heycalmdown/gmta61be/1/
https://jsfiddle.net/heycalmdown/gmta61be/1/embedded/result/

* AnonymousObservable 18
* ConnectableObservable 6
* MapObservable 2

After removing the DOM tree and gc,

* AnonymousObservable 9
* ConnectableObservable 3

It's obvious, I think.

**Comment by paulpdaniels** [comment]
Those `Observables` appear to be the ones that you declare, they are hanging around because you never null them out.

**Comment by heycalmdown** [comment]
You genius! (Sorry I was stupid)

Thanks!
