### ISSUE TITLE
Hard case for using RxJS?

### ISSUE THREAD

**Issue by heycalmdown** [Reactive-Extensions/RxJS#748]
I am studying Rx these days. So it's not weird I'm in phase of considering Rx for every issue which I am struggling. 

Here is a stream of event that messages come in. The gap between messages is unpredictable. A message need to be popped up to the user for 3 seconds unless no following message. If there is a following message, then the life of a message guaranteed only one second.

I could chain the `throttle` and the `concatMap` things, but I can't find how can l model it to cancel 3 seconds life by a following message. Wouldn't it be the right tool for this case?

**Comment by paulpdaniels** [comment]
I am not sure I fully understand what you are looking for, could you write out an example of the behavior you are expecting or a JSFiddle with what you have tried vs the expected output?

**Comment by heycalmdown** [comment]
https://jsfiddle.net/heycalmdown/v8q6ywL8/

Could it be helped?

**Comment by paulpdaniels** [comment]
@heycalmdown 
See my modified [solution](https://jsfiddle.net/m4Lwxj3e/1/).

Note: This is the minimum working system. If you are using angular for more than just demo purposes you should use [rx.angular](https://github.com/Reactive-Extensions/rx.angular.js), which has schedulers already adapted for the angular use case so you should not need any `$apply` calls.

**Comment by heycalmdown** [comment]
The `regulate` slows down whenever event comes in at least given interval value, right? Nice! Is it known pattern in Rx community? Why isn't it provided as default?

And using of `flatMapLatest` to cancel a previous one immediately is also nice solution.

Works like a magic! Thanks!

**Comment by paulpdaniels** [comment]
Correct, `regulate` allows a maximum throughput of 1 item/interval but it doesn't drop the extra messages on the floor like throttle or debounce. Backpressure is a known pattern within RxJS, but this specific use of it with `regulate` I have not seen before. So it may be a candidate for inclusion, but I don't think there has been a lot of demand for it in the past.

**Comment by heycalmdown** [comment]
I think it'd be used for ticker messages which guarantee its own time for people noticed but not so long like a stock market's.

Anyway I can close this issue. Thanks.
