### ISSUE TITLE
Rxjs swallows errors

### ISSUE THREAD

**Issue by aleclofabbro** [Reactive-Extensions/RxJS#759]
Having a simple `Rxjs` stream, i faced this situation:

    Rx.Observable
      .fromArray([1,2,3,4,5,6])
    // if commented from here 
      .windowWithCount(2, 1)
      .selectMany(function(x) {
        return x.toArray();
      })
    // to here .. the error bubbles up
      .subscribe(function(x) {
        console.log('x:',x)
        throw new Error("AAHAAHHAHA!");  
      });

with the `windowWithCount + selectMany` the error is silently catched internally and isn't catchable and it isn't notified in console neither 

commenting those 2 blocks the error is notified on console at least  
I don't think this is supposed to be, or am i missing something?  
[here the jsbin](http://jsbin.com/gujuyadesa/2/edit?js,console)
[SO](http://stackoverflow.com/questions/30736561/rxjs-swallows-errors)

**Comment by mattpodwysocki** [comment]
@aleclofabbro That is an old bug which has long since been fixed.  Please upgrade to the latest RxJS, as your version of 2.2.28 is rather old.

**Comment by aleclofabbro** [comment]
oh! yah!
V2.5.2 is ok!
Sorry, Matt!

**Comment by filipmares** [comment]
i'm still seeing this issue with 4.0.6.

**Comment by slorber** [comment]
@filipmares @mattpodwysocki I have the same problem (with 3.1.1 and 4.0.7)

I've had this problem with:

```
        source.subscribe(function (data) {
            if (data.status === UPLOAD_STATUS.LOAD) {
                    this.addAttachments(data.response);
            }
        }.bind(this));
```


But the following solves my problem and I get the error logged:

```
        source.subscribe(function (data) {
            if (data.status === UPLOAD_STATUS.LOAD) {
                setTimeout(function() {
                    this.addAttachments(data.response);
                }.bind(this),0);
            }
        }.bind(this));
```


I'd rather have this error bubble up to the top and logged natively because when using console.error it can mess up with sourcemaps. (see https://github.com/webpack/webpack/issues/1646)

**Comment by slorber** [comment]
Actually I was wrong it seems to work fine @mattpodwysocki 

The problem was that we were using Q on the production side:

```
        this.uploadFile(fileId, fileContent, onProgress, onAbort, onError)
            .then(function (response) {
                var updatedStreamData = self.updateStreamData(file, UPLOAD_STATUS.LOAD, 100, response);
                subject.onNext(updatedStreamData);
                subject.onCompleted();
            }, function (e) {
                var updatedStreamData = self.updateStreamData(file, UPLOAD_STATUS.ERROR, 100);
                subject.onNext(updatedStreamData);
                subject.onError(e);
            });
```

RxJs correctly throw the error synchronously when calling `onNext`, but it's actually Q that swallows that error because the dev forgot to call `.done();`
