### ISSUE TITLE
ReactiveTest.onNext(200, function (x) { return x.length == 2; }); dose not work in real example.

### ISSUE THREAD

**Issue by rovqapint** [Reactive-Extensions/RxJS#762]
Predicate is not called and test is failed. Rx.internals.isEqual does not use predicate during executing.

**Comment by paulpdaniels** [comment]
I don't believe it is supposed to.  See the documentation for [ReactiveAssert](https://github.com/Reactive-Extensions/RxJS/blob/master/tests/helpers/reactiveassert.js#L32) helper methods.

**Comment by mattpodwysocki** [comment]
@paulpdaniels is correct here, you have to fix that for yourself for any assertion helper you are trying to use.
