### ISSUE TITLE
Simplifying the Plan type

### ISSUE THREAD

**Issue by Davidhanson90** [Reactive-Extensions/RxJS#772]
Hey all, 

I am just wondering what people think of the following.  I have working version in our app and its something I find devs new to rx struggle with.  

Basically when using Patterns, Plans and When you write code like this.

```javascript
var observable1 = foo.getDataAsync('foo');
var observable2 = foo.getDataAsync('bar');

var fooBar = observable1.and(observable2).thenBy((foo, bar) => {
       foo: foo,
       bar: bar
});
```

At this point devs normally get confused as they then need to know about the Observable.When

```javascript
Rx.Observable.When(fooBar).Subscribe();
```

I am just wondering a couple of things, firstly the use of thenBy seems like it could have been called select as it performs the same function. Secondly the disconnect between the Plan and the subscription of the plan seems unnecessary. 

In our monkey patched plan object we can now write this which I feel leads the developer on the right path.

```javascript
var observable1 = foo.getDataAsync('foo');
var observable2 = foo.getDataAsync('bar');

observable1.and(observable2).select((foo, bar) => {
       foo: foo,
       bar: bar
})
.where(foobar => foobar.foo == "foo")
.subscribe();
```
Any thoughts on why RX breaks these apart and uses different naming?

**Comment by xgrommx** [comment]
@Davidhanson90 As you know ```select``` is an alias for ```map```. It's reserved word. Maybe do you mean that ```and``` of Rx should be have a behavior like a ```Bacon.Observable.prototype.and```?

**Comment by Davidhanson90** [comment]
Yes I used select as been doing rx for like 8 years so old habits die hard. But you're correct map could and some would argue should be used. :) 

I looked for info on Bacon.Observable.prototype.and but couldn't find it. Does the and operator return an observable then? Or does it used patterns and plans? 

My main point, in case it's not clear is that the and operator could be like any other operator on the observable prototype, returning a new observable rather than a pattern.

**Comment by xgrommx** [comment]
I talk about http://baconjs.github.io/api.html#property-and. And interesting exists in Rx similar an operator?

**Comment by Davidhanson90** [comment]
Yes combineLatest will do the same, for readability though I think the "and" operator is better. 

Obs1.and(obs2).and(obs3).

**Comment by Davidhanson90** [comment]
The and operator already exists you see but it's not an observable you get back. Is a pattern which is the root of my question

**Comment by xgrommx** [comment]
I know about ```and``` operator. I created an alternative for ```Bacon.update``` use ```Rx.Observable.when``` https://github.com/xgrommx/react-rx-flux/blob/master/src/store.js#L7 which can be use so https://github.com/xgrommx/react-rx-flux/blob/master/src/store.js#L48 (This is my experiment for Flux)

**Comment by Davidhanson90** [comment]
I'm not sure what you're telling me. I know about observable.when too. I'm trying to find out why "and", "when", "then" exist on their own and are disconnected from the core observable operator approach whereby the operator returns a new observable.

**Comment by mattpodwysocki** [comment]
@Davidhanson90 it's pretty clear why we do this is because this is only for join patterns.  If you want anything more than that, I think `combineLatest` is the right answer for you.

The right use case for join patterns is the following:
```js
let source = Rx.Observable.when(
  obs1.and(obs2).thenDo((o1, o2) => o1 + o2),
  obs2.and(obs3).thenDo((o2, o3) => o2 + o3),
  obs4.thenDo((o4) => o4)
);

source.subscribe((x) => ... );
```

If you're not using it this way, then it's most likely using the wrong operator here.  This does not differ in any way from the Reactive Extensions for .NET [Join Patterns](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable.Joins.cs).
