### ISSUE TITLE
Mistaken link 

### ISSUE THREAD

**Issue by cefn** [Reactive-Extensions/RxJS#776]
In the documentation at...
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/promises.md
...there is a mistaken link from 'toPromise' to the 'fromPromise' documentation.

**Comment by mattpodwysocki** [comment]
@cefn fixed

**Comment by cefn** [comment]
This now points to [https://github.com/Reactive-Extensions/RxJS/tree/master/doc/api/core/operators/topromise.md](https://github.com/Reactive-Extensions/RxJS/tree/master/doc/api/core/operators/topromise.md) which doesn't exist. Is that right?

**Comment by xgrommx** [comment]
@cefn ```toPromise``` is a method of instance ```Rx.Observable``` http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/topromise.html but ```fromPromise``` is a static method http://xgrommx.github.io/rx-book/content/observable/observable_methods/frompromise.html

**Comment by mattpodwysocki** [comment]
@cefn woops, realized the doc was indeed not there.  Fixed!
