### ISSUE TITLE
ng-link directive does is not affected by digest call

### ISSUE THREAD

**Issue by maciossek** [Reactive-Extensions/RxJS#777]
`ng-link="app.toolassembly({ id: {{buttonOverviewCtrl.currentToolAssemblyId}} })"` is correctly rendered in html, but ng-link does not seem to be updated after `currentToolAssemblyId` changes.

**Comment by xgrommx** [comment]
How this problem related with Rx?

**Comment by mattpodwysocki** [comment]
@maciossek I'm not sure how this relates to RxJS

**Comment by maciossek** [comment]
jeez, wrong github project. Sorry guys.
