### ISSUE TITLE
docs: add example to flatMap using resultSelector to inject data from previous observables

### ISSUE THREAD

**Issue by BerkeleyTrue** [Reactive-Extensions/RxJS#780]
cc @mattpodwysocki

**Comment by paulpdaniels** [comment]
There is one on this [page](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/selectmany.md)

**Comment by mattpodwysocki** [comment]
@BerkeleyTrue then I guess we can close the issue since it is indeed there

**Comment by BerkeleyTrue** [comment]
The discussion on the Gitter was whether it is possible to insert variables from observables down the chain that are used earlier in the chain.

currently I'm doing this:
```js
var storyCount = dbObservable
  .flatMap(function(db) {
    return createQuery(db, 'stories', {});
  })
  .bufferWithCount(20)
  .withLatestFrom(dbObservable, function(stories, db) {
    return {
      stories: stories,
      db: db
    };
  })
  .flatMap(function(dats) {
    return insertMany(dats.db, 'story', dats.stories, { w: 1 });
  })
  .count();
```

@mattpodwysocki Alluded that it was possible to use the results selector to do this. What I imagined was something like this:

```js
var storyCount = dbObservable
  .flatMap(
    function(db) {
      return createQuery(db, 'stories', {}).bufferWithCount(20);
    },
    function(db, stories) {
      return insertMany(dats.db, 'story', dats.stories, { w: 1 });
    }
  )
  .count();
```

of course the other option is do to this: 
```js
var commentCount = dbObservable
  .flatMap(function(db) {
    return createQuery(db, 'comments', {})
      .bufferWithCount(20)
      .flatMap(function(comments) {
        return insertMany(db, 'comment', comments, { w: 1 });
      });
  })
  .count();
```
Which is a valid option but I prefer keeping the indenting down to a minimum and not rely on closures if possible. Looking at the source though it appears that the result selector is just a [pure function](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/selectmany.js#L38) used in a map operation and the second example here would not be possible.

**Comment by paulpdaniels** [comment]
@BerkeleyTrue You are correct it is just a pure function.

You could do your first way avoiding nesting by adding `mergeAll` before count

```javascript
var storyCount = dbObservable
  .flatMap(
    function(db) {
      return createQuery(db, 'stories, {}).bufferWithCount(20);
    },
    function(db, stories) {
      return insertMany(dats.db, 'story', dats.stories, {w : 1});
    })
    .mergeAll()
    .count();
```

**Comment by BerkeleyTrue** [comment]
Sweet. Hadn't thought about that. @paulpdaniels Thanks!
