### ISSUE TITLE
There is no chance to run RxJS code inside the Worker

### ISSUE THREAD

**Issue by Neurostep** [Reactive-Extensions/RxJS#781]
Hi all,

I've just found that related to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) inside WebWorker we have another global (root) object called `self`. Maybe we should add this to the [root](https://github.com/Reactive-Extensions/RxJS/blob/master/dist/rx.lite.js#L14) definition? Thoughts?

Thank you!

**Comment by mattpodwysocki** [comment]
@Neurostep should be fixed now with adding a `freeSelf` check which should set the `root` properly.

**Comment by Neurostep** [comment]
@mattpodwysocki that's great! Thank you so much!
