### ISSUE TITLE
Missing docs for `exclusive` and `exclusiveMap`

### ISSUE THREAD

**Issue by paulpdaniels** [Reactive-Extensions/RxJS#783]
Operators exist, but we need put together some documentation for them.

**Comment by xgrommx** [comment]
@paulpdaniels I started working on =) http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/exclusive.html and http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/exclusivemap.html
