### ISSUE TITLE
Doc incorrect for distinct operator

### ISSUE THREAD

**Issue by cboden** [Reactive-Extensions/RxJS#784]
The documentation for the [distinct operator](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/distinct.md) lists it as being included in [`rx.lite.js`](https://github.com/Reactive-Extensions/RxJS/blob/master/dist/rx.lite.js) but it is not included in the build.

**Comment by mattpodwysocki** [comment]
@cboden fixed.  Should be in `rx.lite.extras.js` and `rx.lite.extras.compat.js`
