### ISSUE TITLE
Rx.Observable.prototype.pipe not available from required module

### ISSUE THREAD

**Issue by ajcrites** [Reactive-Extensions/RxJS#785]
After installing via `npm install rx`

    Rx = require("rx");
    console.log(Rx.Observable.prototype.pipe); // undefined
    Rx.Observable.of(1, 2, 3).pipe(process.stdout); // undefined is not a function

It seems like `'src/core/linq/observable/pipe.js'` is not included when `dist/rx.backpressure.js` is built.

**Comment by mattpodwysocki** [comment]
@ajcrites closing as per merged PR
