### ISSUE TITLE
v2.5.3 unavailable on bower

### ISSUE THREAD

**Issue by cboden** [Reactive-Extensions/RxJS#790]
`bower install rxjs#2.5.3`

> bower rxjs#2.5.3            not-cached git://github.com/Reactive-Extensions/RxJS.git#2.5.3
bower rxjs#2.5.3               resolve git://github.com/Reactive-Extensions/RxJS.git#2.5.3
bower rxjs#~2.5.3           not-cached git://github.com/Reactive-Extensions/RxJS.git#~2.5.3
bower rxjs#~2.5.3              resolve git://github.com/Reactive-Extensions/RxJS.git#~2.5.3
bower rxjs#~2.5.3         ENORESTARGET No tag found that was able to satisfy ~2.5.3
Additional error details:
Available versions: 2.5.2, 2.5.1, 2.5.0, 2.4.10, 2.4.9, 2.4.8, 2.4.7, 2.4.6, 2.4.5, 2.4.4, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.25, 2.3.24, 2.3.23, 2.3.22, 2.3.21, 2.3.20, 2.3.19, 2.3.18, 2.3.16, 2.3.14, 2.3.13, 2.3.12, 2.3.11, 2.3.10, 2.3.9, 2.3.8, 2.3.7, 2.3.6, 2.3.5, 2.3.4, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.28, 2.2.27, 2.2.26, 2.2.25, 2.2.24, 2.2.23, 2.2.22, 2.2.21, 2.2.20, 2.2.19, 2.2.18, 2.2.16, 2.2.15, 2.2.14, 2.2.13, 2.2.12, 2.2.10, 2.2.9, 2.2.8, 2.2.7, 2.2.6, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.21, 2.1.20, 2.1.19, 2.1.18, 2.1.17, 2.1.16, 2.1.15, 2.1.14, 2.1.13, 2.1.12, 2.1.11, 2.1.10, 2.1.9, 2.1.8, 2.1.7, 2.1.6, 2.1.5, 2.1.2, 2.1.1, 2.1.0, 2.0.0

**Comment by mattpodwysocki** [comment]
@cboden yes, forgot to do that.  The next version will be available soon
