### ISSUE TITLE
fromEvent() and fromEventPattern() pass arguments object to selector function

### ISSUE THREAD

**Issue by rjkip** [Reactive-Extensions/RxJS#794]
In 2.5.3, [`fromEvent()`](https://github.com/Reactive-Extensions/RxJS/blob/v.2.5.3/src/core/linq/observable/fromevent.js#L148) and [`fromEventPattern()`](https://github.com/Reactive-Extensions/RxJS/blob/v.2.5.3/src/core/linq/observable/fromeventpattern.js#L14) pass an arguments object instead of an array to their selector functions. On master, the commit ["Moving to 3.x"](https://github.com/Reactive-Extensions/RxJS/commit/f92544eca1890b6c0b0861d732f98abc699d0d3b) fixes this by [applying](https://github.com/Reactive-Extensions/RxJS/blob/2b37250ef2646d240aa09b7b6d2649c84b6c817a/src/core/linq/observable/fromeventpattern.js#L13) the `arguments` to the selector function.

Will this change be included in a 2.x release? If so, when? If not, will there be a 2.x development branch where I can submit a the same fix to?

**Comment by mattpodwysocki** [comment]
@rjkip no, this will not be backported, because this is a breaking change.
