### ISSUE TITLE
Incorrect variable name passed in argument on http://reactive-extensions.github.io/RxJS/ tutorial

### ISSUE THREAD

**Issue by jjmasse** [Reactive-Extensions/RxJS#802]
I was looking around in the project for this reference to provide a merge request for you - but the styled pages seem unassociated.

Issue found on this page: [http://reactive-extensions.github.io/RxJS/](http://reactive-extensions.github.io/RxJS/)

### Code sample:
```javascript
var $input = $('#input'),
    $results = $('#results');

/* Only get the value from each key up */
// change: var keyups = Rx.Observable.fromEvent(input, 'keyup')
// to: var keyups = Rx.Observable.fromEvent($input, 'keyup')
    .map(function (e) {
        return e.target.value;
    })
```

#### Suggestion:
Since the library will pickup the element on the page on its own by its ID, perhaps it would be a good idea to give the input a different name like: `type-ahead-input` to reduce possible confusion with picking up "inputs" as jQuery would.

For example:

```html
<!-- for elements -->
<input type="text"/>
<input type="text"/>
```
```javascript
// w/o supplying "#" gives some unfortunate, and potentially confusing results
var input = $('input').length;
// => yields 2
```

Being a bit more specific of the elements purpose will help avoid these types of behaviors of the library and give your content clearer meaning and reduce potential for error.
```javascript
var typeAheadInput = $('#type-ahead-input');
...

var keyups = Rx.Observable.fromEvent(typeAheadInput, func...
```

**Comment by xgrommx** [comment]
I think this page is dead.

**Comment by jjmasse** [comment]
That's fair, perhaps it would make sense to forward it to the readme since that seems to be the most up to date.  Or at least leave a notice on the dead page.

**Comment by mattpodwysocki** [comment]
@jjmasse closing as our GH pages has now been removed

**Comment by jjmasse** [comment]
Awesome thanks guys!
