### ISSUE TITLE
Broken link on doc

### ISSUE THREAD

**Issue by razvangherghina** [Reactive-Extensions/RxJS#804]
On documentation page:
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/categories.md
for operator range the link is broken should be:

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/range.md

**Comment by crissdev** [comment]
Also, links in the first paragraph of *Batteries Included* section (README.md):

- (rx.lite.js) https://github.com/Reactive-Extensions/RxJS/blob/master/doc/libraries/rx.lite.md
- (rx.core.js) https://github.com/Reactive-Extensions/RxJS/blob/master/doc/libraries/rx.core.md

**Comment by mattpodwysocki** [comment]
@razvangherghina @crissdev fixed

**Comment by crissdev** [comment]
@mattpodwysocki You might want to check links in the *Lite Libraries* section as well. It seems most of them are broken too.

**Comment by mattpodwysocki** [comment]
@crissdev not broken, just missing as that is documentation I need to write.

**Comment by crissdev** [comment]
Ah, ok. :+1:
