### ISSUE TITLE
`fromNodeCallback` should be fast

### ISSUE THREAD

**Issue by benjamingr** [Reactive-Extensions/RxJS#809]
I got thinking about this because of [an issue on es-observable](https://github.com/zenparsing/es-observable/issues/41#issuecomment-120455922). I know a lot of people here like using observables for singular values. 

I think it would be worth producing a "fast" `fromNodeCallback` function that works without allocating a closure. For a general idea on how to do this see [bluebird's promisify](https://github.com/petkaantonov/bluebird/blob/master/src/promisify.js#L124-L216). I think this would be really helpful for NodeJS users to have an `Observify` method that converts whole callback and stream APIs to promises using dynamic compilation like this. 

I didn't think it was worth mentioning before since in my own code I typically have a relatively low number of observables that stay alive for the whole duration of the application.

**Comment by mattpodwysocki** [comment]
@benjamingr already made improvements to [`Observable`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/observable.js#L20-L28) and [`fromEvent`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/fromevent.js#L1-L29). Are these acceptable improvements?

**Comment by benjamingr** [comment]
These look much better than before, but contrast fromEvent with bluebird's promisify - you can save the closure altogether there (`selector` is referenced from within the anonymous observable) - by the way - why is a CompositeDisposable required there?

**Comment by mattpodwysocki** [comment]
@benjamingr in a quick code snippet, could you illuminate me as to how you would eliminate the closure in this instance with the `selectorFn`?

**Comment by benjamingr** [comment]
Well - first of all I don't think DOM event attachment speed is a big deal for RxJS (at least in my code that was never a bottleneck) - I was more concerned with how certain people wrap one-time-events (That is, fromNodeCallback).

Second, you can pass `selector` to `createEventListener` - but really, you can move the entire `handler` function outside of the `new AnonymousObservable` call, and localize the closure so it doesn't capture it anyway (as functions in the same scope all have closure if at least one does, at least in v8). I also think a lot less can be allocated here.

But really, DOM Events have never been a bottleneck for us in RxJS. I think callbacks in node are much "hotter" target :) I think the bluebird promisify code I linked to above should be pretty easy to RE and there is no reason observables would be slower than promises here as they're simpler.

**Comment by paulpdaniels** [comment]
+1 because that bluebird code blew my mind =)

**Comment by mattpodwysocki** [comment]
@benjamingr I think this is good enough:
```bash
$ node fromcallback.js
old x 45,548 ops/sec ±4.25% (71 runs sampled)
new x 70,270 ops/sec ±4.57% (73 runs sampled)
Fastest is new
```

Here are [`fromCallback`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/perf/operators/fromcallback.js) and [`fromNodeCallback`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/perf/operators/fromnodecallback.js)

Good enough?

**Comment by benjamingr** [comment]
Much better. Let's ask @blesh who uses Observables for singular values, can you now create (let's say) 10 Observables per request?

Do you have any benchmarks you trust that profile a real workload? (Personally I like @spion's suite)

**Comment by mattpodwysocki** [comment]
@benjamingr no, I just basically use benchmark.js for simple testing to see how well I'm doing in the [operators](https://github.com/Reactive-Extensions/RxJS/tree/master/tests/perf/operators) folder

**Comment by blesh** [comment]
> Let's ask @blesh who uses Observables for singular values, can you now create (let's say) 10 Observables per request?

@mattpodwysocki @benjamingr actually, we're [looking for better macro perf benchmarks for RxJS Next right now](https://github.com/ReactiveX/RxJS/issues/77) With a system like this, it's really important that we get some metrics on more "real-worldy" scenarios, and more importantly, keep an eye on things like memory efficiency in those areas as well. @jeffbcross was kind enough to replace our micro-perf benchmarks that we did in the early stages of the library with macro-perf tests in benchpress.js, but we really do need some better scenarios. Perhaps this is one of them?

FWIW: I think the work that @mattpodwysocki has done on this already is adequate for this version.

**Comment by benjamingr** [comment]
Thanks, that settles it then. Good work @mattpodwysocki :)
