### ISSUE TITLE
fromNodeCallback and fromCallback phantom execution

### ISSUE THREAD

**Issue by paulpdaniels** [Reactive-Extensions/RxJS#818]
Both `fromNodeCallback` and `fromCallback` have an interesting bug when they complete but then are subscribed to again.

In the following code snippet, the result of the execution is the same for both subscriptions, since the value of the execution is cached. However, because of how the implementation done, the resubscription causes the method to re-execute and then have its values ignored.

```javascript

var nodeCallCount = 0;

function nodeCallbackFn(cb) {

    console.log("Executing node callback");
    cb(null, ++nodeCallCount);
}

var nodeSource = Rx.Observable.fromNodeCallback(nodeCallbackFn)();

nodeSource.subscribe(console.log.bind(console));
nodeSource.subscribe(console.log.bind(console));


//Expected
//Executing node callback
//1
//1

//Actual
//Executing node callback
//1
//1
//Executing node callback
```

[Offending code](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/fromnodecallback.js#L13-L38)

I am going out on a limb and suggesting that this should not be re-executing, and even if it is it should actually respect the subsequent values. So I'll go ahead and put together a PR for the former case, unless I hear something compelling from the "resubscribe is re-execute" camp in the mean time.

**Comment by alexanderGugel** [comment]
I know that this issue is old and has long been merged in, but I strongly believe that subsequent subscriptions should indeed result into an re-execution of the underlying function.

In general I think that having an cold observable makes things much less confusing in the long term. I ran into this issue a couple of minutes ago when I tried symlinking a file, unless the containing directory doesn't exist (then create the directory and retry).

My code looked something like this:

```js
symlink(relativeTargetPath, sourcePath)
        .retryWhen(() => mkdirp(baseSourcePath))
```

where 

```js
const symlink = Observable.fromNodeCallback(fs.symlink)
``

I would imagine that retryWhen is more or less the exact use-case for a scenario like that.

It looks like `fromNodeCallback` used to be hot (ae1cc683e37e3844e34121e3eb862b9177c3f892), then was changed to cold (dd33b768eac11028020f28fe66e547a75d9bb8cc), then was changed to hot (ae244b514f4ff8fd0be3703069c3587aa3ad041c).

Maybe it might be worth having a different method "fromColdNodeCallback". I personally don't think it makes a lot of sense for this to be a hot observable, but I think there should definitely be an option to create a cold one.

I would be more than happy to put together a PR for this. Thoughts?
