### ISSUE TITLE
A new implementation of flatMapConcat doesn't contains in dist.

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#825]
Hi @paulpdaniels. Why you don't included a new implementation of `flatMapConcat` to dist?

**Comment by paulpdaniels** [comment]
Hey @xgrommx, I don't include the dist files when I do PRs to avoid conflicts in the build. I rely on @mattpodwysocki for that =).

**Comment by mattpodwysocki** [comment]
@xgrommx that's part of checking is that you don't include the dist, only I do when I create builds.
