### ISSUE TITLE
A lift method

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#826]
Hello @mattpodwysocki. What is an alternative for a `lift` method of rxjava in rxjs?

**Comment by mattpodwysocki** [comment]
@xgrommx what is the use case for having `lift` here?

**Comment by blesh** [comment]
FWIW: RxJS has a `lift` method.

**Comment by xgrommx** [comment]
@mattpodwysocki @blesh I think that `lift` is like a `pipe` in nodejs. In rxjava it looks like so. For example http://reactivex.io/documentation/implement-operator.html

**Comment by mattpodwysocki** [comment]
@xgrommx you're more than welcome to submit a PR for it, but it's not high on my priority list.

**Comment by blesh** [comment]
@xgrommx excuse me, I omitted a word in my previous comment... RxJS **Next** has a lift method.

[It's just in a different repository](https://github.com/ReactiveX/RxJS/blob/7737edc3124b3ca436220bcc2485a58ed7123208/src/Observable.ts#L67)

**Comment by mattpodwysocki** [comment]
Closing for now since the next version will have it. No need to retrofit it here
