### ISSUE TITLE
Fix `takeUntilWithTime` documentation

### ISSUE THREAD

**Issue by menelaos** [Reactive-Extensions/RxJS#827]
The first sentence in the documentation of [`takeUntilWithTime`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/takeuntilwithtime.md) currently reads:

> Returns the values from the source observable sequence until the other observable sequence produces a value.

This should probably be something like

> Returns the values from the source observable sequence until `endTime` is reached.

**Comment by paulpdaniels** [comment]
You could probably just go ahead and submit a PR for this next time =)

**Comment by menelaos** [comment]
Yeah, I wasn't sure about whether I'd need to sign the CLA first, so this seemed faster :-)

**Comment by paulpdaniels** [comment]
Ah fair enough. I don't believe you would need to for docs changes though.
