### ISSUE TITLE
Question about error handling in flatMap

### ISSUE THREAD

**Issue by zhangchiqing** [Reactive-Extensions/RxJS#829]
In the [autocomplete example](https://github.com/Reactive-Extensions/RxJS/issues/new), how to always show error messages when the requests fail? 

When an ajax request fails and returns an error, the error will be sent through the observable. Since [no more messages will arrive after an onError](https://github.com/Reactive-Extensions/RxJS/tree/master/doc/designguidelines#32-assume-resources-are-cleaned-up-after-an-onerror-or-oncompleted-message), the observable will be completed with error and no further errors or results won't be shown.

So the question is how to handle **all the errors** after `flatMap` the keyup events to request promises.

For example:
```
'use strict';

var Rx = require('rx');
var Promise = require('bluebird');

function getPromiseByNum(num) {
  if (num < 2) {
    return Promise.resolve(num);
  } else {
    return Promise.reject(num);
  }
}

var source = Rx.Observable.interval(1000)
.flatMap(function(num) {
  return Rx.Observable.fromPromise(getPromiseByNum(num));
});

var subscription = source.subscribe(
  function (x) {
    console.log('Next: ' + x);
  },
  function (err) {
    console.log('Error: ' + err);
  },
  function () {
    console.log('Completed');
  });
```

I expect the above code returns
```
Next: 0
Next: 1
Error: 2
Error: 3
Error: 4
...
```

But it actually returns
```
Next: 0
Next: 1
Error: 2
(over)
```

**Comment by paulpdaniels** [comment]
Errors are terminating for an `Observable`, so you can't expect the outermost sequence to carry on like nothing happened. If you want the behavior of capturing the exceptions you need to catch the exceptions inside the `flatMap` and re-emit them as non-exceptions:

```javascript

'use strict';

var Rx = require('rx');
var Promise = require('bluebird');

function getPromiseByNum(num) {
  if (num < 2) {
    return Promise.resolve(num);
  } else {
    return Promise.reject(num);
  }
}

var source = Rx.Observable.interval(1000)
.flatMap(function(num) {
  return Rx.Observable.fromPromise(getPromiseByNum(num))
                                    .catch(function(e) { return Rx.Observable.just({error : e}); });
});

var subscription = source.subscribe(
  function (x) {
    if (x.error) console.log('Error: ' + x.error);
    else console.log('Next: ' + x);
  },
  function (err) {
    console.log('Error: ' + err);
  },
  function () {
    console.log('Completed');
  });


```

**Comment by zhangchiqing** [comment]
Thanks @paulpdaniels for answering my question. I agree this is a workaround. But is it the best practice? 

1. I don't really like the fact that I have to send respond data along with errors through a `Observable`. The `source` is not just the data source, it also includes errors which are a different data type. So it should be renamed as `sourceWithErrors`. If I have any `Observable` created from `sourceWithErrors`, it has to handle the errors being passed through as well. I feel like that would make things complicated. no?

2. And also, handling errors in two different places looks duplicated. I guess I would never need the `onError` handler, because any error coming from there is a fatal error which will destroy the whole pipe and stop further data coming through. I can't think of any case where I need to handle `onError`.

I think this `flatMap` case is very common to me, especially in form submission. For example, I have a login form, with a button to submit, and I want to show error message if the req doesn't pass the backend validation.

So I would have the similar logic, but the error handling looks complex to me. Is this the best practice?

```
'use strict';

var Rx = require('rx');
var Promise = require('bluebird');

function reqWithQuery(query) {
  return $.ajax({
    url: 'https://xxx/login',
    method: 'POST',
    data: query,
  }).promise();
}

var submits = Rx.Observable.fromEvent($('.btn-submit'), 'click');
var querys = submits.map(function() {
  return {
    username: $('.username').val(),
    password: $('.password').val(),
  };
});

var respondsWithErrors = querys.flatMap(function(query) {
  return Rx.Observable.fromPromise(reqWithQuery(query))
    .catch(function(e) {
      return Rx.Observable.just({ error: e });
    });
});

var subscription = respondsWithErrors.subscribe(
  function (tokenOrError) {
    if (tokenOrError.error) {
      $('error-message').html(tokenOrError.error.message);
      return ;
    }

    console.log('Next: ' + tokenOrError);

    saveToken(tokenOrError);
  },
  function (err) {
    console.log('Fatal error: ' + err);
  });
```

**Comment by trxcllnt** [comment]
@zhangchiqing yes, this is best practice. Observables can only error once. Since `flatMap is merging `n` inner sequences into a single Observable sequence, the `flatMap` sequence is also only allowed to error once, and must terminate on the first error from any of its inner sequences.

`catch` in @paulpdaniels' is *effectively* materializing `onError` messages into `onNext` messages. There's nothing wrong with his example or approach, but you may find value in the `materialize` and [`dematerialize`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/dematerialize.md) operators, which were created for this purpose.

Since the inner Observables no longer `onError`, `flatMap` will remain subscribed to the `querys` source.

```es6
'use strict';

var Rx = require('rx');
var Promise = require('bluebird');

function reqWithQuery(query) {
  return $.ajax({
    url: 'https://xxx/login',
    method: 'POST',
    data: query,
  }).promise();
}

var submits = Rx.Observable.fromEvent($('.btn-submit'), 'click');
var querys = submits.map(function() {
  return {
    username: $('.username').val(),
    password: $('.password').val(),
  };
});

var respondsWithErrors = querys.flatMap(function(query) {
  return Rx.Observable
    .fromPromise(reqWithQuery(query))
    // wrap `onNext`, `onError`, or `onCompleted` messages in
    // onNext'd `next`, `error,` or `completed` Notifications
    .materialize();
});

var subscription = respondsWithErrors.subscribe(
  (notification) => {
    if (notification.kind === "N") {
      const token = notification.value;
      console.log('Next: ' + token);
      saveToken(token);
    } else if (notification.kind === "E") {
      $('error-message').html(notification.error.message);
    }
  },
  (err) => { console.log('Fatal error: ' + err); }
);
```

**Comment by zhangchiqing** [comment]
Thanks for the explanation @trxcllnt ! I'll try it :+1:

**Comment by mkrishnan777** [comment]
## 

> [`****`]([url](

`[url](

> `url`

)`

))

**Comment by gunar** [comment]
@zhangchiqing Did you end up writing that much error-handling code every single time?

**Comment by gunar** [comment]
For whoever might end up here, my advise is to switch to [Highland.js](/caolan/highland).
Check this sweet error handling:
```js
'use strict'

const _ = require('highland')

const $ = _()

try {
  $.map(x => {
    if (x === 1) throw Error('caught number 1')
    else return x
  })
    .errors(e => console.log({ catched: e.message }) )
    .each(x => console.log({ x }))
} catch (e) { console.log({ outer: e.message }) }

$.write(1) // { catched: 'caught number 1' }
$.write(2) // { x: 2 }
```

It seems we were trying to use the wrong tool for the job.
