### ISSUE TITLE
A new method like a update

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#838]
Hello everyone, What if add a new method like a `update` as in Bacon http://baconjs.github.io/api.html#bacon-update? Now this method can be implemented like so:

```js
Rx.Observable.when(
  obs.thenDo(x => prev => prev + x),
  obs2.thenDo(x => prev => prev - x)
).startWith(0).scan((prev, f) => f(prev)).publish().refCount();
```
But this is ugly =)

I created some extension but this extension to use Bacon style https://github.com/xgrommx/react-rx-flux/blob/master/src/rx-extensions.js#L37

**Comment by mattpodwysocki** [comment]
@xgrommx that's fine, and we could add it to the join patterns.  Feel free to send a PR with documentation and tests

**Comment by mattpodwysocki** [comment]
@xgrommx still waiting on that PR with tests and documentation...

**Comment by mattpodwysocki** [comment]
Closing for now until the PR comes in
