### ISSUE TITLE
Rx.Observable.fromCallback .publishLast().refCount() don't seem to be working

### ISSUE THREAD

**Issue by elayman** [Reactive-Extensions/RxJS#839]
When you subscribe to fromCallback more than once, the code executes twice, which not only executes 'func' twice, it also does 'args.push(handler);' which modifies the already modified args array to look something like this:
args = 
1st subscriber: [data, data, handler]
2nd subscriber: [data, data, handler, handler] <-- Broken if your func expects (data, data, callback, boundData)

See JSBin for example:
http://jsbin.com/lifewehimu/1/edit?html,js,output

**Comment by paulpdaniels** [comment]
Duplicate of #818. Should be fixed in the latest version (see #823).

**Comment by mattpodwysocki** [comment]
@elayman fixed as per 3.0.1 and before
