### ISSUE TITLE
smaller npm

### ISSUE THREAD

**Issue by TrySound** [Reactive-Extensions/RxJS#840]
Add please *.min.js and *.map to .npmignore

**Comment by gre** [comment]
are you sure we should disable source maps files? aren't they useful for `browserify` / `webpack` ?

**Comment by TrySound** [comment]
@gre When you use builder, you can add uglify in one second. So it's useful only for cdn or copy-into-dir way.

**Comment by TrySound** [comment]
@gre For now it just strongly increases size of package.

**Comment by gre** [comment]
I agree for the `*.min.js`, but I was just questionning the `.map`. Since the entry point is one big file (`rx.all.js`), isn't that `.map` supposed to restore the RxJS file hierarchy or I'm wrong?

**Comment by TrySound** [comment]
When you debug your app, better to know that one thing is rx, the other is app. But how know that observer is rx, but not part of my app?

**Comment by TrySound** [comment]
And .map more increase size than .min

**Comment by TrySound** [comment]
Also `logos`, `ts` and `src` do not add functionality.

**Comment by mattpodwysocki** [comment]
@TrySound removed logos, but keeping ts and src for now as they are needed if you want TypeScript definitions, etc

**Comment by TrySound** [comment]
Thanks
