### ISSUE TITLE
Does disposing a subscription complete the stream?

### ISSUE THREAD

**Issue by gre** [Reactive-Extensions/RxJS#841]
Hi,

I've been using RxJS for [this demo](http://greweb.me/diaporama/#example/4) and I've met something unexpected and did a workaround to make it work. I will debrief here to see if I can write something more concise.

### use-case

- I have an observable of photos (that get fetched from flickr)
- I subscribe on it in my slideshow lib `subscribe(onNext, onError, onCompleted)`
- when user leaves, I call `dispose()` on the subscription

### What I expected

I expected the `onCompleted` to be called when dispose() was called. Is that a bad assumption? How can I know that the stream has been disposed so I can sync my internal state?

### workaround

code is [here](https://github.com/gre/diaporama-website/blob/master/stream_example.js#L74-L102), basically the pattern is:
```js
var leaves = new Rx.Subject();
module.exports = function () { // called when demo starts
  var stream = getStream(...)
    .takeUntil(leaves); // we stop once user leaves the demo

  var subscription = stream.subscribe(..., ..., onCompleted);

  return function () { // called when the demo ends
    leaves.onNext();
    subscription.dispose();
  };
};
```

onCompleted will be called either because the stream ends OR the demo ends.

I don't like the fact that I have to use another stream (leaves) to do that.
BTW AFAIK the subscription.dispose() call is probably optional since a subscription will be disposed on completed (if I'm correct).

Thanks

**Comment by trxcllnt** [comment]
@gre `onComplete` is only ever signaled by an Observable, not in response to the subscription. If you're looking for an operator that runs a function upon disposal (whether disposal is triggered by `onCompleted`, `onError`, or `dispose`), see [finally](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/finally.md).

**Comment by mattpodwysocki** [comment]
@gre What @trxcllnt has said here is correct.  Just by disposal of a subscription does not mean that `onCompleted` will be fired as that is the responsibility of the `Observable`, not the subscription or `Disposable` in this case.
