### ISSUE TITLE
TestScheduler, ReactiveTest missing from 'rx' module

### ISSUE THREAD

**Issue by dropout** [Reactive-Extensions/RxJS#844]
Hi there,

I'm trying to test my rxjs application with the guidance of testing.md, but the TestScheduler, ReactiveTest properties of Rx are missing.
https://jsbin.com/nigizawige/edit?html,js,console,output

I think its somehow related to this issue: https://github.com/Reactive-Extensions/RxJS/issues/582
I'm using 2.5.3 from npm and 2.3.22 in jsbin.

I'm not sure if this is the expected behaviour and there is something else to do to get it going.

**Comment by dropout** [comment]
Further investigations revealed (at least for me) that browser version rx.all.js (as for me naming it all sounds a little bit odd in this case) doesn't contain these modules. When building a bundle with browserify or webpack they rely on package json 

```
  "browser": {
    "index.js": "dist/rx.all.js"
  },
```

which also points to the rx.all.js so typical use case of writing tests with require('rx') doesn't work. 

What worked for me:
```
var Rx = require('rx/index');
```

This way bundles work as intended and for testing no harm done by including full suite.

**Comment by erykpiast** [comment]
I've reported it some time ago: https://github.com/Reactive-Extensions/RxJS/issues/673

Nobody cares. But `rx/index` is a nice trick, I'll use that.

**Comment by dropout** [comment]
@erykpiast Sorry to hear that. At least a documentation update would be very much appreciated as this problem burns hours for people.

**Comment by baio** [comment]
+1, please fix

**Comment by jmale** [comment]
+1, please fix

**Comment by mattpodwysocki** [comment]
Done
