### ISSUE TITLE
merge allows you to add null values without error, but then throws an error on subscribe

### ISSUE THREAD

**Issue by ccapndave** [Reactive-Extensions/RxJS#847]
```
const badMerge = Rx.Observable.merge(
	Rx.Observable.just(1),
	null
)
```

This is allowed, but when you subscribe you get a hard to debug error deep inside `rx.all.js`:
`Uncaught TypeError: Cannot read property 'subscribe' of null`

It would be nice if the error could be thrown immediately on creating the merge.

**Comment by xgrommx** [comment]
@ccapndave As you can see `merge` can have only sequence of observables. Probably you can solve your example so:

```js
const badMerge = Rx.Observable.merge(
    Rx.Observable.just(1),
    Rx.Observable.just(null)
)
```

**Comment by ccapndave** [comment]
For sure - this is for catching mistakes, not for actually merging a null value.  If I accidentally have a variable which I think contains a stream but is actually null, I want an error message here, not a difficult to decipher one about subscribe.

**Comment by xgrommx** [comment]
> It would be nice if the error could be thrown immediately on creating the merge.

Rx is lazy and all subscriptions will be to work after method subscribe.

**Comment by ccapndave** [comment]
I don't really know how the codebase works.  Is `Rx.Observable.merge` not called at all until the subscription?

**Comment by xgrommx** [comment]
All methods of Rx not called until the subscription not be to call.

**Comment by ccapndave** [comment]
Ah, I didn't realise.  Closing the bug :)

**Comment by xgrommx** [comment]
For example:

```js
let n = 1 + 2; // normal approach
let r = () => 1 + 2; // rx approach. In subscribe all methods like `r` will be called `r()`
```

**Comment by erykpiast** [comment]
Anyway some basic not lazy type checks could be introduced, for programmers comfort and debugging easiness, couldn't they?

**Comment by xgrommx** [comment]
@erykpiast Probably for it you can use Typescript.

**Comment by ccapndave** [comment]
I do use Typescript and it helps with lots of things, but its no use for accidental nulls

**Comment by paulpdaniels** [comment]
I think this is a valid issue, several of the operators have runtime argument checking in place, which are not lazy (see [skip](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/skip)). Especially if it is going to improve the debugging experience.
