### ISSUE TITLE
Document `materialize` method or remove all references to it

### ISSUE THREAD

**Issue by roganov** [Reactive-Extensions/RxJS#849]
For some reason `materialize` method isn't documented, but nevertheless is referenced from some places (for example, section 5.1 of https://github.com/Reactive-Extensions/RxJS/blob/master/doc/designguidelines/readme.md ).

**Comment by xgrommx** [comment]
@roganov Look at http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/materialize.html but this in progress.

**Comment by roganov** [comment]
@xgrommx Thanks, I know what `materialize` does, but it should be documented in official docs (or removed altogether).
BTW, love your rx-book!

**Comment by xgrommx** [comment]
Thanks! :shy: Now I have one big thing https://github.com/xgrommx/rx-book/issues/19

**Comment by mattpodwysocki** [comment]
Done
