### ISSUE TITLE
The Roadmap to 4.0

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/RxJS#854]
This is the roadmap for getting to RxJS 4.0:
- rewrite of the schedulers to have a much simpler interface
- removal of absolute time methods such as `generateWithAbsoluteTime` and `timer`
- removal of `debounceWithSelector` to merge with `debounce` whether it takes a number or a selector
- modularity
- performance work

## Scheduler Rewrite ##

The schedulers have long had a long of technical debt when brought over directly from the .NET world.  To simplify this, we will now have the following contract on the `Scheduler` as written in TypeScript so that it makes sense as an interface.  You will notice that the previous versions which did not have state associated with them are no longer supported.  This caused too much overhead to support both, so if you have no state to pass, simply pass `null` for the state.

```typescript
interface IDisposable {
  dispose(): void
}

interface IScheduler {
  // Current time
  now(): number;

  // Schedule immediately
  schedule<TState>(state: TState, action: (scheduler: IScheduler, state: TState) => IDisposable) : IDisposable;
	
  // Schedule relative
  scheduleFuture<TState>(state: TState, dueTime: number, action: (scheduler: IScheduler, state: any) => IDisposable) : IDisposable;

  // Schedule absolute
  scheduleFuture<TState>(state: TState, dueTime: Date, action: (scheduler: IScheduler, state: TState) => IDisposable) : IDisposable;

  // Schedule recursive
  scheduleRecursive<TState>(state: TState, action: (state: TState, action: (state: TState) => void) => void): IDisposable;

  // Schedule recursive relative
  scheduleRecursiveFuture<TState>(state: TState, dueTime: number, action: (state: TState, action: (state: TState, dueTime: number) => void) => void): IDisposable;
	
  // Schedule recursive absolute
  scheduleRecursiveFuture<TState>(state: TState, dueTime: Date, action: (state: TState, action: (state: TState, dueTime: Date) => void) => void): IDisposable;
	
  // Schedule periodic
  schedulePeriodic<TState>(state: TState, period: number, action: (state: TState) => TState): IDisposable;
}
```

Now, to schedule something immediately, you must follow the following code snippet.  The return value is optional as we will automatically fix it to be a `Disposable` if you do not provide us with one.
```js
var d = scheduler.schedule(null, function (scheduler, state) {
  console.log('scheduled ASAP');
  return Rx.Disposable.empty;
});
```

Same applies to scheduling in the future:
```js
// Scheduled 5 seconds in the future with absolute time
var d = scheduler.scheduleFuture(null, new Date(Date.now() + 5000), function (scheduler, state) {
  console.log('scheduled using absolute time');
  return Rx.Disposable.empty;
});

// Scheduled 5 seconds in the future with relative time
var d = scheduler.scheduleFuture(null, 5000 function (scheduler, state) {
  console.log('scheduled using absolute time');
  return Rx.Disposable.empty;
});
```

## Removal of Absolute Timing Methods ##

Due to time drift and other issues related to absolute timing, we have decided in the JS runtimes that it's best to stick with relative times only.  To that end, `generateWithAbsoluteTime` has been dropped and `generateWithRelativeTime` has been incorporated as part of `generate` with a time based selector.

## Removal of `debounceWithSelector` ##

Once again, we found that we could easily collapse code with the same meaning to the same method whether it is with a relative time `debounce(dueTime, scheduler)` to using a time based selector `debounce(durationSelector)`.  Previously we had them separated with `debounce` and `debounceWithSelector`.

## Modularity

We will continue from our beginnings of moving towards modularity per method in the 4.x timeframe that we started in the 3.x timeframe so that you could import `map`, `filter`, `fromEvent` and others without bringing in the entire RxJS library

## Performance Work

As always, we are looking for ways to increase performance for actual constraints people have when running in production, and not just arbitrary synchronous micro-benchmarks.  To that end, we would love your help in understanding where the performance bottlenecks are for your applications.

**Comment by staltz** [comment]
Humble and honest question: why not join efforts with ReactiveX/RxJS and build this there?

**Comment by mattpodwysocki** [comment]
@staltz because this project has customers that are using it and will continue for a while to do so and they want fixes just like any other library.  I have committed code and done code reviews for ReactiveX/RxJS but it will be a long time before that is ready.

**Comment by staltz** [comment]
:+1:

**Comment by trxcllnt** [comment]
> As always, we are looking for ways to increase performance for actual constraints people have when running in production, and not just arbitrary synchronous micro-benchmarks. To that end, we would love your help in understanding where the performance bottlenecks are for your applications.

Here's an example of a performance bottle-neck we have running Rx in production:
```es6
Rx.Observable.of(1, 2, 3)
  .flatMap((x) => { return Rx.Observable.return(x * 5); })
  .subscribe((x) => { console.log(x); });
```

It's a coincidence that this example is so small it fits nicely into a micro-benchmark, but the issues that cause this to be slow aren't with `of`, `return` or even `flatMap`, they're systemic. That's why we started ReactiveX/RxJS.

**Comment by xgrommx** [comment]
Some method like a `update` as in http://baconjs.github.io/api.html#bacon-update.

**Comment by headinthebox** [comment]
I dont understand the remark from @trxcllnt, if the issues are not with any of the operators in the sample, where are they? 

And I can hardly see how such a basic use case is a perf issue (excuse my ignorance)

**Comment by trxcllnt** [comment]
@headinthebox the issues are with `AnonymousObservable`, `CurrentThreadScheduler`, and Object/closure allocations for Disposables. These are the same facts RxJava and your RxMobile have discovered. It shouldn't be a shock that trampoline-scheduling dispatches and allocating an `AutoDetachObserver` + `SingleAssignmentDisposable` for all subscribes is *expensive*.

**Comment by paulpdaniels** [comment]
@trxcllnt Isn't this why we have the perf folder though? For example none of the operators you mention use `AnonymousObservable` anymore so performance gains don't seem to be a lost cause yet.

**Comment by trxcllnt** [comment]
@paulpdaniels `ObservableBase` is `AnonymousObservable` renamed, i.e. it still creates an Observer/Disposable pair regardless of whether the source Observable creates a Disposable.

**Comment by xgrommx** [comment]
@mattpodwysocki When release of version 4?
