### ISSUE TITLE
How to join Slack channel

### ISSUE THREAD

**Issue by LongLiveCHIEF** [Reactive-Extensions/RxJS#858]
You have a slack channel listed in your README, but it's not one of those "put your email address in for an invite" links.  Is there a public way to request an invite to this slack channel?

**Comment by roganov** [comment]
Don't know about Slack, but there is a quite active [gitter chat](https://gitter.im/Reactive-Extensions/RxJS).

**Comment by mattpodwysocki** [comment]
@LongLiveCHIEF no, it's not really all that public although you can email @paulcbetts for more information.  I would recommend the Gitter channel instead.
