### ISSUE TITLE
Support Generators function

### ISSUE THREAD

**Issue by tusharmath** [Reactive-Extensions/RxJS#860]
As far as I understand `async` functions can also be implemented via observables. Wouldn't it be great if someone could write code like this —

```javascript
var write = rx.fromCallback(fs.write);

rx.wrapGenerator(function * () {
  var bytesWritten = yield write('some-data'); 
  console.log('Bytes Written:', bytesWritten);
})
```

## wrapGenerator 
```javascript
function wrapGenerator(func) {
  var gen = func();

  function attach(observable) {
    if (observable) {
      observable.subscribeOnNext(function(out) {
        setTimeout(function() {
          attach(gen.next(out.value));
        });
      });
    }
  }
  attach(gen.next().value);
}

```
Why Do this?
A lot of times we write async code using [co](http://npmjs.com/package/co) library, it turns out to be much easier to read and is using promises internally. Now one can convert all observerables into promises using the `asPromise` method and then use the co lib OR have a way to use `yield` directly on the observable.

**Comment by xgrommx** [comment]
Did you try it? https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/spawn.js. All that regarding with this one https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/spawn.md https://github.com/Reactive-Extensions/RxJS/pull/851 https://github.com/Reactive-Extensions/RxJS/pull/856 https://github.com/Reactive-Extensions/RxJS/pull/855

**Comment by xgrommx** [comment]
About co.js https://github.com/tj/co/pull/221

**Comment by tusharmath** [comment]
Perfect!

**Comment by tusharmath** [comment]
Though my problem is resolve, there is a new
