### ISSUE TITLE
Leaking comparerEquals as global

### ISSUE THREAD

**Issue by staltz** [Reactive-Extensions/RxJS#862]
https://github.com/Reactive-Extensions/RxJS/blob/20bb27924945a6295eb039d2392f0dd79843995a/src/core/perf/operators/distinctuntilchanged.js#L34
Please don't leak `comparerEquals` to the `window`, all my tests went banana because of this. In RxJS 3.0.1.
I don't know where elsewhere in the codebase is this mistake done, but it ends up in dist/rx.js.

**Comment by mattpodwysocki** [comment]
Fixed

**Comment by staltz** [comment]
Thank you!
Waiting for v3.0.2...

**Comment by staltz** [comment]
@mattpodwysocki just as a pointer in case you didn't know: I release patch versions as often as I can (any tiny fix is a patch version released). And the only way I can do that and stay sane are these handy scripts: https://github.com/cyclejs/cycle-core/blob/master/package.json#L57-L60
Don't know how complicated that would be to add to your grunt workflow, just a suggestion.

**Comment by mattpodwysocki** [comment]
@staltz appreciated!
