### ISSUE TITLE
rx.spawn with Observable.fromNodeCallback broke in version 3

### ISSUE THREAD

**Issue by wonderdogone** [Reactive-Extensions/RxJS#869]
running the samples form documentation at 
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/generators.md#asyncawait-style-and-rxjs

no longer work when moving from Rx 2. to 3. 

Error form examples is:
Rx.spawn(function* () {
   ^
TypeError: undefined is not a function

**Comment by xgrommx** [comment]
Now this is a new declaration for `spawn`. You can take a look at this https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/spawn.md. Also you can use some method as in cojs - `wrap`. Example from doc:

```js
var Rx = require('rx');
var request = require('request');
var get = Rx.Observable.fromNodeCallback(request);

Rx.Observable.spawn(function* () {
  var data;
  try {
    data = yield get('http://bing.com').timeout(5000 /*ms*/);
  } catch (e) {
    console.log('Error %s', e);
  } 

  console.log(data);
}).subscribe();
```

**Comment by wonderdogone** [comment]
@xgrommx thanks. I updated accordingly. and I see PR is in for this.
