### ISSUE TITLE
Question: Trigger a callback once both streams emit an event

### ISSUE THREAD

**Issue by tusharmath** [Reactive-Extensions/RxJS#876]
```javascript
var observable = Rx.Observable.interval(10);
var response = observable.flatMap(x=> fetchJsonAsObservable(x)); //Is Async

var digest = observable.map(x => createDigestAsObservable(x)); // Non Async

function callback (response, digest) {
   //call once both args are available
}
```

How do I link the two streams such that for each corresponding value of response a digest is created and sent to the callback as arguments?

**Comment by paulpdaniels** [comment]
I would turn it into a single stream with the flatMap overload

```javascript

var observable = Rx.Observable.interval(10);
var combined = observable
                .flatMap(x => fetchJsonAsObservable(x), 
                  (x, response) => { 
                    return {
                     digest : createDigestAsObservable(x), 
                     response : response
                    }; 
               });

combined.subscribe(res => callback(res.response, res.digest));



```

**Comment by tusharmath** [comment]
`res.digest` wouldn't represent the value of the observable right?

**Comment by paulpdaniels** [comment]
Do you need to create an Observable for the digest? If it is non-async then just wrap it directly, `createDigest`.

**Comment by tusharmath** [comment]
That just solves this particular problem, what if I have multiple observables that I want to wait for and execute in parallel and execute a callback function once all of the are executed. 
Something like `Promise.all`

**Comment by tusharmath** [comment]
I think `combineLatest` will do the trick :)

**Comment by paulpdaniels** [comment]
That will fire each time one of them fires.

You probably want `zip`

**Comment by tusharmath** [comment]
Yes!
