### ISSUE TITLE
combineLatest isn't correct working

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#877]
Hi @mattpodwysocki  Looks like that `combineLatest` isn't correct working. Take a look at http://jsbin.com/honija/edit?js,console,output. `btn1` working after `btn2`

**Comment by erykpiast** [comment]
Hmm, I can click `btn1`, then `btn2` and I see message on console. It works also in reversed order.

**Comment by paulpdaniels** [comment]
@xgrommx `CombineLatest` only emits after each `Observable` has at least one value.

**Comment by xgrommx** [comment]
@paulpdaniels I need that it work with any observables and have behavior like `combineLatest`

**Comment by xgrommx** [comment]
@paulpdaniels @eliperkins This approach works as expected http://jsbin.com/honija/edit?js,console,output

**Comment by zetlen** [comment]
I'm having this issue too, using the example code from the [combineLatest documentation](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/combinelatest.md) in Node 0.12.5:

```js
/* Have staggering intervals */
var source1 = Rx.Observable.interval(100)
  .map(function (i) { return 'First: ' + i; });

var source2 = Rx.Observable.interval(150)
  .map(function (i) { return 'Second: ' + i; });

// Combine latest of source1 and source2 whenever either gives a value with a selector
var source = Rx.Observable.combineLatest(
    source1,
    source2
  ).take(4);

var subscription = source.subscribe(
  function (x) {
    console.log('Next: %s', x);
  },
  function (err) {
    console.log('Error: %s', err);
  },
  function () {
    console.log('Completed');
  });

// => Next: First: 0,Second: 0
// => Next: First: 1,Second: 0
// => Next: First: 1,Second: 1
// => Next: First: 2,Second: 1
// => Completed
```

```
    throw e;
          ^
TypeError: undefined is not a function
    at AnonymousObserver.tryCatcher (/Users/james_zetlen/gits/samoan-garden/node_modules/rx/dist/rx.js:59:29)
    at InnerObserver.tryCatcher (/Users/james_zetlen/gits/samoan-garden/node_modules/rx/dist/rx.js:59:29)
From previous event:
```

**Comment by xgrommx** [comment]
@zetlen What is version of Rx?

**Comment by zetlen** [comment]
Oh, dear. Never mind. I somehow did not notice I was on 3.0.1.

**Comment by xgrommx** [comment]
@zetlen Did you read it https://github.com/Reactive-Extensions/RxJS/releases/tag/v3.1.0?

**Comment by zetlen** [comment]
@xgrommx Yes I did, a few minutes ago when I realized my local project was one version behind the docs I was reading.

**Comment by mattpodwysocki** [comment]
Not seeing the issue here, so closing this as working as expected
