### ISSUE TITLE
Add .toPromise to Observable prototype

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/RxJS#88]
Add support for `.toPromise(PromiseCtor)` where you could convert an existing Observable sequence to a [Promises A+ spec compliant](http://promises-aplus.github.com/promises-spec/) version.

eg:

``` js
Rx.Observable.prototype.toPromise = function (promiseCtor) {
    var source = this;
    return new promiseCtor(function (resolve, reject) {
        // No cancellation can be done
        var value, hasValue = false;
        source.subscribe(function (v) {
            value = value;
            hasValue = true;
        }, function (err) {
            reject(err);
        }, function () {
            if (hasValue) {
                resolve(value);
            }
        });
    });
};
```

**Comment by Zolmeister** [comment]
@mattpodwysocki I can't seem to find the docs for this

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/libraries/rx.lite.md
