### ISSUE TITLE
CombineLatest with array parameter: selector does not have an array as parameter

### ISSUE THREAD

**Issue by timotei** [Reactive-Extensions/RxJS#883]
I've stumbled upon the following problem: if I call `combineLatest` with an array of observables, I don't get back an array of the values of those observables, but the array expanded.

```
var obs1 = Rx.Observable.just(1);
var obs2 = Rx.Observable.just(2);

Rx.Observable.combineLatest([obs1, obs2], elements => {
  console.log(typeof elements);
  console.log(elements.length);
}).subscribe(_ => {});
```

That snippet above, as executed in http://jsbin.com/yevaxaxupu/edit?js,console it can be seen that instead of the type to be array & the length  = 2, it's actually just the first value of the observable (1).

Is that even the right way to work? The use case I have is that I don't know how many items I have in the array and I don't even care, cause I will just do a reduce operation (e.g.: sum over everything).

**Comment by xgrommx** [comment]
@timotei  Read it https://github.com/Reactive-Extensions/RxJS/issues/877

**Comment by timotei** [comment]
@xgrommx It's not the same issue at all. In your example you know the exact number of observables you are combining. In mine, not (even if I create just two).

It's related to the fact that when I call combineLatest this happens now:
`[item1, item2, ..., itemn] -> function(item1, item2, ..., itemn) {}`

But it should be (at least from my PoV):
`[item1, item2, ..., itemn] -> function([item1, item2, ..., itemn]) {}`

So, if I give an array, I expect an array with the values

**Comment by roganov** [comment]
@timotei Can't you just use `arguments`?
```
item1, item2, ..., itemn] -> function() {console.log(arguments)}
```
Or in ES6:
```
item1, item2, ..., itemn] -> function(...args) {console.log(args)}
```

**Comment by timotei** [comment]
Oh yes, that worked - I'm using TypeScript! Thanks :)

Still, is this the expected behaviour?

**Comment by mattpodwysocki** [comment]
@timotei yes, this is expected behavior as the selector function has not changed behaviors, just if you omit the selector, then you get an array of results.  This selector behavior has been there since 1.0 timeframe.
