### ISSUE TITLE
Regression with `Observable.prototype.timeout` fails for optional other/scheduler

### ISSUE THREAD

**Issue by david-driscoll** [Reactive-Extensions/RxJS#885]
As per the [current docs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/timeout.md), other and scheduler are supposed to be optional.

The recent change, has added an error when you don't give an other or scheduler argument.
https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/timeout.js#L60

Are the docs wrong, or is this a regression?

**Comment by mattpodwysocki** [comment]
@david-driscoll regression, now fixed
