### ISSUE TITLE
Duplicate identifier 'isEnabled'

### ISSUE THREAD

**Issue by Kylar** [Reactive-Extensions/RxJS#888]
I am trying to get TypeScript definitions for everything in RxJS 3.1.1 including TestScheduler. When I include both rx.all.d.ts and rx.testing.d.ts I get an error because VirtualTimeScheduler is defined in both files.

**Comment by xgrommx** [comment]
@Kylar probably you should to ping @david-driscoll

**Comment by david-driscoll** [comment]
hmm, I'll look into it.

**Comment by mattpodwysocki** [comment]
@david-driscoll any update?

**Comment by david-driscoll** [comment]
I got distracted, looking at this tonight.
