### ISSUE TITLE
Rx.where doesn't contain an example

### ISSUE THREAD

**Issue by josephfinlayson** [Reactive-Extensions/RxJS#890]
`Where` just contains the example for filter https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/where.md

**Comment by xgrommx** [comment]
@josephfinlayson As you can see `filter` is alias for `where` and working identically. More here https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/where.js#L11. I guess this issue can be closed.

**Comment by josephfinlayson** [comment]
Thanks. it's not immediately clear that it's an alias. Perhaps the docs should contain words to that effect?
