### ISSUE TITLE
msopentech.com SSL certificate expired

### ISSUE THREAD

**Issue by sirbarrence** [Reactive-Extensions/RxJS#894]
A link in the [RxJS Wiki about contributions](https://github.com/Reactive-Extensions/RxJS/wiki/Contributions#contributing-code) points to https://cla.msopentech.com/ whose SSL certificate expired on August 28, 2015.

**Comment by mattpodwysocki** [comment]
@sirbarrence yes, the real one should be here: https://cla.microsoft.com/.  Will change our documentation.
