### ISSUE TITLE
Rx.Observable.prototype.delay does not accept Rx.Observable.timer as argument

### ISSUE THREAD

**Issue by elayman** [Reactive-Extensions/RxJS#896]
Rx version 2.X.X had delayWithSelector that accepted an Rx.Observable.timer as the first arg. Rx version 3.1.2 removed delayWithSelector in favor of delay. The documentation for .delay also has this syntax, but the code throws an error "Invalid arguments" if a timer is passed in.

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/delay.md

**Comment by mattpodwysocki** [comment]
@elayman fixed
