### ISSUE TITLE
conditional buffering

### ISSUE THREAD

**Issue by kyp0717** [Reactive-Extensions/RxJS#898]
Hi,
Can  you please help me figure  out how to code this?

I have an observable stream that looks like this:
 ...'XDFD', 'A', 15, 'RDAS', 'B', 'B', 23, 'GGGG', 76 ---> start of observable stream

Right now, the observable (as depicted in the line above) is emitting each value separated by commas.  What I am trying to do is send the stream into another observable and emit arrays that combine values separated by integers.  So the new observable stream would look like
...['XDFD', 'A', 15], ['RDAS', 'B', 'B', 23], ['GGGG', 76] ----> start of new stream.

Can  someone please advise me on how to code this?  Thanks in advance.

**Comment by xgrommx** [comment]
Hi @kyp0717. I think you meant something like that http://jsbin.com/bapuxi/edit?js,console

**Comment by xgrommx** [comment]
Or more simply:
```js
Rx.Observable.prototype.bufferUntil = function(predicate) {
  return this.publish(p => p.buffer(() => p.filter(predicate)).filter(x => x.length > 0));
};

Rx.Observable.of('XDFD', 'A', 15, 'RDAS', 'B', 'B', 23, 'GGGG', 76).bufferUntil(x => Number.isInteger(x)).subscribe(::console.log);
```

**Comment by xgrommx** [comment]
Or if you don't want use composition of operators you can implement it with `Rx.Observable.create`

```js
Rx.Observable.prototype.bufferUntil = function(predicate) {
  return Rx.Observable.create(observer => {
    var buffer = null;
    var oldBuffer = null;
    
    return this.subscribe(t => {
      if(buffer === null) {
        buffer = [];
      }
      buffer.push(t);
      if(predicate(t)) {
        oldBuffer = buffer;
        buffer = null;
        observer.onNext(oldBuffer);
      }
    }, observer.onError.bind(observer), observer.onCompleted.bind(observer));
  });
};
```

**Comment by kyp0717** [comment]
Thank you so much.  I am still new to javascript so it will take me a while to absorb your suggestions and advise.  Will get back to you in a few days hopefully.

**Comment by kyp0717** [comment]
Hi,
Thank you for your solution.  I do have a follow-up question.  I have trouble understanding reason using .publish.refcount method.

Upon reading up on these methods, I now under that using publish and refcount turn the observable from a cold to hot.  So, I am still having a little trouble wrapping my mind around why it was necessary to convert cold to hot observable for this  to work.

Can  you explain?

Thanks,
Ky

**Comment by xgrommx** [comment]
@kyp0717 Sorry, I don't have more time. Please read this one http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/publish.html#arguments

**Comment by kyp0717** [comment]
I believe I understand now.  You need a hot observable that is connectable in real-time because there are actually two  subscription that needs to follow this observable.
These two subscriptions are the published.buffer and published.filter.  Both methods need to operate on the same value over time and thus we need a published and multicast the values to all subscribers.

Thanks!  I think I got it.  Please correct me if I am wrong or verify that I am correct.

**Comment by xgrommx** [comment]
`obs.publish().refCount()` is looks like a reactive property. But probably you are right =)

**Comment by mattpodwysocki** [comment]
@kyp0717 I think @xgrommx has satisfied, so closing
