### ISSUE TITLE
buffering between 2 elements in an observable

### ISSUE THREAD

**Issue by kyp0717** [Reactive-Extensions/RxJS#907]
Hi,
Please help me write this code.  I am trying to retrieve a sequence out of an observable at 2 points.  

I have an stream ( 1,2,3,4,5,6,7,8,9) .  I would like to write a using Rx.Observable.buffer that can retrieve the sequence (2,3,4) from the stream.  Here is my code but it does not work:

-------------- CODE ------------------
var source = Rx.Observable.of(1,2,3,4,5,6,7,8,9)

var sbuf = source.buffer(
  // opening observable element
  Rx.Observable.just(2),
  // closing function
  (x) => {return source.filter( x=> {return x===5})}
  )

var sub = sbuf.subscribe( x => console.log(x))
----- OUTPUT --------------
[ 1, 2, 3, 4 ]

Please help!

Thanks,
Ky

**Comment by xgrommx** [comment]
@kyp0717 Did you mean something like that? http://jsbin.com/vesefe/edit?js,console

**Comment by kyp0717** [comment]
Hi,
Your solution helps a lot.  It helps further my understanding or RxJS.  However, I was hoping to implement a more generalized case using buffer.  Would you be able to provide a solution using the Rx.Observable.buffer?  Again, just curious and wanting to learn more about RxJS.
Thanks,
Ky

**Comment by xgrommx** [comment]
@kyp0717 The same solution which I provided earlier:

```js
var source = Rx.Observable.of(1,2,3,4,5,6,7,8,9,0)

var sbuf = source.publish(p => p.buffer(p.filter(x => x === 2), _ => p.filter(x => x === 4)))

var sub = sbuf.subscribe( x => console.log(x))
```

**Comment by xgrommx** [comment]
Just a pure realization:

```js
Rx.Observable.prototype.bufferWithBounds = function(left, right) {
  return Rx.Observable.create(observer => {
    return this.reduce((acc, next) => {
      if(next >= left && next <= right) {
        return acc.concat(next);
      } else {
        return acc;
      }
    }, []).subscribe(
      observer.onNext.bind(observer), 
      observer.onError.bind(observer), 
      observer.onCompleted.bind(observer));
  });
};

obs.bufferWithBounds(2, 4)
```

**Comment by mattpodwysocki** [comment]
@kyp0717 I think @xgrommx came up with a good enough answer here.  In the future, before opening issues, please check out our gitter channel to get questions answered there before filing an issue.
