### ISSUE TITLE
version 3.1.2 prematurely published to npm

### ISSUE THREAD

**Issue by sirbarrence** [Reactive-Extensions/RxJS#913]
An `npm install` with an Rx requirement like `"rx": "~3.1.0"` in package.json is installing v3.1.2 which is essentially the master branch and not an officially tagged release. It also contains breaking changes in keeping with a master branch but inappropriate for a patch version number bump from .1 to .2.

Master / pseudo-3.1.2 changes the way .throttle() works and removes .throttleFirst() and several other related operators. The only workaround I see for a project depending on "~3.1.0" and the old throttle behavior is to lock the "rx" version in package.json to "3.1.1".

This is also [causing rx.angular's Travis builds to fail on `tests.safeApply.js:20`](https://github.com/Reactive-Extensions/rx.angular.js/pull/96), because it uses the throttle operator.

**Comment by sirbarrence** [comment]
Now that I look again, I was wrong about 3.1.2 not being tagged, but it is also not marked as "Latest release" on [the releases page](https://github.com/Reactive-Extensions/RxJS/releases) which is odd. The releases page also contains no release notes for 3.1.2, which makes it seem like an accident.

The main problem is 3.1.2 contains breaking changes that do not belong in a patch release, especially one with no release notes.

@mattpodwysocki Any idea what's going on?

**Comment by mattpodwysocki** [comment]
@sirbarrence which parts are breaking as part of 3.1.2?

**Comment by sirbarrence** [comment]
.throttle() changes, missing .throttleFirst(), etc

**Comment by sirbarrence** [comment]
Breaking changes were in [commit 5a37fa2](https://github.com/Reactive-Extensions/RxJS/commit/5a37fa289eb88f14d020dd88b7a72cc1f2a75da8).

From that commit it appears there could be others, but I've run into the following personally:

### .throttleFirst()
-  [existed at tag 3.1.1](https://github.com/Reactive-Extensions/RxJS/blob/v3.1.1/src/core/linq/observable/throttlefirst.js) and was not deprecated 
- [gone at 3.1.2](https://github.com/Reactive-Extensions/RxJS/tree/v3.1.2/src/core/linq/observable/throttlefirst.js), so anything using .throttleFirst() breaks

### .throttle()
- was [a deprecated synonym for .debounce() in 3.1.1](https://github.com/Reactive-Extensions/RxJS/blob/v3.1.1/src/core/linq/observable/debounce.js#L45)
- moved to [its own file with new behavior in 3.1.2](https://github.com/Reactive-Extensions/RxJS/blob/v3.1.2/src/core/linq/observable/throttle.js)
- Real world breakage: rx.angular.js Travis build has been [broken](https://travis-ci.org/Reactive-Extensions/rx.angular.js/builds/79300296) ever since it started npm installing Rx 3.1.2 because [tests.safeApply.js uses .throttle()](https://github.com/Reactive-Extensions/rx.angular.js/blob/master/tests/tests.safeApply.js#L14) the 3.1.1 way. If rx.angular's "rx" dependency in package.json is changed from `"*"` to `"3.1.1"`, after another `npm install` the tests pass. Change it to `"3.1.2"` or back to `"*"`, then `npm install`, and the tests fail again.

**Comment by sirbarrence** [comment]
@mattpodwysocki Oops, I was replying to your original question I saw in my email. I see you updated it. 

I'll lock to 3.1.1 for now and hopefully jump to 4.0 & update my throttle calls then.

Thanks.
