### ISSUE TITLE
readme.md async example

### ISSUE THREAD

**Issue by alexeyzimarev** [Reactive-Extensions/RxJS#914]
Shouldn't the root readme.md have subscribe instead of forEach in the second code block, where "getAsyncStockData" is used?

**Comment by xgrommx** [comment]
Hi @alexeyzimarev. `forEach` and `subscribe` is aliases https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/observable.js#L48

**Comment by mattpodwysocki** [comment]
@alexeyzimarev since `subscribe` has an alias with `forEach` it makes little sense to swap the two since we would prefer people use subscribe.  In fact the ES-Observable spec uses [`subscribe`](https://github.com/zenparsing/es-observable/)

**Comment by alexeyzimarev** [comment]
So if you prefer people to use subscribe, why use forEach on the front page? Especially considering other samples where subscribe is used. In particular, on the page where interactive is compared with reactive as forEach vs subscribe. Imho it just adds confusion. Why not use subscribe everywhere in the docs?

**Comment by xgrommx** [comment]
@alexeyzimarev please read this one https://github.com/zenparsing/es-observable#observable
