### ISSUE TITLE
Rx.Observable.fromEvent documentation mistake

### ISSUE THREAD

**Issue by rehia** [Reactive-Extensions/RxJS#915]
I'm using Rx in Node, and I wanted to use `Rx.Observable.fromEvent`.
The event I want to listen emits 3 data:
```javascript
emitter.emit('event', data1, data2, data3);
```

While reading the documentation, it appears that the optional `selector`parameter is exactly what I needed to get all data in the stream.
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromevent.md
But the provided example for the usage of the `selector`does not work.

Here's an example that actually works:

```javascript
var source = Rx.Observable.fromEvent(
    eventEmitter,
    'data',
    function (foo, bar) {
        return { foo: foo, bar: bar };
        // or return { foo: arguments[0], bar: arguments[1] }
    });
```

**Comment by xgrommx** [comment]
@rehia I don't understand what do you mean. In new version of Rx you should use this construction:

```js
var Rx = require('rx');
var EventEmitter = require('events').EventEmitter;

var e = new EventEmitter();

var changes = Rx.Observable.fromEvent(e, 'changes', function (first, second) {
  return { first: first, second: second };
});
```

**Comment by mattpodwysocki** [comment]
@rehia fixed, sorry about that

**Comment by rehia** [comment]
@mattpodwysocki Thanks Matt ! Happy to contribute
@xgrommx Previous version was mentioning:
```javascript
function (args) {
  return { foo: args[0], bar: args[1] };
}
```
