### ISSUE TITLE
Typescript definition for fromNodeCallback isn't quite right

### ISSUE THREAD

**Issue by ccapndave** [Reactive-Extensions/RxJS#922]
The generic definition of `fromNodeCallback` (i.e. when used with a function with no arguments) has a compulsory `selector` argument.

Specifically I think that:

`fromNodeCallback<TResult>(func: Function, context: any, selector: Function): (...args: any[]) => Observable<TResult>;`

should be

`fromNodeCallback<TResult>(func: Function, context: any, selector?: Function): (...args: any[]) => Observable<TResult>;`

**Comment by ccapndave** [comment]
Actually the context should be optional too

**Comment by mattpodwysocki** [comment]
@david-driscoll care to fix that one?

**Comment by david-driscoll** [comment]
Sure thing.
