### ISSUE TITLE
alternative to using prevObservable['catch']()

### ISSUE THREAD

**Issue by kcarl-adb** [Reactive-Extensions/RxJS#923]
How about adding an _ to the end of the name? (i.e. prevObservable:catch_().  Having a standard way to rename an operator when it conflicts with the language would look a lot nicer than doing the above.

**Comment by paulpdaniels** [comment]
I think that _is_ a common way of doing it. It should at least be familiar to most people coming from any Promise Library. At this point it is really only for supporting IE8 and if we create a new alias that need to be deprecated, that is all the more headache for developers down the line.

You could always alias it locally if it is causing problems.

**Comment by kcarl-adb** [comment]
Here is an example line I pulled out of a unit test:  It seems harder to parse.

```var someObservable = Rx.Observable['throw'](new Error())['finally'](function () {```

**Comment by mattpodwysocki** [comment]
@kcarl-adb this only clashes with the language for older, broken browsers such as IE8 and before. If you're only supporting IE9+, then you can feel free to use:
```js
var someObservable = Rx.Observable
  .throw(new Error())
  .catch(Rx.Observable.just(42))
  .finally(function () { console.log('done'); });
```

**Comment by kcarl-adb** [comment]
ok thanks.
