### ISSUE TITLE
[regression] v4.0.0's TypeScript definition don't include Observable.prototype.merge<T>().

### ISSUE THREAD

**Issue by saneyuki** [Reactive-Extensions/RxJS#931]
## environment

- RxJS v4.0.0
- At least, I confirm this regression in [rx.all.d.ts](https://github.com/Reactive-Extensions/RxJS/blob/d5a3691db5fe7e435881477b6e8649b4e0eadfb6/ts/rx.all.d.ts) and [rx.all.es6.d.ts](https://github.com/Reactive-Extensions/RxJS/blob/d5a3691db5fe7e435881477b6e8649b4e0eadfb6/ts/rx.all.es6.d.ts).

## actual

- v4.0.0's type definitions for TypeScript don't include `Observable.prototype.merge<T>().`
   - They includes only `ObservableStatic.merge<T>()`
- I think this is regression because:
  - this is not noted in [release note](https://github.com/Reactive-Extensions/RxJS/releases/tag/v4.0.0)
  - the original definition is still in this repository: https://github.com/Reactive-Extensions/RxJS/blob/7d4fc916c1f296b32402ca1b9eb995d3ee1a0d7a/ts/core/linq/observable/mergeproto.ts

**Comment by mattpodwysocki** [comment]
Once again, @david-driscoll is there a reason for the regression? Did I screw up?

**Comment by david-driscoll** [comment]
Not sure, I'll take a look tonight.

**Comment by mattpodwysocki** [comment]
@david-driscoll appreciate it, that and the `zip` one.  Not sure if I'm doing something wrong here

**Comment by david-driscoll** [comment]
I always take the blame first. :)  It's possible the way things are loaded
through grunt has a hole or two.

**Comment by david-driscoll** [comment]
Sorry been distracted with life... I think I see the problem.

Merge currently lives under https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/mergeconcat.js instead of mergeproto.js, it should be as simple as renaming.

I'm not sure if the zip one is the same, but I'm going to look at these tonight after I get kids squared away. :smile:

**Comment by david-driscoll** [comment]
okay I lied... I looked at the zip one too.

zipproto has been rolled into https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/perf/operators/zip.js and zipproto isn't in the grunt file.  I'll get a pr out for these two tonight.

**Comment by baltie** [comment]
Heh, we looked into this at the same time, see #932. ;) I actually had a fix for the merge operator issue and was just about to create a PR for it. Now I see you have the exact same fix in mind. I'll leave you to it, @david-driscoll. :)

**Comment by saneyuki** [comment]
This is also fixed by #970 in the same way as #932.
