### ISSUE TITLE
Rx.Observable.fromEvent(...) typescript definition lacking for window source

### ISSUE THREAD

**Issue by patsissons** [Reactive-Extensions/RxJS#937]
I had to manually add a definition for attaching to window events.

```typescript
/**
 * Creates an observable sequence by adding an event listener to the matching window.
 * @param {Object} window The Window to attach a listener.
 * @param {String} eventName The event name to attach the observable sequence.
 * @param {Function} [selector] A selector which takes the arguments from the event handler to produce a single item to yield on next.
 * @returns {Observable} An observable sequence of events from the specified element and the specified event.
 */
fromEvent<T>(window: Window, eventName: string, selector?: (arguments: any[]) => T): Observable<T>;
```

I am referencing the `rx.all.d.ts` definitions.

**Comment by mattpodwysocki** [comment]
@david-driscoll worth adding to our TS files?

**Comment by david-driscoll** [comment]
Probably can't hurt
On Mon, Oct 5, 2015 at 9:07 AM Matthew Podwysocki <notifications@github.com>
wrote:

> @david-driscoll <https://github.com/david-driscoll> worth adding to our
> TS files?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reactive-Extensions/RxJS/issues/937#issuecomment-145522411>
> .
>
-- 
Thanks,
David

**Comment by patsissons** [comment]
@mattpodwysocki it appears I have an outdated definition file. My signatures were using NodeList and Node instead of EventTarget. looks like c80d792 updated the definitions.

**Comment by mattpodwysocki** [comment]
@patsissons ok, closing then
