### ISSUE TITLE
Rx.Observable.timer(0, x) produces values immediately

### ISSUE THREAD

**Issue by johnnyelwailer** [Reactive-Extensions/RxJS#941]
I have an `Rx.Observable.timer(0, 1000)`, expecting it to yield a value every 1000ms. However, the values will be generated immediately.
When using `Rx.Observable.timer(1000, 1000)`, the values will be generated as expected, after an initial delay of 1000ms.
[See this Fiddle](http://jsfiddle.net/moguwhnp/1/)
Using Rx.all.js v4.0.0

**Comment by youngnh** [comment]
I have hit the same issue working through the examples in https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/creating.md and found that its for any `Rx.Observable.timer` call with a period that doesn't match the starting delay.
