### ISSUE TITLE
shareLatest?

### ISSUE THREAD

**Issue by ronag** [Reactive-Extensions/RxJS#942]
In our code we very often end up with the following pattern:

```javascript
    .shareValue(undefined)
    .filter(x => typeof x !== 'undefined')
```

I wonder if there is a method (.e.g. `shareLatest`) that we've missed and which already does this?

**Comment by xgrommx** [comment]
@ronag `shareValue

**Comment by ronag** [comment]
@xgrommx: Unfortunately  `publishLast` will only give me the *last* value not the *latest*.

**Comment by paulpdaniels** [comment]
@ronag You could probably just use 

```javascript

.shareReplay(1)

```

**Comment by ronag** [comment]
@paulpdaniels: That will as far as I know only give me the *first* value. Replay doesn't use a circular buffer as one might believe.

**Comment by xgrommx** [comment]
@ronag I don't understand what you want. Do u need last or first value which should be share with other subscriptions?

**Comment by xgrommx** [comment]
@ronag I can be wrong but I was found this solution which emit last value:

```js
var o = Rx.Observable.from([1,2,3,4,5]).publish(p => p.last());
```

**Comment by paulpdaniels** [comment]
@ronag If you have buffer size of 1 then by definition it *is* the latest value. And yes it is a [circular buffer](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/subjects/replaysubject.js#L65-L89), assuming you set a max buffer size.

**Comment by xgrommx** [comment]
@ronag @paulpdaniels I realized what wanted @ronag. He need get latest value for another observable. Please correct me if I wrong.
