### ISSUE TITLE
Filter if value exists (or doesn't)

### ISSUE THREAD

**Issue by tusharmath** [Reactive-Extensions/RxJS#948]
often times I write a filter where I am checking if there is a value in the stream. Eg -

```javascript
stream.filter(x => x)
```

Is there a function that can do the same without me having to pass the default `identity` function, ie. `x => x` ?

**Comment by xgrommx** [comment]
@tusharmath Take a look at http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/isempty.html

**Comment by tusharmath** [comment]
@xgrommx It is not at all like filter since it only emits once.

**Comment by erykpiast** [comment]
So you simply want to filter falsy values, right?

**Comment by tusharmath** [comment]
@erykpiast exactly

**Comment by unao** [comment]
`.filter(Boolean)` should do the job.

**Comment by tusharmath** [comment]
Isnt this more verbose than the arrow func?

On Thu, Oct 8, 2015, 1:24 AM artur grzesiak <notifications@github.com>
wrote:

> .filter(Boolean) should do the job.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reactive-Extensions/RxJS/issues/948#issuecomment-146309693>
> .
>
-- 
Regards,
Tushar Mathur.
www.tusharm.com

**Comment by mattpodwysocki** [comment]
@tusharmath not at the moment though but we are willing to take suggestions on how to make it easier. It gets tricky if you want to do that automatically especially around whether it is truly a true/false value or just truthy/falsy which we know is quite a rabbit hole in JavaScript.

**Comment by tusharmath** [comment]
@mattpodwysocki Thats awesome.
So there are 4 typical cases that most JS programmers deal with —
1. `isTruthty()`:  `stream.filter(x => !!x === true)` 
2. `isFalsey()`:  `stream.filter(x => !!x === false)` 
3. `isDefined()`:  `stream.filter(x => x !== undefined)` 
4. `isntDefined()`:  `stream.filter(x => x === undefined)` 

Though I was looking for something like `isntDefined()` the other three also make sense to me.

**Comment by tusharmath** [comment]
I would be glad to create a pull request for this, if you think this is a required feature?

**Comment by roganov** [comment]
Why do we need this in the library if it can be super easily implemented by the clients? I don't think that it worth expanding already huge RxJS' API.

**Comment by tusharmath** [comment]
@roganov I agree its quite easy to implement. But if everyone keeps implementing it, then it would be again the [DRY](https://www.wikiwand.com/en/Don't_repeat_yourself) principle.

**Comment by roganov** [comment]
For me, `filter(Boolean)` is always enough.

**Comment by tusharmath** [comment]
this will filter `false` as well. I just want to check `undefined` values.

**Comment by jadbox** [comment]
Slightly off topic for Boolean, I'd like Filter to accept values in a way that Map does: `map("success")` could have a matching operation `filter("success")`. I mention this here as part of this thread as Filter should be able to check whether it's a Boolean for false-y checks as well as other values for equality checks.

**Comment by tusharmath** [comment]
As per the comments above, I think `Boolean` does a pretty neat job.

**Comment by QuentinFchx** [comment]
When using `.filter(Boolean)` I lose the type inference. Is it expected ?
```ts
foo$ = new BehaviorSubject(true);

foo$
.filter(Boolean) // Observable<any>

foo$
.filter(v => !!v)> // Observable<boolean>
```
