### ISSUE TITLE
Possibly unhandled TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null

### ISSUE THREAD

**Issue by rzachariah** [Reactive-Extensions/RxJS#949]
Hi there,

I'm running an Rx query, and it occasionally throws the following error.

	2516Z Possibly unhandled TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at Object.Rx.helpers.isIterable (/app/node_modules/rx/dist/rx.experimental.js:90:13)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at InnerObserver.onNext (/app/node_modules/rx/dist/rx.js:2017:55)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at InnerObserver.tryCatcher (/app/node_modules/rx/dist/rx.js:59:31)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at AutoDetachObserverPrototype.next (/app/node_modules/rx/dist/rx.js:5214:51)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/app/node_modules/rx/dist/rx.js:1625:31)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at InnerObserver.onNext (/app/node_modules/rx/dist/rx.js:4792:14)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at /app/node_modules/rx/dist/rx.js:2306:11
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at tryCatcher (/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at Promise._settlePromiseFromHandler (/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at Promise._settlePromiseAt (/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at Promise._settlePromises (/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at Async._drainQueue (/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at Async._drainQueues (/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
	panorama-1 | 2015-10-07T10:42:19.795852516Z     at processImmediate [as _immediateCallback] (timers.js:374:17)

I found the isIterable function that throws the error in the rx-js codebase.

https://github.com/Reactive-Extensions/RxJS/blob/d7f64777c9f0b46f7d649c7b82a59733c86eee1a//src/core/headers/enumeratorheader.js#L11

My query is fairly long, and I'm not sure which part is causing this. Since there's stuff about request-promise in the stack, perhaps it's something in here:

	var rp = require('request-promise'),
			Rx = require('rx'),
			winston = require('winston');	
	
	// Hot observable. Uses sharing and automatic disposal. No caching.
	var QuotesDriver = function() {
		
		var baseUrl = 'http://security:3000';					// prod
	
		// symbols is an array of symbols
		this.quotes = function(symbols) {
			var symbolObs = Rx.Observable.return(symbols);
			return this.quotesWithChangingInterest(symbolObs);
		}
	
		// symbolInterestObs is an IObservable of symbol arrays, representing changing interest in symbols
		this.quotesWithChangingInterest = function(symbolInterestObs) {
			return distinctQuotes(symbolInterestObs)
				.finally(function() { winston.info('Closing quotes stream'); })
				.publish()
				.refCount();
		}
		
		var distinctQuotes = function(symbolInterestObs) {
			return filtered(symbolInterestObs)
				.groupBy(function (quote) { return quote.Symbol; })
				.select(function(g) {
					return g.distinctUntilChanged(function(quote) { return quote.Last; })
							.finally(function(){winston.info('Closing quotes stream for ' + g.key);})
				})
				.mergeAll();
		}
		
		var filtered = function (symbolInterestObs) {
			return repeatQuotesRequest(symbolInterestObs).where(function(quote) {
				return (quote != null) && (typeof(quote.Symbol) != 'undefined') && (typeof(quote.Last) != 'undefined'); 
			})
		}
	
		var repeatQuotesRequest = function (symbolInterestObs) {
			return Rx.Observable.interval(2000)
								.combineLatest(symbolInterestObs, function(i, symbolInterest) {
									return quotesRequest(symbolInterest);
								})
								.switch()
		}
		
		var quotesRequest = function(symbols) {
			return Rx.Observable.fromPromise(getQuotesNetworkCall(symbols))
								.select(function(body) {
									try {
										return JSON.parse(body);	
									}
									catch (error) {
										winston.error(error);
										return {Quotes:[]}
									}
								})
								.selectMany(function(batch) {
									return batch.Quotes;
								});
		}
	
		var getQuotesNetworkCall = function (symbols) {
			var symbolQuery = getSymbolQuery(symbols);
			var apiUrl = baseUrl + '/Prices?Identifiers=' + symbolQuery; 
			winston.info('Network call to ' + apiUrl);
			return rp(apiUrl);
		}
		
		var getSymbolQuery = function (symbols) {
			var queryBuilder = '';
			for(var i = 0; i < symbols.length; i++)
			{
				if(i > 0)
					queryBuilder = queryBuilder + ';';
				queryBuilder = queryBuilder + symbols[i];
			}
			return queryBuilder;
		}
	}
	
	module.exports = QuotesDriver;

**Comment by mattpodwysocki** [comment]
@rzachariah fixed as per:
```js
  var isIterable = Rx.helpers.isIterable = function (o) {
    return o && o[$iterator$] !== undefined;
  };
```

Should be fixed as per 4.0.4
