### ISSUE TITLE
Rx.Observable.fromEvent doesn't work for 4.0.1 version

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#962]
Hello @mattpodwysocki. Looks like `Rx.Observable.fromEvent` doesn't work for 4.0.1 version but for 4.0.0 this to work as expected. You can reproduce this bug with this jsbin http://jsbin.com/bomoso/edit?html,js,console,output

**Comment by paulpdaniels** [comment]
@xgrommx I submitted a fix for it in #959.

**Comment by IDSFN** [comment]
Guys i'm using 5.0.0-beta.2 and it still not firing anything ?!

`const elem = document.querySelector('input');`
`var keyups = Observable.fromEvent(elem, 'click');`
`keyups.subscribe(console.log);`

**Comment by jmalonzo** [comment]
@IDSFN Rx 5.x is different from this repo - https://github.com/ReactiveX/RxJS. And IIRC, they don't support DOM events in .fromEvent as of yet.

**Comment by IDSFN** [comment]
@jmalonzo downgrading from 5.x to 4.x that's a lot!
if the community uses a new good way to handle that, Why should I bother! what makes me angry is why it supports JQUERY ? JUST WHY
a very slow library not useful anymore, 2016
