### ISSUE TITLE
fromPromise not working with jQuery promises

### ISSUE THREAD

**Issue by kkroening** [Reactive-Extensions/RxJS#966]
Creating an observable from a jQuery promise using `fromPromise` seems to have stopped working in 4.0.1.  The following works in 4.0.0 but not 4.0.1 or later:
```
Rx.Observable.fromPromise(jQuery.get(url))
```

Is this the correct way to create observables from jQuery promises?

FWIW, using `fromPromise` with an RSVP promise seems to work in 4.0.0 and 4.0.2 but not 4.0.1.  I wonder if this is related to the `fromEvent` issue in #962...

**Comment by xgrommx** [comment]
@kkroening What is your version of jQuery?

**Comment by mattpodwysocki** [comment]
@kkroening no, nothing has changed with `fromPromise` at all since 4.0 dropped, so there's something else at work here.

**Comment by xgrommx** [comment]
@mattpodwysocki Probably if @kkroening to use old version of jQuery he should append `.promise()` to `jQuery.get(url)` => `jQuery.get(url).promise()` and this should be working

**Comment by mattpodwysocki** [comment]
@kkroening cannot reproduce using the latest RxJS:

```html
<script src="https://code.jquery.com/jquery-2.1.4.js"></script>
<script src="rxjs/dist/rx.all.js"></script>
<script>
var source = Rx.Observable.fromPromise($.get('http://google.com'));
source.subscribe(
  function (x) { console.log('Next: %s', x); },
  function (e) { console.log('Error: %s', e); }
);
</script>
// => Error: [Object]
```
