### ISSUE TITLE
resultSelector in combineLatest doesn't seem to be optional

### ISSUE THREAD

**Issue by warseph** [Reactive-Extensions/RxJS#967]
The documentation states that the resultSelector argument can be omitted and a list with the elements will be yielded (https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/combinelatest.md#arguments)
However this doesn't seem to work. A quick example in coffee:

```coffee
a = Rx.Observable.range 1, 5
b = Rx.Observable.just 'test'
log = (name) -> (args...) -> console.log "#{name}: #{util.inspect args}"

a.combineLatest(b).forEach log('next'), log('error'), log('complete')
# error: [ [TypeError: resultSelector.apply is not a function] ]

a.combineLatest(b, (args...) -> args).forEach log('next'), log('error'), log('complete')
# next: [ [ 1, 'test' ] ]
# next: [ [ 2, 'test' ] ]
# next: [ [ 3, 'test' ] ]
# next: [ [ 4, 'test' ] ]
# next: [ [ 5, 'test' ] ]
# complete: []
```

Is this an actual issue or am I doing something wrong? I've also seen the same behavior when using `Rx.Observable.zip`

Thanks!

**Comment by xgrommx** [comment]
@warseph What is your version what you use?

**Comment by mattpodwysocki** [comment]
@warseph this has been the acceptable behavior since RxJS 3.0, so if you're using a previous version, then that will cause an issue.

**Comment by warseph** [comment]
You're right @mattpodwysocki, I was using 2.*, my bad, I just updated and it works fine, thank you both!!
