### ISSUE TITLE
A property extractor for map, do etc.

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#968]
Hello @mattpodwysocki What if I will try add support for a new feature like a `property extractor`? For example we can do with it: 

```js
Rx.Observable.fromEvent(el, 'click').map('test') or .map(1) or .map(-1)`
```

Almost the same approach in Bacon.

**Comment by paulpdaniels** [comment]
@xgrommx you mean like [`pluck`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/pluck.js)?

**Comment by xgrommx** [comment]
@paulpdaniels `pluck` cannot get property deeply like a `foo.bar.1.a`

**Comment by mattpodwysocki** [comment]
@xgrommx I think @paulpdaniels has the right answer here, pluck is your friend.  As for the `.map(1)` and `map(-1)`, that's been supported since 2.x.

Not only that, but ours is recursive, whereas others such as lo-dash and underscore are single deep.

**Comment by paulpdaniels** [comment]
@xgrommx yes it can, just pass it in as `pluck('foo', 'bar', 1, 'a')`

**Comment by mattpodwysocki** [comment]
@paulpdaniels :+1:

**Comment by xgrommx** [comment]
@paulpdaniels look like ugly but ok =)

**Comment by mattpodwysocki** [comment]
@xgrommx you cannot do it the other way such as `pluck('foo.bar.1.a')` because that could be a valid property.  For example, this is perfect valid:
```js
var obj = {};
obj['foo.bar.1.a'] = 42;
```

So, parsing on the dots would not get us anywhere.
