### ISSUE TITLE
Rx.Observable.prototype.timeout not working

### ISSUE THREAD

**Issue by jlVidal** [Reactive-Extensions/RxJS#969]
Hello,

I was playing with Rx, and this sample:
```javascript
/* With no other */
var source = Rx.Observable
  .just(42)
  .delay(5000)
  .timeout(200);

var subscription = source.subscribe(
  function (x) {
    console.log('Next: %s', x);
  },
  function (err) {
    console.log('Error: %s', err);
  },
  function () {
    console.log('Completed');
  });
```
 Give me this error:
c:\node\ddp\node_modules\rx\dist\rx.time.js:853
            subscription.setDisposable(other.subscribe(o));
                                            ^

TypeError: Cannot read property 'subscribe' of undefined
    at c:\node\ddp\node_modules\rx\dist\rx.time.js:853:45
    at schedule [as _onTimeout] (c:\node\ddp\node_modules\rx\dist\rx.js:1288:79)
    at Timer.listOnTimeout (timers.js:89:15)

Process finished with exit code 1

Node: v4.1.1
RxJs from npm: 4.0.4

**Comment by jlVidal** [comment]
To fix this error/exception on node.js I just need to change:

```javascript```
 .timeout(200);
```
to
```javascript``
 .timeout(200,Rx.Observable.empty());
```

I think is just a problem with the documentation and the samples provided on:
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/timeout.md

Thanks @Frikki for the help

**Comment by mattpodwysocki** [comment]
Fixed

**Comment by deanius** [comment]
This has resurfaced - I have a JSBin which reproduces it here:
https://jsbin.com/yumeke

Using `4.1.0/rx.all.min.js` and the RxJS sample code specified here:
http://reactivex.io/documentation/operators/subscribeon.html

```
/* Change from immediate scheduler to timeout */
var source = Rx.Observable.return(42, Rx.Scheduler.immediate)
    .subscribeOn(Rx.Scheduler.timeout);

var subscription = source.subscribe(
    function (x) { console.log('Next: ' + x); },
    function (err) { console.log('Error: ' + err); },
    function () { console.log('Completed'); });
```
