### ISSUE TITLE
Why isn't this example working?

### ISSUE THREAD

**Issue by lifeiscontent** [Reactive-Extensions/RxJS#972]
I'm trying to learn more about RxJS but this example: http://jsfiddle.net/staltz/4gGgs/27/ is using old RxJS code, so I was wondering why the example below is not working as expected

http://codepen.io/lifeiscontent/pen/ojGwzE?editors=101

**Comment by mattpodwysocki** [comment]
Because `throttle` is the incorrect operator. During the 2.x timeframe, `throttle` meant what `debounce` means (long story). Fixed it for you with this example:
http://jsfiddle.net/4gGgs/294/

**Comment by lifeiscontent** [comment]
@mattpodwysocki do you think you could update the codepen example? the jsfiddle example is still using the old versions and I'm still lost.

**Comment by mattpodwysocki** [comment]
@lifeiscontent sure, sorry about closing it until we get that working.  What is your desired behavior?  The same as the previous?

**Comment by mattpodwysocki** [comment]
@lifeiscontent this should work: http://codepen.io/anon/pen/ojowep?editors=101

**Comment by lifeiscontent** [comment]
@mattpodwysocki Ah, I see. so both throttle calls need to be debounced, do you have any recommended reading material to understand RxJS Operators better? some of the docs can be a little terse. Thanks for helping me learn :+1:

**Comment by mattpodwysocki** [comment]
@lifeiscontent if you want videos, these are probably the best you can find: https://egghead.io/series/introduction-to-reactive-programming

**Comment by blesh** [comment]
FYI: @lifeiscontent ... I think the video about a "throttled buffer" on Egghead is looking at the "old" throttle, which is now debounce. :) So, just switch that in those examples. Haha.
