### ISSUE TITLE
Rx.Notification.prototype.accept shouldn't require all parameters

### ISSUE THREAD

**Issue by ccapndave** [Reactive-Extensions/RxJS#974]
Currently `Rx.Notification.prototype.accept(onNext, onError, onCompleted)` will throw an error like `Uncaught TypeError: onCompleted is not a function` if one of the functions is not defined.

It would be very helpful if the parameters were optional (at least `onError` and `onCompleted`).

**Comment by ccapndave** [comment]
Note that this is in line with the Typescript definitions, which defined `onError` and `onCompleted` to be optional.

**Comment by mattpodwysocki** [comment]
@ccapndave I'm not quite sure what your use case is here because I can't reproduce your issue.  I would also need to see a reproduction of this.

For example, this works fine:
```js
/* onNext calls only */
var n = Rx.Notification.createOnNext(42);
n.kind
// => 'N'
n.accept(function (x) { console.log(x); });
// => 42

/* onError calls only */
var n = Rx.Notification.createOnError(new Error());
n.kind
// => 'E'
n.accept(null, function (x) { console.log(x); });
// => [Error]

/* onError calls only */
var n = Rx.Notification.createOnCompleted();
n.kind
// => 'C'
n.accept(null, null, function (x) { console.log('done'); });
// => 'done'
```

**Comment by xgrommx** [comment]
@mattpodwysocki Try to apply some observer to n.accept.

**Comment by mattpodwysocki** [comment]
@xgrommx ok, still not seeing any errors...

```js
var Rx = require('./rxjs/.');

/* onNext calls only */
var n = Rx.Notification.createOnNext(42);
console.log(n.kind);
// => 'N'
n.accept(Rx.Observer.create(function (x) { console.log(x); }));
// => 42

/* onError calls only */
var n = Rx.Notification.createOnError(new Error());
console.log(n.kind);
// => 'E'
n.accept(Rx.Observer.create(null, function (x) { console.log(x); }));
// => [Error]

/* onError calls only */
var n = Rx.Notification.createOnCompleted();
console.log(n.kind);
// => 'C'
n.accept(Rx.Observer.create(null, null, function () { console.log('done'); }));
// => 'done'
```

**Comment by ccapndave** [comment]
I can reproduce it like this:

```
Rx.Observable
  .just(true)
  .delay(1000)
  .materialize()
  .subscribe(mat => mat.accept(
    _ => console.log(_)
  ));
```
```
> true
> rx.all.js:1581 Uncaught TypeError: onCompleted is not a function
```

**Comment by xgrommx** [comment]
@mattpodwysocki :
```js
var observer = Rx.Observer.create(x => x);
var notification = Rx.Notification.createOnNext(42);
console.log(notification.accept(observer));
```

Should be `42` but I got `undefined`

**Comment by mattpodwysocki** [comment]
@xgrommx no, it shouldn't be `42`, it should be `undefined`, because `Rx.Observer` does not return any values from any of its actions. If you read the [tests](https://github.com/Reactive-Extensions/RxJS/blob/master/tests/core/notification.js#L54-L96) you'll need a custom `Observer` just as I had to create one here.

**Comment by mattpodwysocki** [comment]
@ccapndave I see where you are getting tripped up because the documentation is correct, although only if you know what you're looking for, eg what `kind` the Notification is, 'N', 'E', or 'C' (which you should be doing btw), but since you're not doing that, yes, the `onCompleted` will fire when you have not provided a handler for it. I have since updated the documentation to make them all necessary, including the TypeScript definitions (which were wrong).

**Comment by ccapndave** [comment]
Any reason why they can't be optional though (or is it for parity with Rx on other platforms)?  Otherwise you need to write:

```
$stream
  .materialize()
  .subscribe(mat => mat.accept(
    _ => console.log(_),
    _ => _,
    () => void 0
  ));
```

which doesn't look so pretty.  Checking for `kind` in an if or switch is even less pretty.

**Comment by mattpodwysocki** [comment]
@ccapndave yes, it is indeed for parity. If you look at our usages of `materialize` for example in `delay`, you see that we are indeed checking for which type it is and deciding our action based upon that. That was why it was created so we had a single stream where we could easily decide where each one went.
