### ISSUE TITLE
Behavior of #publish

### ISSUE THREAD

**Issue by Nupf** [Reactive-Extensions/RxJS#977]
When running this code
```javascript
// logs -> parent: 1, parent: 2, parent: 3
var parent = Rx.Observable.from([1,2,3])
      .map(i => {
        console.log('parent:', i);
        return i;
      })
      .publish();

// should log -> child: 1, child: 2, child: 3 but nothing happens
var child = parent
      .map(i => {
        console.log('child:', i);
        return i;
      })
      .publish();

parent.subscribe();
child.subscribe();

parent.connect();
child.connect();
```
Only parent seems to be executed and log values - I don't know if this expected behavior.

I want to share parent amongst multiple child observables (a child being a mapped version of the parent observable).

These child observables themselves can possibly be parents to further child observables (thus each observable has to be published).

Thanks!

PS:

This better represents what I'm trying to accomplish while being more verbose. 
Each child / map() should receive the same values and each observable should only execute once.

```javascript
var parent = Rx.Observable.from([1,2,3])
      .map(i => {
        console.log('parent', i);
        return i;
      })
      .publish();

var child = parent
      .map(i => {
        console.log('child', i);
        return i;
      })
      .publish();

var grandchild1 = child
      .map(j => {
        console.log('grandchild1', j);
        return j;
      })
      .publish();

var grandchild2 = child
      .map(j => {
        console.log('grandchild2', j);
        return j;
      })
      .publish();

parent.subscribe( );
child.subscribe();
grandchild1.subscribe();
grandchild2.subscribe();

parent.connect();
child.connect();
grandchild1.connect();
grandchild2.connect();

```

**Comment by xgrommx** [comment]
@Nupf  Try `replay` https://jsbin.com/tofoji/edit?js,console

**Comment by Nupf** [comment]
@xgrommx Thanks! 
Your reply led me to experiment with moving the connect() statements around - as apparently replaying only 1 value is enough to make everything work :). 

I don't really know why the version in the question did not work at all, but this way actually makes more sense and works completely.

https://jsbin.com/yadawatege/edit?js,console
````javascript
  var parent = Rx.Observable.from([1,2,3])
        .map(i => {
          console.log('parent', i);
          return i;
        })
        .publish();

  var child = parent
        .map(i => {
          console.log('child', i);
          return i;
        })
        .publish();

  var grandchild1 = child
        .map(j => {
          console.log('grandchild1', j);
          return j;
        })
        .publish();

  var grandchild2 = child
        .map(j => {
          console.log('grandchild2', j);
          return j;
        })
        .publish();

  parent.subscribe( );
  child.subscribe();
  grandchild1.subscribe();
  grandchild2.subscribe();

  // notice the reversed order of connecting the observables - children first
  grandchild1.connect();
  grandchild2.connect();
  child.connect();
  parent.connect();
````

**Comment by xgrommx** [comment]
Also you can create shareable observables:

```js
var parent = Rx.Observable.from([1,2,3])
      .map(i => {
        console.log('parent', i);
        return i;
      })
      .shareReplay(1)

var child = parent
      .map(i => {
        console.log('child', i);
        return i;
      })
      .shareReplay(1)

var grandchild1 = child
      .map(j => {
        console.log('grandchild1', j);
        return j;
      })
      .shareReplay(1)

var grandchild2 = child
      .map(j => {
        console.log('grandchild2', j);
        return j;
      })
      .shareReplay(1)

parent.subscribe( );
child.subscribe();
grandchild1.subscribe();
grandchild2.subscribe();
```

And you don't need use `connect`

**Comment by Nupf** [comment]
Thanks again!

I didn't konw that was possible. For clarification, I decided against share() early on, as I need all observers to get the same values
>To ensure all subscribers start at exactly the same time and get the exact same values, refCount can not be used. Either ConnectableObservable with a manual, imperative invocation of connect needs to be done, or the variant of publish(function) which connects everything within the function before connecting the upstream. - [wedding party on refCount](http://nerds.weddingpartyapp.com/tech/2015/01/21/rxjava-share-publish-refcount-and-all-that-jazz/)

Your suggestion of shareReplay() works and produces nicer looking code - I wonder at what cost though. 

If I understand shareReplay right this trades memory (caching elements for replay) for automatic connection (refCount) of the observables - correct?

**Comment by xgrommx** [comment]
Welcome =) You need read about difference between hot and cold observables. In your case you use cold observable.

**Comment by mattpodwysocki** [comment]
@Nupf are we good to close this off then?

**Comment by Nupf** [comment]
Yep, sorry.
