### ISSUE TITLE
Subscriber getting events twice on Observable

### ISSUE THREAD

**Issue by tetriscode** [Reactive-Extensions/RxJS#981]
Using RxJS 2.5, I have folder of 'strategies' that developers can drop in and integrate with a task runner. The goal was to call a notify method on the array of tasks that are dropped in a directory and implement the appropriate functions. This works fine with one exception. The subscriber to the is getting all the events twice. Notify is sending an email and the email will get sent twice. 

```
_.keys(strategies).map(function (key) {
   strategies[key].notify(stockStream);
});
```

```
  returnObject.notify = function(stream) {

    var htmlStr = '<html><body>';
    var buyersStr = '<table border="1"><tr><th>Symbol</th><th>Last</th><th>Streak Price</th></tr>';
    var sellersStr = '<table border="1"><tr><th>Symbol</th><th>Last</th></tr>';
    var buyers = stream.filter(function(stock){
      if (stock.daysDown === 3 && stock.change < 0 && stock.isNas) {
        return true;
      }
      return false;
    }).map(
      function(item){
        var str = '<tr>';
        str += '<td>' + item.symbol + '</td>';
        str += '<td>'+item.last+'</td>';
        str += '<td>'+item.streakPrice+'</td>';
        str += '</tr>';
        return str;
      }).reduce(function(acc,str){
        return acc + str;
      },'');
```

This happens if I use either Object.keys or collection functions in lodash.

**Comment by paulpdaniels** [comment]
2.5 is a fairly old version. Can you try with the latest (4.0.6)?

**Comment by tetriscode** [comment]
@paulpdaniels used a node module export improperly and created a global. Observable was being sent to two functions. Works fine for 2.5 and 4.0.6. Sorry for the distraction.
