### ISSUE TITLE
Easy way to compose functionality?

### ISSUE THREAD

**Issue by YourDeveloperFriend** [Reactive-Extensions/RxJS#982]
I was wondering if there was a way to compose functionality in order to create easy-to-read DRY applications.

Here's a simple example in javascript:

```javascript
// Enter Press
var $input = document.getElementById('myInput');
var enterPress$ = Rx.Observable.fromEvent($input, 'keypress')
.filter(function(ev) {
  return ev.keyCode === 13;
}).pluck('target', 'value');
```

In order to make this DRY, I'd have to do something similar to the following:

```javascript
// Enter Press
var $input = document.getElementById('myInput');
var enterPress$ = enterPress(Rx.Observable.fromEvent($input, 'keypress'));
function enterPress(observ$) {
  return observ$.filter(function(ev) {
    return ev.keyCode === 13;
  }).pluck('target', 'value');
}
```

This makes it difficult to read from left to right, and with multiple little transformations like this, it becomes extremely difficult to read. I wonder if there's a simple way to combine those two functions like this:

```javascript
// Enter Press
Rx.Observable.prototype.transform = function(fn) {
  return fn(this);
};
var $input = document.getElementById('myInput');
var enterPress$ = Rx.Observable.fromEvent($input, 'keypress')
.transform(enterPress);

function enterPress(observ$) {
  return observ$.filter(function(ev) {
    return ev.keyCode === 13;
  }).pluck('target', 'value');
}
```

I'm assuming something like this exists. If not, I can create a pull request, but I'm not sure if the way I'm doing this follows proper RFP programming standards.

**Comment by xgrommx** [comment]
@YourDeveloperFriend We have discussion about this  https://github.com/Reactive-Extensions/RxJS/issues/863. But in your case you can use http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/let.html

**Comment by YourDeveloperFriend** [comment]
Awesome, thanks!

**Comment by tomchentw** [comment]
For those who came here looking for `RxJava`'s [compose][compose] method, there's a [let][let] operator in `RxJS` has the same functionality.

The link by @xgrommx is the demo: http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/let.html

[compose]: http://reactivex.io/RxJava/javadoc/rx/Observable.html#compose(rx.Observable.Transformer)
[let]: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/let.md
