### ISSUE TITLE
BehaviorSubject.prototype.getValue() is not working, the function is not there or docs are outdated

### ISSUE THREAD

**Issue by ognjenb** [Reactive-Extensions/RxJS#985]
BehaviorSubject.prototype.getValue() is not working, the function is not there or docs are outdated.

http://jsbin.com/wajorugexa/edit?html,js,console

**Comment by stefanonepa** [comment]
try with 

.value

**Comment by ognjenb** [comment]
Thanks, thats working. Is this a workaround and there should be a getter function?

**Comment by stefanonepa** [comment]
I'm sorry it's just a workaround, I'm not a member of the dev team... :8ball: 

I think the problem was that you didn't use the last version:
https://cdnjs.cloudflare.com/ajax/libs/rxjs/4.0.6/rx.all.js

//it seems to be a better answer :laughing:

**Comment by ognjenb** [comment]
Great! Thanks @stefanonepa . Yes, it looks like bumping up major versions is going quite fast :)

Closing.
