### ISSUE TITLE
IE8 support is broken

### ISSUE THREAD

**Issue by jpotterm** [Reactive-Extensions/RxJS#986]
IE8 fails to load RxJS because `src/core/internal/errors.js` uses `Object.create` before it is polyfilled by `src/core/internal/polyfills.js`. As far as I can tell the last good version is `3.1.1`.

Another more recent problem is that `src/core/internal/polyfills.js` uses `document.createEvent` which isn't supported by IE8. The last good version for this seems to be `4.0.0`.

The README says RxJS supports IE6+ so these are bugs.

**Comment by mattpodwysocki** [comment]
@jpotterm can you verify the fix please?

**Comment by jpotterm** [comment]
Those commits fix the errors I was getting, but now I get a new error in IE8. With the following example I get "Object doesn't support property or method 'call'".

```javascript
var stream = Rx.Observable.interval(1000).debounce(200);
stream.subscribe(log);

function log() {
    console.log('Test');
}
```

It only seems to happen with the `debounce` method according to my very limited testing. Thanks for looking into it!

**Comment by mattpodwysocki** [comment]
@jpotterm I think that has to do with `setTimeout.call(null, fn, dt)` which doesn't seem to be supported.  Very strange...

**Comment by mattpodwysocki** [comment]
@jpotterm can you verify this works again?

**Comment by jpotterm** [comment]
Ok, it looks like RxJS is working well for me in IE8 now. Thanks!

RxJS-DOM still isn't working, so I'll post in that ticket.
