### ISSUE TITLE
RxJS Angular Documentation sets scope.name twice

### ISSUE THREAD

**Issue by RyanDawkins** [Reactive-Extensions/RxJS#991]
This isn't a major issue, but I noticed scope.name was set twice in some documentation.

Here is where I found the sets twice: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/howdoi/angular.md#integration-with-scopes

I propose to remove the second set to scope.name. 

Can I fork/pull to make this change?

**Comment by mattpodwysocki** [comment]
@RyanDawkins sure

**Comment by RyanDawkins** [comment]
@mattpodwysocki 

I made a pull request at #996
