### ISSUE TITLE
Implementing Elm Signals

### ISSUE THREAD

**Issue by ccorcos** [Reactive-Extensions/RxJS#992]
## Context

I'm looking at the [Elm Architecture Tutorial][arch] and trying to implement it in javascript. I've been good so far without using any external libraries other than React. But by step 5 in the tutorial, I really need to use streams of some kind if I want to maintain pure functional programming. 

[This is what I eventually need to recreate][start]. 

## Question

There are a few things I'm trying to figure out. 

1) How can I create a stream and then write to it on demand?

```jsx
x = Rx.Observable.empty()
x.subscribe(console.log.bind(console))
x.onNext(10) // error
x(10)  // error
```

2) How can I forward one stream to another?

```jsx
parent = Rx.Observable.empty()
parent.subscribe(console.log.bind(console))
child = Rx.Observable.empty()
child.map(function(x) {return 'emit from child: ' + x }).forwardTo(parent)
// writing to the child will map and then emit to the parent.
```

3) How can I set an initial value of the accumulator in scan? I'm trying to make a basic version of [this][start].

```jsx
let action$ = Rx.Observable.empty()

// (action, state) -> state
function update(state, action) {
  return state + action
}

let model$ = action$.scan(reduce, initialState)

// render the view with the state and the action stream
model$.subscribe(function(state) {
  ReactDOM.render(view(action$, state), document,body)
})

ReactDOM.render(view(action$, initialState), document,body)

// render a state that dispatches to the observable.
function view(action$, state) {
  return (
    <div>
      <button onClick={() => action$.onNext(1)}>Increment</button>
      {state}
      <button onClick={() => action$.onNext(-1)}>Decrement</button>
    </div>
  )
}
```

[arch]: https://github.com/evancz/elm-architecture-tutorial/
[start]: https://github.com/evancz/start-app/blob/2.0.1/src/StartApp.elm#L80-L117

**Comment by xgrommx** [comment]
About 1 question. Take a look at [`Subject`](http://xgrommx.github.io/rx-book/content/subjects/subject/index.html). About 2 question - take a look at ['flatMap'](http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/flatmap.html) About 3 question - try this one `let model$ = action$.startWith(initialState).scan(reduce)`

**Comment by ccorcos** [comment]
Awesome. Thanks for the help.

I'm running into some weird issues -- I think it has to do with hot vs cold observables. I'm not sure when I should be mapping or subscribing...

```coffee
# config = {init:{model, effects}, update, view, inputs=[]}
# inputs is an array of observables that emit actions.
start = (config) ->
  # views send actions to this address
  address = new Rx.Subject()
  
  # all actions, external and internal
  messages = Rx.Observable.merge((config.inputs or []).concat(address))
  
  updateStep = (prev, action) ->
    console.log "UPDATE"
    next = config.update(action, prev.model)
    model: next.model
    effects: next.effects
  
  modelAndEffects = messages.startWith(config.init).scan(updateStep)

  model = modelAndEffects.map(prop('model'))
  effects = modelAndEffects.map(prop('effects'))

  # pipe all effects actions to the address
  tasks = effects.filter(truthy).map (promises) ->
    console.log "TASKS"
    promises.map (promise) -> 
      promise.then(address.onNext.bind(address)).catch(address.onNext.bind(address))
  
  html = model.map (instance) -> 
    config.view(address.onNext.bind(address), instance)

  return {html, model, messages}
```

With this setup, then the tasks never get run. When I change that from tasks.map to subscribe, then I get duplicate updates for some reason and I still dont see any tasks run...

**Comment by ccorcos** [comment]
Hmm. I have the feeling it has to do with this:

```coffee
  model = modelAndEffects.map(prop('model'))
  effects = modelAndEffects.map(prop('effects'))
```

They're both subscribed to, so they seem to pull events through twice... thats no good.

**Comment by ccorcos** [comment]
This is what I do in the main part of the program:

```coffee

{html, model, messages} = start({init: init(), update, view})

# render html and run tasks
html.subscribe (tree) -> render(tree, document.getElementById('root'))


Rx = require('rx-lite')

logger = Rx.Observable.merge(
  model.map (x) ->    "model:   #{JSON.stringify(x)}" 
  messages.map (x) -> "message: #{JSON.stringify(x)}"
).subscribe(console.log.bind(console))

```

**Comment by ccorcos** [comment]
Here's the project I'm working on for reference: https://github.com/ccorcos/elmish

**Comment by xgrommx** [comment]
Hi @ccorcos. I forgot about a very helpful article from @staltz. Please read this one https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

**Comment by ccorcos** [comment]
Hmm. I ended up just using [flyd](https://github.com/paldepind/flyd). Its working really well and it was a breeze. Its also modeled after elm signals. Check out how clean the result is!

https://github.com/ccorcos/elmish/blob/master/elmish.coffee#L15-L19
