### ISSUE TITLE
'Flatmap performace' was deleted?

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#994]
Hello @paulpdaniels and @mattpodwysocki. Looks like this PR was rejected or deleted https://github.com/Reactive-Extensions/RxJS/pull/822. I would like know reason for this.

**Comment by paulpdaniels** [comment]
@xgrommx no it was merged. I deleted my local branch afterward.

**Comment by xgrommx** [comment]
@paulpdaniels I don't see changes. Please to point me to changes.

**Comment by mattpodwysocki** [comment]
@xgrommx the changes are here: https://github.com/Reactive-Extensions/RxJS/commit/f6340e9d6880eba2834dadcab78138510560c054
